import { SmartSearchCatalogItem } from './types';

const BEARING_THREAD = [
  'ts-a3-belt-drive',
  'task-wo-2481',
  'asset-station-12',
  'doc-bearing-maintenance-guide',
  'shift-note-331',
  'training-awareness',
  'notif-line-alert',
  '3d-conveyor-station-12',
  'action-track-1042',
  'eso-2026-122',
  'doc-inspection-manual',
  'task-log-observation',
];

const bearingTags = ['station-12', 'bearing', 'line-a3', 'wo-2481', 'vibration'];

export function getGlobalSearchCatalog(currentUserName: string): Record<
  Exclude<import('../types').SmartSearchCategory, 'All'>,
  SmartSearchCatalogItem[]
> {
  const documents: SmartSearchCatalogItem[] = [
    {
      id: 'doc-bearing-maintenance-guide',
      category: 'Documents',
      kind: 'document',
      fileType: 'PDF',
      title: 'Conveyor Belt Bearing Maintenance Guidelines',
      subtitle: 'PDF • Reliability • Production Line A3',
      summary: 'Comprehensive guide covering conveyor bearing vibration impact, escalation thresholds, lubrication steps, and work-order documentation.',
      status: 'Relevant',
      tone: '#044ED7',
      metric: '8 relevant sections',
      secondaryMetric: 'Updated 2 weeks ago',
      location: 'Document Manager',
      plant: 'Line A3',
      updated: 'Updated 2 weeks ago',
      keywords: ['bearing', 'maintenance', 'guide', 'vibration', 'document', 'lubrication', 'escalation'],
      relatedIds: BEARING_THREAD.filter((id) => id !== 'doc-bearing-maintenance-guide'),
      entityTags: bearingTags,
      detail: {
        summary: 'Defines warning (2.8 mm/s) and critical (4.5 mm/s) thresholds used by the line monitoring system.',
        folderPath: ['BD Global', 'Americas', 'Sandy', 'Reliability', 'Line A3', 'Maintenance Documents'],
        highlights: [
          'Section 4.2: Escalate to maintenance when RMS velocity exceeds 2.8 mm/s.',
          'Section 6.1: Stop the asset when vibration and temperature rise together.',
          'Appendix B: Work-order template for bearing verification issues.',
        ],
      },
    },
    {
      id: 'doc-inspection-manual',
      category: 'Documents',
      kind: 'document',
      fileType: 'DOC',
      title: 'Inspection & Monitoring Manual',
      subtitle: 'Manual • Reliability',
      summary: 'SOP to identify abnormal vibration, noise patterns, and temperature changes in conveyor bearings before failure.',
      status: 'Recommended',
      tone: '#0ea5e9',
      metric: '4 procedures',
      secondaryMetric: 'Updated 6 days ago',
      location: 'Document Manager',
      plant: 'Reliability',
      updated: 'Updated 6 days ago',
      keywords: ['inspection', 'manual', 'vibration', 'monitoring', 'bearing', 'procedure', 'operator'],
      relatedIds: ['training-awareness', 'doc-bearing-maintenance-guide', 'task-wo-2481'],
      entityTags: [...bearingTags, 'inspection'],
      detail: {
        summary: 'Frontline inspection steps operators can perform before handing off to maintenance.',
        folderPath: ['BD Global', 'Americas', 'Sandy', 'Reliability', 'Inspection Procedures'],
        highlights: [
          'Use sight, sound, and touch checks only if the asset is safe to inspect.',
          'Escalate when vibration changes are accompanied by squeal or grinding.',
        ],
      },
    },
    {
      id: 'doc-hydraulic-press-sop',
      category: 'Documents',
      kind: 'document',
      fileType: 'PDF',
      title: 'Hydraulic Press #4 Lubrication SOP',
      subtitle: 'PDF • Maintenance • Press Cell',
      summary: 'Step-by-step lubrication and inspection procedure for hydraulic press cell 04 including guarded zones and lockout requirements.',
      status: 'Active',
      tone: '#0f766e',
      metric: '6 steps',
      secondaryMetric: 'Updated 1 week ago',
      location: 'Document Manager',
      plant: 'Press Cell / Line 4',
      updated: 'Updated 1 week ago',
      keywords: ['hydraulic', 'press', 'lubrication', 'sop', 'maintenance', 'line 4'],
      relatedIds: ['3d-press-cell-04', 'asset-hydraulic-press-04'],
      entityTags: ['press-04', 'hydraulic', 'line-4', 'lubrication'],
      detail: {
        summary: 'Covers pre-inspection, lubrication points, and post-service verification for press cell 04.',
        folderPath: ['BD Global', 'Americas', 'Sandy', 'Maintenance', 'Press Cell'],
        highlights: ['Verify lockout before any lubrication round.', 'Document any abnormal pressure readings.'],
      },
    },
    {
      id: 'doc-shift-handoff-template',
      category: 'Documents',
      kind: 'document',
      fileType: 'DOC',
      title: 'Shift Handoff Template — Reliability Exceptions',
      subtitle: 'Template • Operations',
      summary: 'Standard template for documenting equipment exceptions, linked work orders, and follow-up actions during shift handoff.',
      status: 'Recommended',
      tone: '#2563EB',
      metric: '3 sections',
      secondaryMetric: 'Updated 3 days ago',
      location: 'Document Manager',
      plant: 'Operations',
      updated: 'Updated 3 days ago',
      keywords: ['shift', 'handoff', 'template', 'reliability', 'exception', 'logbook'],
      relatedIds: ['shift-note-331', 'task-log-observation', 'training-log-issue'],
      entityTags: ['handoff', 'shift', 'operations'],
      detail: {
        summary: 'Ensures consistent handoff quality for reliability and maintenance exceptions.',
        folderPath: ['BD Global', 'Operations', 'Shift Excellence', 'Templates'],
        highlights: ['Include asset ID, vibration reading, and linked WO number.', 'Tag severity for Control Tower visibility.'],
      },
    },
    {
      id: 'doc-employee-handbook',
      category: 'Documents',
      kind: 'document',
      fileType: 'PDF',
      title: 'Employee Handbook — E-Signature Pending',
      subtitle: 'PDF • HR • Global',
      summary: 'Updated employee handbook requiring e-signature approval. Overdue approval is blocking one downstream workflow.',
      status: 'Overdue',
      tone: '#FF6E00',
      metric: '1 approval pending',
      secondaryMetric: 'Overdue 1 day',
      location: 'Document Manager',
      plant: 'Global HR',
      updated: 'Overdue 1 day',
      keywords: ['employee handbook', 'e-signature', 'approval', 'document', 'overdue'],
      relatedIds: ['notif-doc-approval'],
      entityTags: ['hr', 'approval', 'esignature'],
      detail: {
        summary: 'Quality team approval is overdue and affecting Action Tracker follow-through.',
        folderPath: ['BD Global', 'HR', 'Policies'],
        highlights: ['Approval required before next compliance audit window.'],
      },
    },
    {
      id: 'doc-tier1-brief',
      category: 'Documents',
      kind: 'document',
      fileType: 'PDF',
      title: 'Tier 1 Meeting Brief — Line A3 Status',
      subtitle: 'PDF • Tier 1 • Operations',
      summary: 'Pre-meeting brief covering Line A3 blockers, bearing escalation context, and open action tracker items.',
      status: 'Ready',
      tone: '#9199D8',
      metric: '5 blockers',
      secondaryMetric: 'Updated today',
      location: 'Document Manager',
      plant: 'Line A3',
      updated: 'Updated today',
      keywords: ['tier 1', 'meeting', 'brief', 'line a3', 'blockers', 'bearing'],
      relatedIds: ['action-track-1042', 'action-track-1058', 'notif-line-alert'],
      entityTags: ['tier-1', 'line-a3', 'meeting'],
      detail: {
        summary: 'Summarizes the three blockers queued for the next Tier 1 meeting.',
        folderPath: ['BD Global', 'Operations', 'Tier 1', 'Briefs'],
        highlights: ['Bearing verification follow-up is the highest-priority blocker.'],
      },
    },
    {
      id: 'doc-spare-parts-catalog',
      category: 'Documents',
      kind: 'document',
      fileType: 'PDF',
      title: 'Conveyor Bearing Spare Parts Catalog',
      subtitle: 'PDF • Tool Crib • Maintenance',
      summary: 'Catalog of approved spare parts for conveyor bearing assemblies including SKU cross-reference and safety stock levels.',
      status: 'Reference',
      tone: '#0f766e',
      metric: '24 SKUs',
      secondaryMetric: 'Updated 1 month ago',
      location: 'Document Manager',
      plant: 'Tool Crib',
      updated: 'Updated 1 month ago',
      keywords: ['spare parts', 'bearing', 'catalog', 'sku', 'inventory', 'tool crib'],
      relatedIds: ['asset-station-12', 'task-wo-2481'],
      entityTags: ['spare-parts', 'bearing', 'inventory'],
      detail: {
        summary: 'Links bearing assembly SKUs to Station 12 and CV-101 conveyor variants.',
        folderPath: ['BD Global', 'Maintenance', 'Spare Parts', 'Catalogs'],
        highlights: ['Primary bearing SKU: BRG-A3-S12-001', 'Safety stock threshold: 2 units'],
      },
    },
    {
      id: 'doc-centerline-params',
      category: 'Documents',
      kind: 'document',
      fileType: 'DOC',
      title: 'Centerline Parameter Checklist — Line A3',
      subtitle: 'DOC • Quality • Line A3',
      summary: 'Daily centerline parameter monitoring checklist for Line A3 including conveyor speed and vibration correlation points.',
      status: 'Active',
      tone: '#0891b2',
      metric: '12 parameters',
      secondaryMetric: 'Updated 4 days ago',
      location: 'Document Manager',
      plant: 'Line A3',
      updated: 'Updated 4 days ago',
      keywords: ['centerline', 'parameters', 'line a3', 'quality', 'monitoring'],
      relatedIds: ['ts-a3-belt-drive', 'ts-a3-oee'],
      entityTags: ['centerline', 'line-a3', 'quality'],
      detail: {
        summary: 'Parameter drift on conveyor speed can precede bearing vibration escalation.',
        folderPath: ['BD Global', 'Quality', 'Centerline', 'Line A3'],
        highlights: ['Check conveyor speed deviation before each shift start.'],
      },
    },
  ];

  const tasks: SmartSearchCatalogItem[] = [
    {
      id: 'task-wo-2481',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Work Order',
      taskState: 'Overdue',
      priority: 'Critical',
      title: 'WO-2481 Conveyor Verification',
      subtitle: 'Maintenance • Critical',
      summary: 'Bearing verification due before next handoff, linked to Station 12 anomaly and critical vibration trend.',
      status: 'Due today',
      tone: '#E43B46',
      metric: 'Today 14:30',
      secondaryMetric: 'Owner: Maintenance',
      location: 'Work Order Hub',
      plant: 'Production Line A3',
      updated: 'Due today',
      keywords: ['work order', 'wo-2481', 'bearing', 'verification', 'maintenance', 'conveyor', 'critical'],
      relatedIds: BEARING_THREAD.filter((id) => id !== 'task-wo-2481'),
      entityTags: bearingTags,
      detail: {
        owner: 'Maintenance',
        due: 'Today 14:30',
        equipment: 'Station 12 Conveyor',
        nextStep: 'Confirm bearing inspection result and update shift handoff before close.',
      },
    },
    {
      id: 'task-log-observation',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Task',
      taskState: 'Open',
      priority: 'Medium',
      title: 'Log bearing observation for next shift',
      subtitle: 'Shift Handoff • Ready',
      summary: 'Handoff note needed so next operator sees vibration condition and linked WO-2481 immediately.',
      status: 'Ready',
      tone: '#044ED7',
      metric: 'Before handoff',
      secondaryMetric: `Owner: ${currentUserName}`,
      location: 'Shift Logbook',
      plant: 'Production Line A3',
      updated: 'Before handoff',
      keywords: ['shift', 'handoff', 'bearing', 'logbook', 'observation', 'wo-2481'],
      relatedIds: ['shift-note-331', 'task-wo-2481', 'training-log-issue'],
      entityTags: [...bearingTags, 'handoff'],
      detail: {
        owner: currentUserName,
        due: 'Before handoff',
        nextStep: 'Use BLU.AI to prefill note with vibration value, asset, and linked work order.',
      },
    },
    {
      id: 'task-wo-2476',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Work Order',
      taskState: 'Scheduled',
      priority: 'High',
      title: 'WO-2476 Lubrication Round — Station 12',
      subtitle: 'Maintenance • Scheduled',
      summary: 'Scheduled lubrication round for Station 12 conveyor bearing assembly. Delay may accelerate vibration trend.',
      status: 'Scheduled',
      tone: '#FF6E00',
      metric: 'Tomorrow 08:00',
      secondaryMetric: 'Owner: Reliability',
      location: 'Work Order Hub',
      plant: 'Production Line A3',
      updated: 'Scheduled',
      keywords: ['work order', 'lubrication', 'station 12', 'bearing', 'maintenance'],
      relatedIds: ['asset-station-12', 'shift-note-334', 'eso-2026-118'],
      entityTags: ['station-12', 'lubrication', 'wo-2476'],
      detail: {
        owner: 'Reliability',
        due: 'Tomorrow 08:00',
        equipment: 'Station 12 Conveyor',
        nextStep: 'Complete lubrication before next production window.',
      },
    },
    {
      id: 'task-wo-2490',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Work Order',
      taskState: 'In Progress',
      priority: 'Medium',
      title: 'WO-2490 Hydraulic Press Inspection',
      subtitle: 'Maintenance • In Progress',
      summary: 'Routine inspection of hydraulic press #4 including lubrication points and pressure verification.',
      status: 'In progress',
      tone: '#0f766e',
      metric: 'This week',
      secondaryMetric: 'Owner: Maintenance',
      location: 'Work Order Hub',
      plant: 'Press Cell / Line 4',
      updated: 'In progress',
      keywords: ['work order', 'hydraulic', 'press', 'inspection', 'line 4'],
      relatedIds: ['3d-press-cell-04', 'asset-hydraulic-press-04', 'doc-hydraulic-press-sop'],
      entityTags: ['press-04', 'inspection'],
      detail: {
        owner: 'Maintenance',
        due: 'This week',
        equipment: 'Hydraulic Press #4',
        nextStep: 'Complete pressure check and update equipment ledger.',
      },
    },
    {
      id: 'task-pm-1847',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Work Order',
      taskState: 'Open',
      priority: 'Low',
      title: 'PM-1847 Monthly Bearing Trend Review',
      subtitle: 'Preventive Maintenance • Open',
      summary: 'Monthly review of bearing vibration trends across Line A3 assets for predictive maintenance planning.',
      status: 'Open',
      tone: '#2563EB',
      metric: 'Due in 5 days',
      secondaryMetric: 'Owner: Reliability',
      location: 'Maintenance Planner',
      plant: 'Line A3',
      updated: 'Due in 5 days',
      keywords: ['preventive', 'maintenance', 'bearing', 'trend', 'predictive', 'pm'],
      relatedIds: ['ts-a3-belt-drive', 'ts-a3-temperature'],
      entityTags: ['predictive', 'bearing', 'line-a3'],
      detail: {
        owner: 'Reliability',
        due: 'Due in 5 days',
        nextStep: 'Compare 30-day vibration trends and update PM schedule if needed.',
      },
    },
    {
      id: 'task-wo-2501',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Work Order',
      taskState: 'Open',
      priority: 'High',
      title: 'WO-2501 Replace Drive Bearing — CV-101',
      subtitle: 'Maintenance • Planning',
      summary: 'Planning work order to replace CV-101 drive bearing if verification confirms escalation beyond critical threshold.',
      status: 'Ready to plan',
      tone: '#E43B46',
      metric: 'Pending verification',
      secondaryMetric: 'Owner: Maintenance',
      location: 'Work Order Hub',
      plant: 'Production Line A3',
      updated: 'Created today',
      keywords: ['work order', 'replace', 'drive bearing', 'cv-101', 'planning'],
      relatedIds: ['task-wo-2481', 'asset-station-12', 'doc-spare-parts-catalog'],
      entityTags: ['cv-101', 'bearing', 'replacement'],
      detail: {
        owner: 'Maintenance',
        due: 'After WO-2481 verification',
        equipment: 'CV-101 Conveyor',
        nextStep: 'Await WO-2481 result before scheduling replacement window.',
      },
    },
    {
      id: 'task-cil-892',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Task',
      taskState: 'Open',
      priority: 'Medium',
      title: 'CIL-892 Clean conveyor service aisle',
      subtitle: 'CIL • Operator Task',
      summary: 'Operator CIL task to clean conveyor service aisle — linked to ESO slip hazard report.',
      status: 'Open',
      tone: '#06b6d4',
      metric: 'Due this shift',
      secondaryMetric: 'Owner: Operations',
      location: 'CIL Hub',
      plant: 'Line A3',
      updated: 'Due this shift',
      keywords: ['cil', 'clean', 'conveyor', 'service aisle', 'housekeeping'],
      relatedIds: ['eso-2026-118', 'shift-note-334'],
      entityTags: ['cil', 'housekeeping', 'line-a3'],
      detail: {
        owner: 'Operations',
        due: 'Due this shift',
        nextStep: 'Complete cleaning before lubrication round.',
      },
    },
    {
      id: 'task-doc-approval',
      category: 'Tasks & Work Orders',
      kind: 'task',
      taskType: 'Task',
      taskState: 'Overdue',
      priority: 'High',
      title: 'Approve Employee Handbook E-Signature',
      subtitle: 'Document Approval • Overdue',
      summary: 'E-signature approval overdue by 1 day — blocking downstream workflow in Action Tracker.',
      status: 'Overdue',
      tone: '#FF6E00',
      metric: 'Overdue 1 day',
      secondaryMetric: 'Owner: Quality',
      location: 'Document Manager',
      plant: 'Global HR',
      updated: 'Overdue 1 day',
      keywords: ['approval', 'e-signature', 'document', 'overdue', 'handbook'],
      relatedIds: ['doc-employee-handbook', 'notif-doc-approval'],
      entityTags: ['approval', 'document'],
      detail: {
        owner: 'Quality',
        due: 'Overdue',
        nextStep: 'Complete e-signature approval to unblock workflow.',
      },
    },
  ];

  const assets: SmartSearchCatalogItem[] = [
    {
      id: 'asset-station-12',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/maquina-fabrica.png',
      title: 'Station 12 Conveyor — Primary Bearing',
      subtitle: 'Asset • Production Line A3',
      summary: 'Conveyor bearing assembly showing elevated vibration at 6.80 mm/s RMS with linked WO-2481 and critical time-series trend.',
      status: 'At risk',
      tone: '#E43B46',
      metric: '6.80 mm/s',
      secondaryMetric: 'Updated 8 min ago',
      location: 'Production Line A3',
      plant: 'Station 12',
      updated: 'Updated 8 min ago',
      keywords: ['station 12', 'conveyor', 'bearing', 'asset', 'vibration', 'critical'],
      relatedIds: BEARING_THREAD.filter((id) => id !== 'asset-station-12'),
      entityTags: bearingTags,
      detail: {
        assetId: 'BRG-A3-S12',
        owner: 'Area A Operations',
        temperature: '65°C',
        vibration: '6.80 mm/s RMS',
        nextStep: 'Complete physical check and confirm whether watch signal should escalate.',
      },
    },
    {
      id: 'asset-hydraulic-press-04',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/maquina-fabrica.png',
      title: 'Hydraulic Press #4',
      subtitle: 'Asset • Press Cell',
      summary: 'Hydraulic press in healthy state with upcoming inspection WO-2490 and linked 3D spatial maintenance view.',
      status: 'Healthy',
      tone: '#00AF95',
      metric: 'Normal',
      secondaryMetric: 'Updated 1 hour ago',
      location: 'Press Cell',
      plant: 'Line 4',
      updated: 'Updated 1 hour ago',
      keywords: ['hydraulic', 'press', 'asset', 'line 4', 'healthy'],
      relatedIds: ['3d-press-cell-04', 'task-wo-2490', 'doc-hydraulic-press-sop'],
      entityTags: ['press-04', 'hydraulic'],
      detail: {
        assetId: 'HP-04-S3',
        owner: 'Reliability',
        temperature: '42°C',
        vibration: '0.8 mm/s RMS',
        nextStep: 'Continue scheduled inspection per WO-2490.',
      },
    },
    {
      id: 'asset-cv101',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/Line1.png',
      title: 'CV-101 Entry Conveyor',
      subtitle: 'Asset • Conveyor Feed',
      summary: 'Entry conveyor feeding the filling and assembly sequence. Drive bearing is the primary vibration source.',
      status: 'Watch',
      tone: '#FF7A00',
      metric: 'Watch condition',
      secondaryMetric: 'Updated 15 min ago',
      location: 'Production Line A3',
      plant: 'Conveyor Cell',
      updated: 'Updated 15 min ago',
      keywords: ['cv-101', 'conveyor', 'asset', 'drive bearing', 'feed'],
      relatedIds: ['asset-station-12', 'ts-a3-belt-drive', 'task-wo-2501'],
      entityTags: ['cv-101', 'conveyor', 'bearing'],
      detail: {
        assetId: 'CONV-A3-CV101',
        owner: 'Maintenance',
        temperature: '58°C',
        vibration: '5.2 mm/s RMS',
        nextStep: 'Monitor trend correlation with Station 12 primary bearing.',
      },
    },
    {
      id: 'asset-filling-head',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/Line1.png',
      title: 'Filling Head Assembly — Line A3',
      subtitle: 'Asset • Filling System',
      summary: 'Filling head assembly with servo motor and nozzle cluster. No active anomalies but in same operating window as conveyor escalation.',
      status: 'Normal',
      tone: '#2563EB',
      metric: 'Stable',
      secondaryMetric: 'Updated 30 min ago',
      location: 'Production Line A3',
      plant: 'Filling Cell',
      updated: 'Updated 30 min ago',
      keywords: ['filling head', 'assembly', 'line a3', 'servo', 'nozzle'],
      relatedIds: ['asset-station-12'],
      entityTags: ['filling', 'line-a3'],
      detail: {
        assetId: 'FILL-A3-HEAD',
        owner: 'Manufacturing Engineering',
        temperature: '38°C',
        vibration: '1.1 mm/s RMS',
        nextStep: 'No action required — monitor if conveyor stop affects feed rate.',
      },
    },
    {
      id: 'asset-vision-vi210',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/Line1.png',
      title: 'Vision Inspection VI-210',
      subtitle: 'Asset • Quality Gate',
      summary: 'Downstream quality gate on Line A3. Inspection reject rate stable; not contributing to current bearing escalation.',
      status: 'Healthy',
      tone: '#00AF95',
      metric: '0.3% reject',
      secondaryMetric: 'Updated 45 min ago',
      location: 'Production Line A3',
      plant: 'Quality Zone',
      updated: 'Updated 45 min ago',
      keywords: ['vision', 'inspection', 'vi-210', 'quality', 'line a3'],
      relatedIds: [],
      entityTags: ['vision', 'quality', 'line-a3'],
      detail: {
        assetId: 'VI-210-A3',
        owner: 'Quality',
        temperature: '32°C',
        vibration: '0.2 mm/s RMS',
        nextStep: 'Continue standard calibration schedule.',
      },
    },
    {
      id: 'asset-cartoner-ct32',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/Line1.png',
      title: 'Cartoner CT-32',
      subtitle: 'Asset • Pack-out',
      summary: 'Final pack-out dependency before zone release. Throughput aligned with Line A3 target.',
      status: 'Healthy',
      tone: '#00AF95',
      metric: 'On target',
      secondaryMetric: 'Updated 1 hour ago',
      location: 'Production Line A3',
      plant: 'Pack-out Zone',
      updated: 'Updated 1 hour ago',
      keywords: ['cartoner', 'ct-32', 'pack-out', 'line a3'],
      relatedIds: [],
      entityTags: ['cartoner', 'pack-out'],
      detail: {
        assetId: 'CT-32-A3',
        owner: 'Operations',
        temperature: '35°C',
        vibration: '0.5 mm/s RMS',
        nextStep: 'No action required.',
      },
    },
    {
      id: 'asset-labeling-lm7',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/Line1.png',
      title: 'Labeling Module LM-7',
      subtitle: 'Asset • Labeling',
      summary: 'Labeling module between inspection and cartoner. Minor calibration drift noted in last PM.',
      status: 'Watch',
      tone: '#FF7A00',
      metric: 'Calibration drift',
      secondaryMetric: 'Updated 2 hours ago',
      location: 'Production Line A3',
      plant: 'Labeling Zone',
      updated: 'Updated 2 hours ago',
      keywords: ['labeling', 'lm-7', 'calibration', 'line a3'],
      relatedIds: ['task-pm-1847'],
      entityTags: ['labeling', 'calibration'],
      detail: {
        assetId: 'LM-7-A3',
        owner: 'Maintenance',
        temperature: '36°C',
        vibration: '0.4 mm/s RMS',
        nextStep: 'Schedule calibration check in next PM window.',
      },
    },
    {
      id: 'asset-servo-motor',
      category: 'Assets',
      kind: 'asset',
      thumbnail: '/images/maquina-fabrica.png',
      title: 'Servo Motor — Filling Head Drive',
      subtitle: 'Asset • Drive System',
      summary: 'Servo motor driving filling head assembly. Temperature and vibration within normal operating range.',
      status: 'Healthy',
      tone: '#00AF95',
      metric: 'Normal',
      secondaryMetric: 'Updated 1 hour ago',
      location: 'Production Line A3',
      plant: 'Filling Cell',
      updated: 'Updated 1 hour ago',
      keywords: ['servo', 'motor', 'filling', 'drive'],
      relatedIds: ['asset-filling-head'],
      entityTags: ['servo', 'filling'],
      detail: {
        assetId: 'SERVO-FILL-A3',
        owner: 'Manufacturing Engineering',
        temperature: '40°C',
        vibration: '0.9 mm/s RMS',
        nextStep: 'No action required.',
      },
    },
  ];

  const timeSeries: SmartSearchCatalogItem[] = [
    {
      id: 'ts-a3-belt-drive',
      category: 'Time Series',
      kind: 'timeSeries',
      title: 'Belt Drive System A3-001 - Primary Bearing',
      subtitle: 'RMS Conveyor Velocity',
      summary: '24-hour trend above warning threshold with multiple critical threshold crossings in the last two hours.',
      status: 'Critical',
      tone: '#E43B46',
      metric: '6.80 mm/s',
      secondaryMetric: 'Updated 16:15:32',
      location: 'Production Line A3',
      plant: 'Primary Conveyor',
      updated: 'Updated just now',
      keywords: ['bearing', 'vibration', 'timeseries', 'trend', 'conveyor', 'critical', 'mm/s', 'station 12'],
      relatedIds: BEARING_THREAD.filter((id) => id !== 'ts-a3-belt-drive'),
      entityTags: bearingTags,
      detail: {
        warning: '2.80 mm/s',
        critical: '4.50 mm/s',
        points: [5.7, 5.2, 5.9, 5.4, 6.1, 6.2, 5.5, 5.7, 6.3, 6.1, 5.8, 6.4, 6.0, 6.7, 6.2, 6.8],
        anomalies: [8, 13, 15],
      },
    },
    {
      id: 'ts-a3-temperature',
      category: 'Time Series',
      kind: 'timeSeries',
      title: 'Station 12 Bearing Temperature',
      subtitle: 'Surface Temperature Trend',
      summary: 'Temperature rising in correlation with vibration spike — combined signal indicates active failure progression.',
      status: 'Warning',
      tone: '#FF6E00',
      metric: '65°C',
      secondaryMetric: 'Updated 10 min ago',
      location: 'Production Line A3',
      plant: 'Station 12',
      updated: 'Updated 10 min ago',
      keywords: ['temperature', 'bearing', 'station 12', 'trend', 'timeseries'],
      relatedIds: ['ts-a3-belt-drive', 'asset-station-12'],
      entityTags: [...bearingTags, 'temperature'],
      detail: {
        warning: '55°C',
        critical: '70°C',
        points: [52, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 64, 65, 66, 65],
        anomalies: [11, 14, 15],
      },
    },
    {
      id: 'ts-a3-oee',
      category: 'Time Series',
      kind: 'timeSeries',
      title: 'Line A3 Overall Equipment Effectiveness',
      subtitle: 'OEE % — Last 24 Hours',
      summary: 'OEE softened to 88.4% with micro-stop concentration around Station 12 conveyor events.',
      status: 'Watch',
      tone: '#FF7A00',
      metric: '88.4%',
      secondaryMetric: 'Updated 30 min ago',
      location: 'Production Line A3',
      plant: 'Line A3',
      updated: 'Updated 30 min ago',
      keywords: ['oee', 'performance', 'line a3', 'downtime', 'timeseries'],
      relatedIds: ['asset-station-12', 'shift-note-331'],
      entityTags: ['oee', 'line-a3', 'performance'],
      detail: {
        warning: '90%',
        critical: '85%',
        points: [92, 91, 90, 89, 90, 89, 88, 89, 88, 87, 88, 87, 88, 88, 88, 88.4],
        anomalies: [9, 11],
      },
    },
    {
      id: 'ts-press-pressure',
      category: 'Time Series',
      kind: 'timeSeries',
      title: 'Hydraulic Press #4 System Pressure',
      subtitle: 'Operating Pressure Trend',
      summary: 'Press system pressure stable within normal operating band for Line 4 press cell.',
      status: 'Normal',
      tone: '#00AF95',
      metric: '142 bar',
      secondaryMetric: 'Updated 1 hour ago',
      location: 'Press Cell',
      plant: 'Line 4',
      updated: 'Updated 1 hour ago',
      keywords: ['pressure', 'hydraulic', 'press', 'timeseries', 'line 4'],
      relatedIds: ['asset-hydraulic-press-04'],
      entityTags: ['press-04', 'pressure'],
      detail: {
        warning: '160 bar',
        critical: '175 bar',
        points: [140, 141, 142, 141, 142, 143, 142, 141, 142, 142, 141, 142, 143, 142, 142, 142],
        anomalies: [],
      },
    },
    {
      id: 'ts-line-throughput',
      category: 'Time Series',
      kind: 'timeSeries',
      title: 'Line A3 Throughput Rate',
      subtitle: 'Units per Hour',
      summary: 'Throughput trending down 4.6% in last 2 hours correlated with conveyor micro-stops at Station 12.',
      status: 'Watch',
      tone: '#FF7A00',
      metric: '-4.6%',
      secondaryMetric: 'Updated 20 min ago',
      location: 'Production Line A3',
      plant: 'Line A3',
      updated: 'Updated 20 min ago',
      keywords: ['throughput', 'production', 'line a3', 'timeseries', 'rate'],
      relatedIds: ['ts-a3-oee', 'asset-station-12'],
      entityTags: ['throughput', 'line-a3'],
      detail: {
        warning: '-3%',
        critical: '-8%',
        points: [100, 99, 98, 98, 97, 97, 96, 96, 95, 96, 95, 95, 96, 95, 95, 95.4],
        anomalies: [8, 10],
      },
    },
  ];

  const threeD: SmartSearchCatalogItem[] = [
    {
      id: '3d-conveyor-station-12',
      category: '3D',
      kind: '3d',
      title: 'Conveyor Station 12 - Interactive 3D Twin',
      subtitle: '3D Asset View - Maintenance Context',
      summary: 'Interactive 3D twin with linked manual, spare parts, and maintenance routine context for reliability diagnosis.',
      status: '3D Ready',
      tone: '#2563eb',
      metric: '3D twin',
      secondaryMetric: 'Updated 20 min ago',
      location: 'Production Line A3',
      plant: 'Station 12',
      updated: '20 min ago',
      keywords: ['3d', 'asset twin', 'station 12', 'conveyor', 'maintenance'],
      relatedIds: BEARING_THREAD.filter((id) => id !== '3d-conveyor-station-12'),
      entityTags: bearingTags,
      detail: {
        description: '3D digital twin mapping vibration-critical components with maintenance documentation links.',
        hierarchy: ['Sandy Plant', 'Area A', 'Line A3', 'Conveyor Cell', 'Station 12'],
        context: [
          { label: 'Asset ID', value: 'CONV-A3-ST12' },
          { label: 'Equipment Class', value: 'Conveyor Bearing Assembly' },
          { label: 'Current Owner', value: 'Maintenance' },
        ],
        kpis: [
          { label: 'Tagged components', value: '24', tone: '#2563eb' },
          { label: 'Linked docs', value: '3', tone: '#0f766e' },
          { label: 'Open actions', value: '2', tone: '#ef4444' },
        ],
      },
    },
    {
      id: '3d-press-cell-04',
      category: '3D',
      kind: '3d',
      title: 'Hydraulic Press Cell 04 - Spatial Maintenance View',
      subtitle: '3D Asset View - Reliability',
      summary: 'Spatial view with highlighted lubrication points and fast links to procedures.',
      status: '3D Ready',
      tone: '#0ea5e9',
      metric: 'Spatial model',
      secondaryMetric: 'Updated 1 hour ago',
      location: 'Press Cell',
      plant: 'Line 4',
      updated: '1 hour ago',
      keywords: ['3d', 'press', 'spatial', 'maintenance', 'lubrication'],
      relatedIds: ['asset-hydraulic-press-04', 'doc-hydraulic-press-sop'],
      entityTags: ['press-04', '3d'],
      detail: {
        description: 'Spatial maintenance view with highlighted service points and guarded zones.',
        hierarchy: ['Sandy Plant', 'Area C', 'Line 4', 'Press Cell', 'Press 04'],
        context: [
          { label: 'Asset ID', value: 'PRESS-L4-04' },
          { label: 'Equipment Class', value: 'Hydraulic Press' },
        ],
        kpis: [
          { label: 'Tagged components', value: '17', tone: '#0ea5e9' },
          { label: 'Linked docs', value: '2', tone: '#0f766e' },
        ],
      },
    },
    {
      id: '3d-line-a3-overview',
      category: '3D',
      kind: '3d',
      title: 'Line A3 Production Flow — 3D Overview',
      subtitle: '3D Line View',
      summary: 'Full Line A3 production flow from conveyor feed through filling, inspection, labeling, and cartoner.',
      status: '3D Ready',
      tone: '#2563eb',
      metric: 'Line model',
      secondaryMetric: 'Updated 2 hours ago',
      location: 'Production Line A3',
      plant: 'Line A3',
      updated: 'Updated 2 hours ago',
      keywords: ['3d', 'line a3', 'production', 'flow', 'overview'],
      relatedIds: ['asset-station-12', 'asset-filling-head'],
      entityTags: ['line-a3', '3d'],
      detail: {
        description: 'End-to-end line model for orientation and scope selection.',
        hierarchy: ['Sandy Plant', 'Area A', 'Line A3'],
        kpis: [{ label: 'Systems mapped', value: '8', tone: '#2563eb' }],
      },
    },
  ];

  const notifications: SmartSearchCatalogItem[] = [
    {
      id: 'notif-line-alert',
      category: 'Notifications',
      kind: 'notification',
      title: 'Critical vibration alert triggered on Line A3',
      subtitle: 'Operations Alert',
      summary: 'Primary bearing exceeded critical threshold three times in last two hours and remains above warning band.',
      status: 'Live alert',
      tone: '#E43B46',
      metric: '3 anomaly spikes',
      secondaryMetric: 'Triggered 12 min ago',
      location: 'Control Tower',
      plant: 'Production Line A3',
      updated: '12 min ago',
      keywords: ['alert', 'notification', 'bearing', 'critical', 'line a3', 'anomaly'],
      relatedIds: ['ts-a3-belt-drive', 'task-wo-2481'],
      entityTags: bearingTags,
      detail: { severity: 'Critical', action: 'Review work order and compare 24-hour trend before restart.' },
    },
    {
      id: 'notif-training',
      category: 'Notifications',
      kind: 'notification',
      title: 'Bearing awareness refresher assigned',
      subtitle: 'Learning Notification',
      summary: 'Refresher training recommended due to recurring vibration escalations on same asset type this month.',
      status: 'Suggested',
      tone: '#9199D8',
      metric: '1 training assigned',
      secondaryMetric: 'Triggered 1 hour ago',
      location: 'Training Center',
      plant: 'Reliability',
      updated: '1 hour ago',
      keywords: ['training', 'notification', 'bearing', 'awareness'],
      relatedIds: ['training-awareness'],
      entityTags: ['training', 'bearing'],
      detail: { severity: 'Informational', action: 'Start the 12-minute training or share with next operator.' },
    },
    {
      id: 'notif-doc-approval',
      category: 'Notifications',
      kind: 'notification',
      title: 'Employee Handbook approval overdue',
      subtitle: 'Document Alert',
      summary: 'E-signature approval is 1 day overdue and blocking Action Tracker workflow.',
      status: 'Overdue',
      tone: '#FF6E00',
      metric: '1 day overdue',
      secondaryMetric: 'Triggered 3 hours ago',
      location: 'Document Manager',
      plant: 'Global HR',
      updated: '3 hours ago',
      keywords: ['approval', 'overdue', 'document', 'notification', 'handbook'],
      relatedIds: ['doc-employee-handbook', 'task-doc-approval'],
      entityTags: ['approval', 'document'],
      detail: { severity: 'High', action: 'Complete approval to unblock downstream workflow.' },
    },
    {
      id: 'notif-tier-blocker',
      category: 'Notifications',
      kind: 'notification',
      title: 'Tier 1 blocker — bearing verification follow-up',
      subtitle: 'Tier 1 Alert',
      summary: 'Action ACT-1042 is blocking Tier 1 meeting closure until bearing verification is confirmed.',
      status: 'Active',
      tone: '#9199D8',
      metric: '1 blocker',
      secondaryMetric: 'Triggered 45 min ago',
      location: 'Tier 1 Meeting',
      plant: 'Line A3',
      updated: '45 min ago',
      keywords: ['tier 1', 'blocker', 'bearing', 'action', 'notification'],
      relatedIds: ['action-track-1042', 'task-wo-2481'],
      entityTags: ['tier-1', 'bearing'],
      detail: { severity: 'High', action: 'Validate inspection result and report closure to Tier 1 tracker.' },
    },
    {
      id: 'notif-shift-coverage',
      category: 'Notifications',
      kind: 'notification',
      title: 'Shift coverage gap — Line 10 packaging',
      subtitle: 'Staffing Alert',
      summary: 'Maria S. is out today and a second-half swap still needs confirmation before 15:00.',
      status: 'Watch',
      tone: '#0ea5e9',
      metric: '1 absence',
      secondaryMetric: 'Triggered 2 hours ago',
      location: 'Shift Schedule',
      plant: 'Line 10',
      updated: '2 hours ago',
      keywords: ['shift', 'coverage', 'absence', 'staffing', 'line 10'],
      relatedIds: [],
      entityTags: ['staffing', 'shift'],
      detail: { severity: 'Medium', action: 'Confirm backup coverage with Andre P. before 15:00.' },
    },
    {
      id: 'notif-spare-parts-low',
      category: 'Notifications',
      kind: 'notification',
      title: 'Low stock alert — Bearing SKU BRG-A3-S12-001',
      subtitle: 'Inventory Alert',
      summary: 'Primary conveyor bearing SKU at or below safety stock. May affect WO-2501 scheduling.',
      status: 'Warning',
      tone: '#FF6E00',
      metric: '2 units left',
      secondaryMetric: 'Triggered 4 hours ago',
      location: 'Tool Crib',
      plant: 'Spare Parts',
      updated: '4 hours ago',
      keywords: ['spare parts', 'low stock', 'bearing', 'inventory', 'notification'],
      relatedIds: ['doc-spare-parts-catalog', 'task-wo-2501'],
      entityTags: ['spare-parts', 'inventory', 'bearing'],
      detail: { severity: 'Medium', action: 'Review replenishment order and confirm lead time.' },
    },
  ];

  const trainings: SmartSearchCatalogItem[] = [
    {
      id: 'training-awareness',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'Bearing Awareness Training',
      subtitle: '12 min • Reliability Academy',
      summary: 'Recognize early bearing wear signs and when to escalate to maintenance vs. line supervisor.',
      status: 'Recommended',
      tone: '#9199D8',
      metric: '12 min',
      secondaryMetric: '92% completion rate',
      location: 'Training Center',
      plant: 'Reliability',
      updated: 'Available now',
      keywords: ['training', 'bearing', 'awareness', 'maintenance', 'escalation', 'inspection'],
      relatedIds: ['doc-inspection-manual', 'notif-training'],
      entityTags: [...bearingTags, 'training'],
      detail: { objective: 'Identify abnormal vibration and take correct next action quickly.' },
    },
    {
      id: 'training-log-issue',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'Log Observation Correctly',
      subtitle: '8 min • Shift Excellence',
      summary: 'Capture vibration, noise, or overheating observations to support faster diagnosis and action closure.',
      status: 'Available',
      tone: '#0ea5e9',
      metric: '8 min',
      secondaryMetric: 'Fast learning',
      location: 'Training Center',
      plant: 'Operations',
      updated: 'Available now',
      keywords: ['training', 'log', 'observation', 'issue', 'shift', 'handoff'],
      relatedIds: ['task-log-observation', 'doc-shift-handoff-template'],
      entityTags: ['training', 'handoff'],
      detail: { objective: 'Improve observation quality handed off to maintenance and supervisors.' },
    },
    {
      id: 'training-loto',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'Lockout/Tagout Fundamentals',
      subtitle: '15 min • Safety Academy',
      summary: 'Required training for maintenance personnel entering service areas for bearing inspection.',
      status: 'Required',
      tone: '#E43B46',
      metric: '15 min',
      secondaryMetric: '4 overdue',
      location: 'Training Center',
      plant: 'Safety',
      updated: 'Available now',
      keywords: ['training', 'loto', 'lockout', 'tagout', 'safety', 'maintenance'],
      relatedIds: ['eso-2026-122'],
      entityTags: ['training', 'safety', 'loto'],
      detail: { objective: 'Ensure safe entry procedures before vibration inspection sequences.' },
    },
    {
      id: 'training-vibration-analysis',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'Vibration Analysis for Reliability Engineers',
      subtitle: '45 min • Advanced Reliability',
      summary: 'Advanced course on interpreting RMS velocity trends, anomaly detection, and predictive maintenance triggers.',
      status: 'Available',
      tone: '#2563EB',
      metric: '45 min',
      secondaryMetric: 'Advanced',
      location: 'Training Center',
      plant: 'Reliability',
      updated: 'Available now',
      keywords: ['training', 'vibration', 'analysis', 'reliability', 'predictive', 'advanced'],
      relatedIds: ['ts-a3-belt-drive', 'doc-bearing-maintenance-guide'],
      entityTags: ['training', 'vibration', 'reliability'],
      detail: { objective: 'Interpret time-series signals and set appropriate maintenance triggers.' },
    },
    {
      id: 'training-tier1-facilitation',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'Tier 1 Meeting Facilitation',
      subtitle: '20 min • Operations Excellence',
      summary: 'How to run effective Tier 1 meetings with blocker resolution and action tracker integration.',
      status: 'Available',
      tone: '#9199D8',
      metric: '20 min',
      secondaryMetric: 'Recommended for leads',
      location: 'Training Center',
      plant: 'Operations',
      updated: 'Available now',
      keywords: ['training', 'tier 1', 'meeting', 'facilitation', 'operations'],
      relatedIds: ['doc-tier1-brief', 'action-track-1042'],
      entityTags: ['training', 'tier-1'],
      detail: { objective: 'Run Tier 1 meetings that drive action closure and accountability.' },
    },
    {
      id: 'training-cil-operator',
      category: 'Trainings',
      kind: 'training',
      thumbnail: '/images/Line1.png',
      title: 'CIL Operator Fundamentals',
      subtitle: '10 min • CIL Academy',
      summary: 'Clean, inspect, lubricate routines for operators including abnormality reporting.',
      status: 'Available',
      tone: '#06b6d4',
      metric: '10 min',
      secondaryMetric: '45% completion',
      location: 'Training Center',
      plant: 'CIL',
      updated: 'Available now',
      keywords: ['training', 'cil', 'operator', 'clean', 'inspect', 'lubricate'],
      relatedIds: ['task-cil-892'],
      entityTags: ['training', 'cil'],
      detail: { objective: 'Execute CIL routines and report abnormalities correctly.' },
    },
  ];

  const actionTracking: SmartSearchCatalogItem[] = [
    {
      id: 'action-track-1042',
      category: 'Action Tracking',
      kind: 'action',
      title: 'Close conveyor bearing verification follow-up',
      subtitle: 'Action Tracking • Tier 1',
      summary: 'Follow-up linked to Station 12 bearing escalation and maintenance verification from first shift.',
      status: 'Open',
      priority: 'High',
      tone: '#E43B46',
      metric: 'Due today',
      secondaryMetric: 'Owner: Reliability',
      location: 'Action Tracker',
      plant: 'Production Line A3',
      updated: 'Due today',
      keywords: ['action tracking', 'bearing', 'reliability', 'tier 1', 'wo-2481'],
      relatedIds: ['task-wo-2481', 'notif-tier-blocker'],
      entityTags: bearingTags,
      detail: {
        actionId: 'ACT-1042',
        owner: 'Reliability',
        assignedTo: 'James Miller',
        dueDate: 'Today 16:30',
        source: 'Tier 1 Meeting',
        description: 'Validate inspection result and confirm no residual vibration risk.',
      },
    },
    {
      id: 'action-track-1058',
      category: 'Action Tracking',
      kind: 'action',
      title: 'Update line restart checklist after inspection',
      subtitle: 'Action Tracking • Operations',
      summary: 'Refresh restart checklist with additional verification step from anomaly review.',
      status: 'In Progress',
      priority: 'Medium',
      tone: '#2563EB',
      metric: '2 steps left',
      secondaryMetric: 'Owner: Operations',
      location: 'Action Tracker',
      plant: 'Production Line A3',
      updated: 'Updated 20 min ago',
      keywords: ['action tracking', 'restart checklist', 'operations', 'line a3'],
      relatedIds: ['shift-note-331'],
      entityTags: ['operations', 'checklist'],
      detail: {
        actionId: 'ACT-1058',
        owner: 'Operations',
        assignedTo: 'Maria Pinna',
        dueDate: 'Tomorrow 08:00',
        source: 'Shift Handover',
        description: 'Ensure restart checklist reflects extra bearing verification.',
      },
    },
    {
      id: 'action-track-1065',
      category: 'Action Tracking',
      kind: 'action',
      title: 'Confirm spare parts replenishment for bearing SKU',
      subtitle: 'Action Tracking • Maintenance',
      summary: 'Verify replenishment order for BRG-A3-S12-001 is placed before replacement WO is scheduled.',
      status: 'Open',
      priority: 'Medium',
      tone: '#0f766e',
      metric: 'Due in 2 days',
      secondaryMetric: 'Owner: Tool Crib',
      location: 'Action Tracker',
      plant: 'Spare Parts',
      updated: 'Created today',
      keywords: ['action tracking', 'spare parts', 'replenishment', 'bearing'],
      relatedIds: ['notif-spare-parts-low', 'task-wo-2501'],
      entityTags: ['spare-parts', 'inventory'],
      detail: {
        actionId: 'ACT-1065',
        owner: 'Tool Crib',
        assignedTo: 'Parts Coordinator',
        dueDate: 'Jul 9, 2026',
        source: 'Inventory Alert',
        description: 'Place replenishment order and confirm lead time with supplier.',
      },
    },
    {
      id: 'action-track-1071',
      category: 'Action Tracking',
      kind: 'action',
      title: 'Assign owner to Tier 1 quality blocker',
      subtitle: 'Action Tracking • Quality',
      summary: 'One quality item in Tier 1 queue lacks clear ownership — needs assignment before next meeting.',
      status: 'Open',
      priority: 'High',
      tone: '#9199D8',
      metric: 'Unassigned',
      secondaryMetric: 'Owner: Tier Coach',
      location: 'Action Tracker',
      plant: 'Tier 1',
      updated: 'Updated 1 hour ago',
      keywords: ['action tracking', 'tier 1', 'quality', 'blocker', 'owner'],
      relatedIds: ['doc-tier1-brief'],
      entityTags: ['tier-1', 'quality'],
      detail: {
        actionId: 'ACT-1071',
        owner: 'Tier Coach',
        dueDate: 'Before next meeting',
        source: 'Tier 1 Meeting',
        description: 'Assign owner and due date to unblock meeting closure.',
      },
    },
  ];

  const esoItems: SmartSearchCatalogItem[] = [
    {
      id: 'eso-2026-118',
      category: 'ESO',
      kind: 'eso',
      title: 'Unsafe walking path near conveyor service aisle',
      subtitle: 'ESO • Condition Report',
      summary: 'Repeated slip risk along conveyor service aisle during lubrication rounds.',
      status: 'Action In Progress',
      priority: 'Medium',
      tone: '#FF6E00',
      metric: 'Condition Report',
      secondaryMetric: 'Reported today',
      location: 'ESO Hub',
      plant: 'Production Line A3',
      updated: 'Created today 09:40',
      keywords: ['eso', 'condition report', 'service aisle', 'safety', 'line a3'],
      relatedIds: ['shift-note-334', 'task-cil-892'],
      entityTags: ['safety', 'housekeeping'],
      detail: {
        esoId: 'ESO-2026-118',
        esoType: 'Condition Report',
        severity: 'Medium',
        reportedBy: 'John Joshua',
        description: 'Fluid residue near service aisle created repeat slip hazard during lubrication route.',
      },
    },
    {
      id: 'eso-2026-122',
      category: 'ESO',
      kind: 'eso',
      title: 'Near miss during bearing inspection setup',
      subtitle: 'ESO • Near Miss',
      summary: 'Barricade not fully in place before vibration inspection sequence started.',
      status: 'Review',
      priority: 'High',
      tone: '#E43B46',
      metric: 'Near Miss',
      secondaryMetric: 'Awaiting review',
      location: 'ESO Hub',
      plant: 'Reliability / Line A3',
      updated: 'Updated 35 min ago',
      keywords: ['eso', 'near miss', 'inspection', 'barricade', 'bearing'],
      relatedIds: ['task-wo-2481', 'training-loto'],
      entityTags: ['safety', 'bearing', 'inspection'],
      detail: {
        esoId: 'ESO-2026-122',
        esoType: 'Near Miss',
        severity: 'High',
        reportedBy: 'BLU.AI',
        description: 'Pre-inspection barricade sequence started but not fully verified.',
      },
    },
    {
      id: 'eso-2026-125',
      category: 'ESO',
      kind: 'eso',
      title: 'Positive observation — improved housekeeping near Station 12',
      subtitle: 'ESO • Positive Observation',
      summary: 'Operator noted improved housekeeping standards after CIL task completion.',
      status: 'Closed',
      priority: 'Low',
      tone: '#00AF95',
      metric: 'Positive',
      secondaryMetric: 'Closed today',
      location: 'ESO Hub',
      plant: 'Line A3',
      updated: 'Closed today',
      keywords: ['eso', 'positive', 'housekeeping', 'station 12'],
      relatedIds: ['task-cil-892'],
      entityTags: ['safety', 'positive'],
      detail: {
        esoId: 'ESO-2026-125',
        esoType: 'Positive Observation',
        severity: 'Low',
        reportedBy: 'Maria Pinna',
        description: 'Housekeeping improvement noted after CIL-892 completion.',
      },
    },
  ];

  const shiftNotes: SmartSearchCatalogItem[] = [
    {
      id: 'shift-note-331',
      category: 'Shift Notes',
      kind: 'shiftNote',
      title: 'Bearing watch condition handed to second shift',
      subtitle: 'Shift Notes • Handover',
      summary: 'First shift documented bearing watch status, linked WO-2481, and need to confirm trend stabilization after restart.',
      status: 'Logged',
      tone: '#2563EB',
      metric: 'Day Shift',
      secondaryMetric: 'Created by Maria Pinna',
      location: 'Shift Logbook',
      plant: 'Production Line A3',
      updated: 'Created today 14:12',
      keywords: ['shift notes', 'handover', 'bearing', 'wo-2481', 'line a3'],
      relatedIds: ['task-wo-2481', 'ts-a3-belt-drive'],
      entityTags: bearingTags,
      detail: {
        noteId: 'SN-331',
        shift: 'Day Shift',
        createdBy: 'Maria Pinna',
        relatedIssue: 'WO-2481',
        description: 'Second shift must verify vibration remains below warning band after restart.',
      },
    },
    {
      id: 'shift-note-334',
      category: 'Shift Notes',
      kind: 'shiftNote',
      title: 'Lubrication delay noted during night shift prep',
      subtitle: 'Shift Notes • Prep Note',
      summary: 'Delayed lubrication round and related housekeeping follow-up before startup.',
      status: 'Open',
      tone: '#0EA5E9',
      metric: 'Night Shift',
      secondaryMetric: 'Created by Olivia Martin',
      location: 'Shift Logbook',
      plant: 'Reliability / Line A3',
      updated: 'Created today 15:05',
      keywords: ['shift notes', 'lubrication', 'night shift', 'housekeeping'],
      relatedIds: ['eso-2026-118', 'task-wo-2476'],
      entityTags: ['lubrication', 'handoff'],
      detail: {
        noteId: 'SN-334',
        shift: 'Night Shift',
        createdBy: 'Olivia Martin',
        relatedIssue: 'ESO-2026-118',
        description: 'Check housekeeping and lubrication timing before startup checklist sign-off.',
      },
    },
    {
      id: 'shift-note-338',
      category: 'Shift Notes',
      kind: 'shiftNote',
      title: 'Micro-stop pattern on Line A3 — third occurrence',
      subtitle: 'Shift Notes • Exception',
      summary: 'Third micro-stop at Station 12 in current shift window. Pattern suggests bearing-related instability.',
      status: 'Active',
      tone: '#FF6E00',
      metric: 'Day Shift',
      secondaryMetric: 'Created 20 min ago',
      location: 'Shift Logbook',
      plant: 'Production Line A3',
      updated: 'Created 20 min ago',
      keywords: ['shift notes', 'micro-stop', 'line a3', 'station 12', 'exception'],
      relatedIds: ['asset-station-12', 'ts-a3-oee'],
      entityTags: [...bearingTags, 'micro-stop'],
      detail: {
        noteId: 'SN-338',
        shift: 'Day Shift',
        createdBy: 'James Miller',
        relatedIssue: 'Station 12 bearing',
        description: 'Pattern of micro-stops correlates with vibration trend — escalate if fourth occurrence.',
      },
    },
    {
      id: 'shift-note-340',
      category: 'Shift Notes',
      kind: 'shiftNote',
      title: 'Control Tower priority update — Line A3 focus',
      subtitle: 'Shift Notes • Control Tower',
      summary: 'Control Tower elevated Line A3 bearing escalation to top plant priority for current shift.',
      status: 'Logged',
      tone: '#9199D8',
      metric: 'Day Shift',
      secondaryMetric: 'Created 30 min ago',
      location: 'Control Tower',
      plant: 'Plant-wide',
      updated: 'Created 30 min ago',
      keywords: ['shift notes', 'control tower', 'priority', 'line a3', 'bearing'],
      relatedIds: ['notif-line-alert', 'task-wo-2481'],
      entityTags: ['control-tower', 'priority'],
      detail: {
        noteId: 'SN-340',
        shift: 'Day Shift',
        createdBy: 'Control Team',
        description: 'Line A3 bearing verification is top plant priority until WO-2481 closes.',
      },
    },
  ];

  return {
    Documents: documents,
    'Tasks & Work Orders': tasks,
    Notifications: notifications,
    Trainings: trainings,
    Assets: assets,
    'Time Series': timeSeries,
    '3D': threeD,
    'Action Tracking': actionTracking,
    ESO: esoItems,
    'Shift Notes': shiftNotes,
  };
}

export function getGlobalCatalogFlat(currentUserName: string): SmartSearchCatalogItem[] {
  return Object.values(getGlobalSearchCatalog(currentUserName)).flat();
}

export function getGlobalCatalogStats(currentUserName: string) {
  const catalog = getGlobalSearchCatalog(currentUserName);
  const total = Object.values(catalog).reduce((acc, items) => acc + items.length, 0);
  const sources = Object.keys(catalog).length;
  return { total, sources };
}
