import type {
  ActionPayload,
  AiActionCard,
  AiInsight,
  AiPriorityBriefing,
  ConversationEntry,
  DemandRiskDetail,
  DemandRiskRow,
  KpiCardData,
  LineImpactRow,
  RiskClusterItem,
  RiskDetailData,
  WoDetailData,
  WoQueueItem,
} from './types';

export const aiPriorityBriefing: AiPriorityBriefing = {
  headline: '780K units are at risk across 6 work orders. Family A on Line 10 is the highest demand exposure due to a hard material shortage.',
  summary:
    'Resolving WO-350021 protects 500K units. AI recommends three actions before 12:00: expedite RM-4421, request QA release update for WO-350087, and reserve a sterilization slot for WO-350145.',
  keySignals: [
    '3 governed actions require planner confirmation.',
    '620K units are still recoverable today if top actions are accepted.',
    '2 recommendations should be rechecked because source data is older than the freshness threshold.',
  ],
  quickActions: [
    {id: 'review-top-actions', label: 'Review Top Actions'},
    {id: 'open-demand-risk', label: 'Open Demand Risk'},
    {id: 'view-root-cause-clusters', label: 'View Root Cause Clusters'},
    {id: 'refresh-readiness', label: 'Refresh Readiness'},
    {id: 'ask-ai', label: 'Ask AI'},
  ],
  refreshLabel: 'Last AI refresh 09:12',
};

export const workOrderKpis: KpiCardData[] = [
  {key: 'demand-at-risk', label: 'Demand at Risk', value: '780K units', helperText: 'Units at risk of delay', tone: 'danger', icon: 'inventory'},
  {key: 'recoverable-today', label: 'Recoverable Today', value: '620K units', helperText: 'Can be protected if AI actions complete', tone: 'success', icon: 'shield'},
  {key: 'critical-ai-actions', label: 'Critical AI Actions', value: 3, helperText: 'Require immediate confirmation or assignment', tone: 'warning', icon: 'bolt'},
  {key: 'blocked-wos', label: 'Blocked WOs', value: 5, helperText: 'At least one readiness check blocked', tone: 'danger', icon: 'block'},
  {key: 'due-48h', label: 'Due in 48h', value: 11, helperText: 'Scheduled start within 2 days', tone: 'info', icon: 'schedule'},
  {key: 'unassigned-blockers', label: 'Unassigned Blockers', value: 4, helperText: 'No owner assigned', tone: 'neutral', icon: 'owner-off'},
];

export const operationalRiskKpis: KpiCardData[] = [
  {key: 'demand-at-risk', label: 'Demand at Risk', value: '780K units', helperText: 'Demand exposed across root causes', tone: 'danger', icon: 'inventory'},
  {key: 'recoverable-today', label: 'Recoverable Today', value: '620K units', helperText: 'Demand still recoverable today', tone: 'success', icon: 'shield'},
  {key: 'root-cause-clusters', label: 'Root Cause Clusters', value: 4, helperText: 'Operational blocker groups monitored by AI', tone: 'info', icon: 'cluster'},
  {key: 'line-hours-at-risk', label: 'Line Hours at Risk', value: '6.5h', helperText: 'Potential execution loss', tone: 'warning', icon: 'factory'},
  {key: 'critical-ai-actions', label: 'Critical AI Actions', value: 3, helperText: 'Require immediate confirmation', tone: 'warning', icon: 'bolt'},
  {key: 'override-active', label: 'Override Active', value: 6, helperText: 'Governed exceptions in effect', tone: 'neutral', icon: 'override'},
];

export const aiActionCards: AiActionCard[] = [
  {
    id: 'action-1',
    rank: 1,
    priority: 'Critical',
    title: 'Expedite RM-4421 or evaluate replacement WO',
    relatedType: 'wo',
    relatedId: 'WO-350021',
    relatedLabel: 'WO-350021',
    demandProtected: '500K units',
    deadline: 'Today 12:00',
    owner: 'Material Controller',
    confidence: 'Medium',
    why: 'Hard material blocker, start within 6h, no confirmed recovery.',
    primaryAction: 'Open Recovery Plan',
    secondaryActions: ['Assign Owner', 'Suggest Replacement', 'Escalate'],
    governed: true,
  },
  {
    id: 'action-2',
    rank: 2,
    priority: 'High',
    title: 'Request QA release update',
    relatedType: 'wo',
    relatedId: 'WO-350087',
    relatedLabel: 'WO-350087',
    demandProtected: '120K units',
    deadline: 'Today 15:00',
    owner: 'Quality Eng.',
    confidence: 'Medium',
    why: 'Quality release pending with no delegate confirmed.',
    primaryAction: 'Notify QA',
    secondaryActions: ['Open Detail', 'Re-run Readiness'],
    governed: true,
  },
  {
    id: 'action-3',
    rank: 3,
    priority: 'High',
    title: 'Reserve sterilization slot',
    relatedType: 'wo',
    relatedId: 'WO-350145',
    relatedLabel: 'WO-350145',
    demandProtected: '3 batches',
    deadline: 'Tomorrow 09:00',
    owner: 'Sterilization',
    confidence: 'High',
    why: 'Single qualified resource with backlog growing into dwell window.',
    primaryAction: 'Reserve Slot',
    secondaryActions: ['Open Detail'],
    governed: true,
  },
  {
    id: 'action-4',
    rank: 4,
    priority: 'High',
    title: 'Reassign shift coverage or delay start',
    relatedType: 'wo',
    relatedId: 'WO-350200',
    relatedLabel: 'WO-350200',
    demandProtected: '80K units',
    deadline: 'Tomorrow 13:00',
    owner: 'Production Manager',
    confidence: 'Medium',
    why: 'Certified labor gap confirmed and no owner assigned.',
    primaryAction: 'Assign Shift Coverage',
    secondaryActions: ['Escalate', 'Open Detail'],
    governed: true,
  },
];

export const workOrderQueueItems: WoQueueItem[] = [
  {
    id: 'WO-350021',
    rank: 1,
    priority: 'Critical',
    woId: 'WO-350021',
    product: 'Family A / SKU-1001',
    batch: 'B-78451',
    lineMachine: 'Line 10 / M-04',
    scheduledStart: '26-May 14:00',
    timeToStart: '6h 20m',
    readiness: 'Blocked',
    mainBlocker: 'Material shortage',
    whyRanked: 'Hard blocker + 500K units at risk + starts today.',
    demandAtRisk: '500K units',
    operationalImpact: '3.5h line loss',
    owner: 'Material Controller',
    actionStatus: 'New',
    actionDue: 'Today 12:00',
    aiRecommendation: 'Expedite RM-4421 or evaluate replacement WO.',
    aiConfidence: 'Medium',
    nextAction: 'Open Recovery Plan',
    freshness: 'Stale',
    overrideActive: false,
    recoverableToday: true,
    preparedActionId: 'prep-wo-350021',
    recommendationId: 'AI-78421',
  },
  {
    id: 'WO-350087',
    rank: 2,
    priority: 'High',
    woId: 'WO-350087',
    product: 'Family B / SKU-2002',
    batch: 'B-78452',
    lineMachine: 'Line 07 / M-02',
    scheduledStart: '27-May 09:00',
    timeToStart: '18h',
    readiness: 'Warning',
    mainBlocker: 'Quality release pending',
    whyRanked: 'QA blocker + 120K units exposed + frozen window risk.',
    demandAtRisk: '120K units',
    operationalImpact: '1.0d schedule slip',
    owner: 'Quality Eng.',
    actionStatus: 'In Review',
    actionDue: 'Today 15:00',
    aiRecommendation: 'Request QA release update and confirm delegate.',
    aiConfidence: 'Medium',
    nextAction: 'Notify QA',
    freshness: 'Fresh',
    overrideActive: true,
    recoverableToday: true,
    preparedActionId: 'prep-wo-350087',
    recommendationId: 'AI-78422',
  },
  {
    id: 'WO-350145',
    rank: 3,
    priority: 'High',
    woId: 'WO-350145',
    product: 'Family C / SKU-3003',
    batch: 'B-78453',
    lineMachine: 'Line 05 / Ster-02',
    scheduledStart: '27-May 18:00',
    timeToStart: '1d 3h',
    readiness: 'Warning',
    mainBlocker: 'Sterilization slot',
    whyRanked: 'No slot reserved + 3 batches at risk + high confidence recovery.',
    demandAtRisk: '3 batches',
    operationalImpact: '2.0h sterilization delay',
    owner: 'Sterilization',
    actionStatus: 'New',
    actionDue: 'Tomorrow 09:00',
    aiRecommendation: 'Reserve sterilization slot before dwell risk window closes.',
    aiConfidence: 'High',
    nextAction: 'Reserve Slot',
    freshness: 'Fresh',
    overrideActive: false,
    recoverableToday: true,
    preparedActionId: 'prep-wo-350145',
    recommendationId: 'AI-78423',
  },
  {
    id: 'WO-350200',
    rank: 4,
    priority: 'High',
    woId: 'WO-350200',
    product: 'Family D / SKU-4004',
    batch: 'B-78460',
    lineMachine: 'Line 03 / M-01',
    scheduledStart: '28-May 05:00',
    timeToStart: '1d 20h',
    readiness: 'Warning',
    mainBlocker: 'Certified labor unavailable',
    whyRanked: 'No certified coverage + 80K units at risk + owner missing.',
    demandAtRisk: '80K units',
    operationalImpact: '2.0h start loss',
    owner: 'Production Manager',
    actionStatus: 'Waiting Response',
    actionDue: 'Tomorrow 13:00',
    aiRecommendation: 'Reassign shift coverage or delay start.',
    aiConfidence: 'Medium',
    nextAction: 'Assign Shift Coverage',
    freshness: 'Watch',
    overrideActive: false,
    recoverableToday: false,
    preparedActionId: 'prep-wo-350200',
    recommendationId: 'AI-78424',
  },
  {
    id: 'WO-350311',
    rank: 5,
    priority: 'Medium',
    woId: 'WO-350311',
    product: 'Family A / SKU-1002',
    batch: 'B-78470',
    lineMachine: 'Line 10 / M-04',
    scheduledStart: '29-May 08:00',
    timeToStart: '2d 0h',
    readiness: 'Warning',
    mainBlocker: 'Capacity conflict',
    whyRanked: 'Depends on WO-350021 recovery and same constrained line.',
    demandAtRisk: '60K units',
    operationalImpact: '1.0d sequence shift',
    owner: 'Planner',
    actionStatus: 'Assigned',
    actionDue: 'Tomorrow 10:00',
    aiRecommendation: 'Prepare resequencing if Line 10 remains constrained.',
    aiConfidence: 'High',
    nextAction: 'Suggest Replacement',
    freshness: 'Fresh',
    overrideActive: false,
    recoverableToday: false,
    preparedActionId: 'prep-wo-350311',
    recommendationId: 'AI-78425',
  },
  {
    id: 'WO-350422',
    rank: 6,
    priority: 'Medium',
    woId: 'WO-350422',
    product: 'Family E / SKU-5005',
    batch: 'B-78480',
    lineMachine: 'Line 12 / M-09',
    scheduledStart: '30-May 10:00',
    timeToStart: '3d 2h',
    readiness: 'Ready',
    mainBlocker: 'No hard blocker',
    whyRanked: 'Candidate replacement WO if Family A shortage remains unresolved.',
    demandAtRisk: '40K units',
    operationalImpact: 'Ready capacity buffer',
    owner: 'Planner',
    actionStatus: 'Resolved Pending Recheck',
    actionDue: '29-May 08:00',
    aiRecommendation: 'Keep ready as replacement candidate for Line 10 recovery plan.',
    aiConfidence: 'High',
    nextAction: 'Open Detail',
    freshness: 'Fresh',
    overrideActive: false,
    recoverableToday: true,
    preparedActionId: 'prep-wo-350422',
    recommendationId: 'AI-78426',
  },
  {
    id: 'WO-350510',
    rank: 7,
    priority: 'Medium',
    woId: 'WO-350510',
    product: 'Family F / SKU-6100',
    batch: 'B-78501',
    lineMachine: 'Line 08 / M-06',
    scheduledStart: '30-May 16:00',
    timeToStart: '3d 8h',
    readiness: 'Blocked',
    mainBlocker: 'Documentation incomplete',
    whyRanked: 'Soft blocker, lower demand exposure, still due within 72h.',
    demandAtRisk: '25K units',
    operationalImpact: '0.5d release slip',
    owner: 'Packaging Lead',
    actionStatus: 'Assigned',
    actionDue: 'Tomorrow 16:00',
    aiRecommendation: 'Request documentation completion and re-run readiness.',
    aiConfidence: 'Low',
    nextAction: 'Re-run Readiness',
    freshness: 'Watch',
    overrideActive: true,
    recoverableToday: false,
    preparedActionId: 'prep-wo-350510',
    recommendationId: 'AI-78427',
  },
  {
    id: 'WO-350612',
    rank: 8,
    priority: 'Low',
    woId: 'WO-350612',
    product: 'Family G / SKU-7201',
    batch: 'B-78515',
    lineMachine: 'Line 11 / M-03',
    scheduledStart: '31-May 08:00',
    timeToStart: '4d 0h',
    readiness: 'Ready',
    mainBlocker: 'No hard blocker',
    whyRanked: 'Monitor only. Not part of near-term demand protection actions.',
    demandAtRisk: '15K units',
    operationalImpact: 'No immediate impact',
    owner: 'Planner',
    actionStatus: 'Completed',
    actionDue: '31-May 08:00',
    aiRecommendation: 'No action required; keep in watchlist.',
    aiConfidence: 'High',
    nextAction: 'Open Detail',
    freshness: 'Fresh',
    overrideActive: false,
    recoverableToday: false,
    preparedActionId: 'prep-wo-350612',
    recommendationId: 'AI-78428',
  },
];

export const woDetailMap: Record<string, WoDetailData> = {
  'WO-350021': {
    woId: 'WO-350021',
    product: 'Family A / SKU-1001',
    batch: 'B-78451',
    plannedQty: '500,000 units',
    lineMachine: 'Line 10 / Machine M-04',
    scheduledStart: '26-May-2026 14:00',
    scheduledEnd: '27-May-2026 23:30',
    timeToStart: '6h 20m',
    actionStatus: 'New',
    priorityReason: 'Ranked #1 because it has a hard material blocker, protects 500K units of Family A demand, starts within 24 hours, and no recovery action is confirmed.',
    whyBlocked: 'Required RM-4421 is short by 500,000 units and no supplier ETA is confirmed in the latest sync.',
    demandImpact: '500K units at risk. Resolving this WO protects the largest near-term customer commitment on the page.',
    operationalImpact: 'Line 10 loses 3.5h and pushes downstream Family A sequence if unresolved.',
    noActionImpact: 'If no action is confirmed by 12:00, Family A demand slips into the next shipping window and Line 10 remains constrained.',
    suggestedReplacement: 'WO-350422 is the preferred contingency WO if Family A cannot start today.',
    dataFreshness: 'SAP inventory 35 min ago. Supplier ETA missing. Warehouse staging 22 min ago.',
    readinessChecks: [
      {label: 'Material', status: 'Blocked', detail: 'RM-4421 shortage of 500,000 units'},
      {label: 'Warehouse', status: 'Warning', detail: 'Staging incomplete'},
      {label: 'Quality', status: 'Ready', detail: 'Release complete'},
      {label: 'Labor', status: 'Ready', detail: 'Crew confirmed'},
      {label: 'Machine', status: 'Ready', detail: 'Line available'},
      {label: 'Schedule', status: 'Ready', detail: 'Slot still protected'},
    ],
    evidence: [
      {label: 'Required RM-4421', value: '1,200,000 units'},
      {label: 'Available', value: '700,000 units'},
      {label: 'Shortage', value: '500,000 units'},
      {label: 'Supplier ETA', value: 'Missing'},
    ],
    preparedActions: [
      {id: 'prep-wo-350021', label: 'Assign blocker to Material Controller', actionType: 'Assign blocker', governed: true, owner: 'Material Controller', reasonCode: 'MAT-SHORT', confirmationLabel: 'Confirm Assignment', comment: 'Please confirm expedite feasibility for RM-4421. If no ETA is available by 12:00, evaluate replacement WO.'},
      {id: 'prep-wo-350021-2', label: 'Escalate to procurement', actionType: 'Escalate', governed: true, owner: 'Procurement Lead', reasonCode: 'SUP-EXP', confirmationLabel: 'Confirm Escalation', comment: 'Open supplier escalation and request same-day ETA update.'},
    ],
    eventTimeline: [
      '09:05 AI refreshed ranking after material sync.',
      '08:44 Warehouse flagged staging incomplete for Family A kit.',
      '08:18 Supplier ETA still missing in procurement portal.',
    ],
    suggestedQuestions: ['Why is this ranked #1?', 'What demand is at risk?', 'What happens if unresolved?', 'What replacement WO is available?'],
  },
  'WO-350087': {
    woId: 'WO-350087',
    product: 'Family B / SKU-2002',
    batch: 'B-78452',
    plannedQty: '120,000 units',
    lineMachine: 'Line 07 / Machine M-02',
    scheduledStart: '27-May-2026 09:00',
    scheduledEnd: '28-May-2026 21:00',
    timeToStart: '18h',
    actionStatus: 'In Review',
    priorityReason: 'Ranked high because QA release is the only blocker, the start is within 24 hours, and the frozen window leaves little room for delay.',
    whyBlocked: 'Batch release is pending QA director sign-off and no delegate has been confirmed.',
    demandImpact: '120K units at risk. Delay pushes Family B into frozen period and raises expedited freight risk.',
    operationalImpact: 'Line 07 sequence will compress into tomorrow afternoon if release is late.',
    noActionImpact: 'If no response arrives by 15:00, planner loses the preferred execution window and may need to resequence.',
    suggestedReplacement: 'No direct replacement WO selected. AI recommends protecting QA release first.',
    dataFreshness: 'QMS 18 min ago. LIMS 11 min ago. Shift plan 44 min ago.',
    readinessChecks: [
      {label: 'Material', status: 'Ready'},
      {label: 'Quality', status: 'Blocked', detail: 'Release pending'},
      {label: 'Labor', status: 'Ready'},
      {label: 'Machine', status: 'Ready'},
      {label: 'Schedule', status: 'Warning', detail: 'Frozen-period exposure'},
    ],
    evidence: [
      {label: 'Release owner', value: 'QA Director'},
      {label: 'Delegate confirmed', value: 'No'},
      {label: 'Latest lab result', value: '08:21 complete'},
    ],
    preparedActions: [
      {id: 'prep-wo-350087', label: 'Notify QA release owner', actionType: 'Notify quality', governed: true, owner: 'Quality Eng.', reasonCode: 'QA-REL', confirmationLabel: 'Confirm Notification', comment: 'Please confirm release update for WO-350087 and identify a delegate if the director is unavailable.'},
    ],
    eventTimeline: ['08:38 Lab results posted.', '08:12 AI raised recommendation to High.', '07:55 QA noted director unavailable until 15:00.'],
    suggestedQuestions: ['Why prioritized?', 'What is blocking release?', 'What action protects demand?'],
  },
  'WO-350145': {
    woId: 'WO-350145',
    product: 'Family C / SKU-3003',
    batch: 'B-78453',
    plannedQty: '3 batches',
    lineMachine: 'Line 05 / Ster-02',
    scheduledStart: '27-May-2026 18:00',
    scheduledEnd: '28-May-2026 23:00',
    timeToStart: '1d 3h',
    actionStatus: 'New',
    priorityReason: 'Ranked high because Sterilizer 2 is a single qualified resource and no slot is reserved inside the dwell risk window.',
    whyBlocked: 'Sterilization capacity is available only if the slot is reserved before tomorrow 09:00.',
    demandImpact: '3 batches at risk. Missing the slot extends release by 5 to 7 days.',
    operationalImpact: 'Backlog grows on Ster-02 and delays downstream shipment staging.',
    noActionImpact: 'If no slot is reserved, AI expects the release window to be missed for all three batches.',
    suggestedReplacement: 'No qualified alternative sterilizer available.',
    dataFreshness: 'Ster schedule 14 min ago. Maintenance status 21 min ago.',
    readinessChecks: [
      {label: 'Material', status: 'Ready'},
      {label: 'Quality', status: 'Ready'},
      {label: 'Sterilization', status: 'Blocked', detail: 'Slot not reserved'},
      {label: 'Machine', status: 'Ready'},
      {label: 'Schedule', status: 'Warning'},
    ],
    evidence: [
      {label: 'Qualified sterilizer', value: 'Ster-02 only'},
      {label: 'Available slot', value: '27-May 22:00 tentative'},
      {label: 'Dwell risk window', value: 'Closes tomorrow 09:00'},
    ],
    preparedActions: [
      {id: 'prep-wo-350145', label: 'Reserve sterilization slot', actionType: 'Reserve slot', governed: true, owner: 'Sterilization', reasonCode: 'STER-SLOT', confirmationLabel: 'Confirm Reservation Request', comment: 'Reserve the next feasible Ster-02 slot for Family C priority batches before dwell risk increases.'},
    ],
    eventTimeline: ['08:52 Ster-02 backlog increased by one batch.', '08:10 AI confirmed Family C remains recoverable today.'],
    suggestedQuestions: ['Why is sterilization the blocker?', 'What is the deadline?', 'What happens if unresolved?'],
  },
  'WO-350200': {
    woId: 'WO-350200',
    product: 'Family D / SKU-4004',
    batch: 'B-78460',
    plannedQty: '80,000 units',
    lineMachine: 'Line 03 / Machine M-01',
    scheduledStart: '28-May-2026 05:00',
    scheduledEnd: '28-May-2026 22:00',
    timeToStart: '1d 20h',
    actionStatus: 'Waiting Response',
    priorityReason: 'Ranked high because no certified labor owner is assigned and the line cannot start safely without coverage.',
    whyBlocked: 'Three certified operators are unavailable and shift coverage is not confirmed.',
    demandImpact: '80K units at risk if coverage is not assigned by tomorrow.',
    operationalImpact: 'Line 03 may lose the planned start and create 2 hours of idle time.',
    noActionImpact: 'Without a confirmed assignment, AI expects a one-day slip or a manual hold decision.',
    suggestedReplacement: 'No replacement WO recommended; recover via shift coverage.',
    dataFreshness: 'HR 1h ago. Shift planning 48 min ago.',
    readinessChecks: [
      {label: 'Labor', status: 'Blocked', detail: 'Certified operator shortage'},
      {label: 'Material', status: 'Ready'},
      {label: 'Machine', status: 'Ready'},
      {label: 'Quality', status: 'Ready'},
    ],
    evidence: [
      {label: 'Minimum crew', value: '4 certified operators'},
      {label: 'Confirmed crew', value: '2 operators'},
      {label: 'Backup line', value: 'Line 12 cross-trained crew available'},
    ],
    preparedActions: [
      {id: 'prep-wo-350200', label: 'Assign shift coverage owner', actionType: 'Assign owner', governed: true, owner: 'Production Manager', reasonCode: 'LAB-GAP', confirmationLabel: 'Confirm Assignment', comment: 'Assign a production owner to secure certified shift coverage or confirm delay by tomorrow 13:00.'},
    ],
    eventTimeline: ['08:03 HR confirmed additional medical leave.', '07:41 AI changed action status to Waiting Response.'],
    suggestedQuestions: ['Who owns this action?', 'Can this be recovered today?', 'What if no labor is assigned?'],
  },
  'WO-350311': {
    woId: 'WO-350311',
    product: 'Family A / SKU-1002',
    batch: 'B-78470',
    plannedQty: '60,000 units',
    lineMachine: 'Line 10 / Machine M-04',
    scheduledStart: '29-May-2026 08:00',
    scheduledEnd: '29-May-2026 20:00',
    timeToStart: '2d 0h',
    actionStatus: 'Assigned',
    priorityReason: 'Ranked behind WO-350021 because it is downstream of the same root-cause cluster and can become a contingency decision.',
    whyBlocked: 'Capacity conflict depends on Family A recovery and Line 10 load.',
    demandImpact: '60K units at risk if Line 10 remains overloaded.',
    operationalImpact: 'Potential resequence across the next two Family A jobs.',
    noActionImpact: 'If no contingency is prepared, planners will make a late rescheduling decision with lower recovery options.',
    suggestedReplacement: 'AI suggests evaluating Line 12 contingency if Line 10 remains constrained.',
    dataFreshness: 'Capacity 20 min ago.',
    readinessChecks: [
      {label: 'Material', status: 'Ready'},
      {label: 'Schedule', status: 'Warning', detail: 'Dependent on Line 10 recovery'},
      {label: 'Machine', status: 'Ready'},
    ],
    evidence: [
      {label: 'Dependency', value: 'Shares line with WO-350021'},
      {label: 'Alternative line', value: 'Line 12 possible with setup penalty'},
    ],
    preparedActions: [
      {id: 'prep-wo-350311', label: 'Suggest replacement plan', actionType: 'Suggest replacement', governed: false, owner: 'Planner', reasonCode: 'SEQ-CONT', confirmationLabel: 'Log Suggestion', comment: 'Prepare contingency to move the Family A follow-on job if Line 10 remains constrained after noon.'},
    ],
    eventTimeline: ['08:46 AI linked this WO to the material shortage cluster.'],
    suggestedQuestions: ['Why ranked below WO-350021?', 'What contingency exists?'],
  },
};

export const riskClusterItems: RiskClusterItem[] = [
  {
    id: 'cluster-material-shortage',
    rank: 1,
    severity: 'Critical',
    clusterName: 'Material Shortage',
    affectedWos: 5,
    demandAtRisk: '620K units',
    linesImpacted: 'Line 10, Line 03',
    earliestStart: 'Today 14:00',
    rootCause: 'RM-4421 shortage and no confirmed supplier ETA',
    aiRecommendation: 'Expedite RM-4421 or resequence ready WOs.',
    owner: 'Material Controller',
    confidence: 'Medium',
    actionStatus: 'New',
    primaryAction: 'Open Material Recovery',
    freshness: 'Stale',
    preparedActionId: 'prep-cluster-material',
    recommendationId: 'AI-79001',
  },
  {
    id: 'cluster-quality-release',
    rank: 2,
    severity: 'High',
    clusterName: 'Quality Release Pending',
    affectedWos: 3,
    demandAtRisk: '210K units',
    linesImpacted: 'Line 07, Line 05',
    earliestStart: 'Today 18:00',
    rootCause: 'Batch release approvals pending near start window',
    aiRecommendation: 'Request QA release updates and identify delegate sign-off.',
    owner: 'Quality Eng.',
    confidence: 'Medium',
    actionStatus: 'In Review',
    primaryAction: 'Notify Quality',
    freshness: 'Fresh',
    preparedActionId: 'prep-cluster-quality',
    recommendationId: 'AI-79002',
  },
  {
    id: 'cluster-sterilization',
    rank: 3,
    severity: 'High',
    clusterName: 'Sterilization Risk',
    affectedWos: 2,
    demandAtRisk: '4 batches',
    linesImpacted: 'Ster-02 / Line 05',
    earliestStart: 'Tomorrow 09:00',
    rootCause: 'Slot not reserved before dwell risk window',
    aiRecommendation: 'Reserve sterilization slot for priority batches.',
    owner: 'Sterilization',
    confidence: 'High',
    actionStatus: 'New',
    primaryAction: 'Reserve Slot',
    freshness: 'Fresh',
    preparedActionId: 'prep-cluster-ster',
    recommendationId: 'AI-79003',
  },
  {
    id: 'cluster-labor-coverage',
    rank: 4,
    severity: 'High',
    clusterName: 'Labor Coverage',
    affectedWos: 2,
    demandAtRisk: '80K units',
    linesImpacted: 'Line 03',
    earliestStart: 'Tomorrow 13:00',
    rootCause: 'Missing certified operator coverage',
    aiRecommendation: 'Reassign shift coverage or delay start.',
    owner: 'Production Manager',
    confidence: 'Medium',
    actionStatus: 'Waiting Response',
    primaryAction: 'Assign Shift Coverage',
    freshness: 'Watch',
    preparedActionId: 'prep-cluster-labor',
    recommendationId: 'AI-79004',
  },
];

export const riskDetailMap: Record<string, RiskDetailData> = {
  'cluster-material-shortage': {
    clusterName: 'Material Shortage',
    severity: 'Critical',
    owner: 'Material Controller',
    actionStatus: 'New',
    demandAtRisk: '620K units',
    recoverableQty: '500K units',
    linesImpacted: 'Line 10, Line 03',
    earliestRisk: 'Today 14:00',
    rootCauseSummary: 'RM-4421 is short and no supplier ETA is confirmed. This cluster drives the top-ranked WO and two follow-on jobs.',
    aiRecoveryPlan: 'Expedite RM-4421, then resequence ready Line 10 work orders if ETA is not confirmed by 12:00.',
    noActionImpact: 'Family A slips immediately, Line 10 remains constrained, and 620K units stay exposed.',
    suggestedOwnerReason: 'Material Controller owns the supplier and inventory recovery path.',
    affectedWos: ['WO-350021', 'WO-350311', 'WO-350422', 'WO-350510', 'WO-350712'],
    relatedRisks: [{id: 'cluster-quality-release', title: 'Quality Release Pending', severity: 'High'}],
    preparedActions: [
      {id: 'prep-cluster-material', label: 'Assign material recovery owner', actionType: 'Assign owner', governed: true, owner: 'Material Controller', reasonCode: 'MAT-SHORT', confirmationLabel: 'Confirm Assignment', comment: 'Assign material recovery owner and request same-day ETA update for RM-4421.'},
      {id: 'prep-cluster-material-2', label: 'Escalate supplier team', actionType: 'Escalate', governed: true, owner: 'Supplier Team', reasonCode: 'SUP-EXP', confirmationLabel: 'Confirm Escalation', comment: 'Escalate shortage to supplier team and trigger replacement supply review.'},
    ],
    suggestedQuestions: ['What demand is protected if this clears?', 'Which WOs are affected?', 'What is the next best recovery plan?'],
    eventTimeline: ['09:05 AI refreshed cluster ranking.', '08:18 Supplier ETA still missing.', '07:52 inventory shortage widened after latest allocation.'],
  },
  'cluster-quality-release': {
    clusterName: 'Quality Release Pending',
    severity: 'High',
    owner: 'Quality Eng.',
    actionStatus: 'In Review',
    demandAtRisk: '210K units',
    recoverableQty: '210K units',
    linesImpacted: 'Line 07, Line 05',
    earliestRisk: 'Today 18:00',
    rootCauseSummary: 'Batches are ready to build but quality release sign-off remains pending for near-term starts.',
    aiRecoveryPlan: 'Request QA release update, confirm delegate sign-off authority, and re-run readiness once approvals post.',
    noActionImpact: 'The Family B shipping window narrows and planners lose same-day recovery options.',
    suggestedOwnerReason: 'Quality engineering controls release coordination and escalation path.',
    affectedWos: ['WO-350087', 'WO-350188', 'WO-350240'],
    relatedRisks: [],
    preparedActions: [
      {id: 'prep-cluster-quality', label: 'Notify QA release owners', actionType: 'Notify quality', governed: true, owner: 'Quality Eng.', reasonCode: 'QA-REL', confirmationLabel: 'Confirm Notification', comment: 'Request QA release update and identify delegate sign-off before the next freeze point.'},
    ],
    suggestedQuestions: ['Why is QA the constraint?', 'What happens if no release arrives?', 'Who should own the response?'],
    eventTimeline: ['08:38 latest lab result completed.', '07:55 director availability changed.'],
  },
  'cluster-sterilization': {
    clusterName: 'Sterilization Risk',
    severity: 'High',
    owner: 'Sterilization',
    actionStatus: 'New',
    demandAtRisk: '4 batches',
    recoverableQty: '3 batches',
    linesImpacted: 'Ster-02 / Line 05',
    earliestRisk: 'Tomorrow 09:00',
    rootCauseSummary: 'Ster-02 remains the only qualified resource and slot reservations are not locked before the dwell threshold.',
    aiRecoveryPlan: 'Reserve the next feasible slot for priority batches and protect Family C release window.',
    noActionImpact: 'Batch release slips 5 to 7 days and customer commitment risk increases.',
    suggestedOwnerReason: 'Sterilization team controls slot reservation and maintenance-based capacity recovery.',
    affectedWos: ['WO-350145', 'WO-350290'],
    relatedRisks: [],
    preparedActions: [
      {id: 'prep-cluster-ster', label: 'Reserve priority sterilization slot', actionType: 'Reserve slot', governed: true, owner: 'Sterilization', reasonCode: 'STER-SLOT', confirmationLabel: 'Confirm Reservation Request', comment: 'Reserve next feasible slot for priority batches before dwell risk increases.'},
    ],
    suggestedQuestions: ['Which batches are at risk?', 'What is the deadline?', 'Can demand still be recovered?'],
    eventTimeline: ['08:52 backlog increased by one batch.', '07:48 maintenance overrun absorbed one slot.'],
  },
  'cluster-labor-coverage': {
    clusterName: 'Labor Coverage',
    severity: 'High',
    owner: 'Production Manager',
    actionStatus: 'Waiting Response',
    demandAtRisk: '80K units',
    recoverableQty: '80K units',
    linesImpacted: 'Line 03',
    earliestRisk: 'Tomorrow 13:00',
    rootCauseSummary: 'Certified operator coverage is missing for the next shift window and no owner is assigned.',
    aiRecoveryPlan: 'Assign shift coverage owner now, then confirm cross-trained backup or delay decision.',
    noActionImpact: 'Line 03 misses start, planner may need to hold the WO manually, and demand protection degrades.',
    suggestedOwnerReason: 'Production manager controls crew assignment and escalation to shift leads.',
    affectedWos: ['WO-350200', 'WO-350245'],
    relatedRisks: [],
    preparedActions: [
      {id: 'prep-cluster-labor', label: 'Assign shift coverage owner', actionType: 'Assign owner', governed: true, owner: 'Production Manager', reasonCode: 'LAB-GAP', confirmationLabel: 'Confirm Assignment', comment: 'Assign an accountable owner for certified shift coverage before tomorrow 13:00.'},
    ],
    suggestedQuestions: ['Who owns the fix?', 'How much demand is protected?', 'What if no labor is found?'],
    eventTimeline: ['08:03 HR confirmed leave extension.', '07:41 AI changed cluster to Waiting Response.'],
  },
};

export const demandRiskRows: DemandRiskRow[] = [
  {
    id: 'demand-family-a',
    family: 'Family A',
    demandRequired: '1.2M units',
    readyQuantity: '700K units',
    atRiskQuantity: '500K units',
    recoverableQuantity: '500K units',
    mainConstraint: 'Material shortage',
    affectedWos: ['WO-350021', 'WO-350311'],
    earliestRiskDate: 'Today 14:00',
    aiRecoveryRecommendation: 'Expedite RM-4421 or replace WO.',
    nextAction: 'Open Recovery Plan',
    owner: 'Material Controller',
    confidence: 'Medium',
    preparedActionId: 'prep-demand-family-a',
    recommendationId: 'AI-80001',
  },
  {
    id: 'demand-family-b',
    family: 'Family B',
    demandRequired: '500K units',
    readyQuantity: '380K units',
    atRiskQuantity: '120K units',
    recoverableQuantity: '120K units',
    mainConstraint: 'QA release pending',
    affectedWos: ['WO-350087'],
    earliestRiskDate: 'Today 18:00',
    aiRecoveryRecommendation: 'Request QA release update.',
    nextAction: 'Notify QA',
    owner: 'Quality Eng.',
    confidence: 'Medium',
    preparedActionId: 'prep-demand-family-b',
    recommendationId: 'AI-80002',
  },
  {
    id: 'demand-family-c',
    family: 'Family C',
    demandRequired: '3 batches',
    readyQuantity: '0 confirmed',
    atRiskQuantity: '3 batches',
    recoverableQuantity: '3 batches',
    mainConstraint: 'Sterilization slot',
    affectedWos: ['WO-350145'],
    earliestRiskDate: 'Tomorrow 09:00',
    aiRecoveryRecommendation: 'Reserve slot.',
    nextAction: 'Reserve Slot',
    owner: 'Sterilization',
    confidence: 'High',
    preparedActionId: 'prep-demand-family-c',
    recommendationId: 'AI-80003',
  },
  {
    id: 'demand-family-d',
    family: 'Family D',
    demandRequired: '180K units',
    readyQuantity: '100K units',
    atRiskQuantity: '80K units',
    recoverableQuantity: '80K units',
    mainConstraint: 'Labor coverage',
    affectedWos: ['WO-350200'],
    earliestRiskDate: 'Tomorrow 13:00',
    aiRecoveryRecommendation: 'Assign shift coverage.',
    nextAction: 'Assign Shift Coverage',
    owner: 'Production Manager',
    confidence: 'Medium',
    preparedActionId: 'prep-demand-family-d',
    recommendationId: 'AI-80004',
  },
];

export const demandRiskDetailMap: Record<string, DemandRiskDetail> = {
  'demand-family-a': {
    family: 'Family A',
    demandRequired: '1.2M units',
    readyQuantity: '700K units',
    atRiskQuantity: '500K units',
    recoverableQuantity: '500K units',
    constraints: ['RM-4421 shortage', 'Missing supplier ETA', 'Line 10 dependency'],
    relatedWos: ['WO-350021', 'WO-350311'],
    aiRecoveryRecommendation: 'Expedite RM-4421 or switch to ready replacement WO if no ETA arrives by 12:00.',
    noActionImpact: 'Family A service level breach and immediate exposure for 500K units.',
    demandProtectionActions: [
      {id: 'prep-demand-family-a', label: 'Open Family A recovery plan', actionType: 'Open recovery plan', governed: false, owner: 'Material Controller', reasonCode: 'DEM-PROT', confirmationLabel: 'Log Review', comment: 'Review recovery options for Family A demand before noon.'},
    ],
    suggestedQuestions: ['Which WO protects demand first?', 'What is the main constraint?', 'What if no ETA arrives?'],
  },
  'demand-family-b': {
    family: 'Family B',
    demandRequired: '500K units',
    readyQuantity: '380K units',
    atRiskQuantity: '120K units',
    recoverableQuantity: '120K units',
    constraints: ['QA release pending', 'Frozen period start tomorrow'],
    relatedWos: ['WO-350087'],
    aiRecoveryRecommendation: 'Request QA release update and confirm delegate sign-off.',
    noActionImpact: '120K units move into late planning response and may require expedited freight.',
    demandProtectionActions: [
      {id: 'prep-demand-family-b', label: 'Notify QA for Family B', actionType: 'Notify quality', governed: true, owner: 'Quality Eng.', reasonCode: 'QA-REL', confirmationLabel: 'Confirm Notification', comment: 'Request immediate release update for Family B risk exposure.'},
    ],
    suggestedQuestions: ['How much can still be recovered?', 'Who needs to respond?', 'When is the cutoff?'],
  },
  'demand-family-c': {
    family: 'Family C',
    demandRequired: '3 batches',
    readyQuantity: '0 confirmed',
    atRiskQuantity: '3 batches',
    recoverableQuantity: '3 batches',
    constraints: ['Ster-02 slot not reserved', 'Single qualified sterilizer'],
    relatedWos: ['WO-350145'],
    aiRecoveryRecommendation: 'Reserve slot before dwell risk window closes.',
    noActionImpact: 'Three batches slip 5 to 7 days.',
    demandProtectionActions: [
      {id: 'prep-demand-family-c', label: 'Reserve Family C slot', actionType: 'Reserve slot', governed: true, owner: 'Sterilization', reasonCode: 'STER-SLOT', confirmationLabel: 'Confirm Reservation Request', comment: 'Reserve slot for Family C priority batches.'},
    ],
    suggestedQuestions: ['What is the recovery deadline?', 'Which batches are protected?', 'What happens if no slot is reserved?'],
  },
  'demand-family-d': {
    family: 'Family D',
    demandRequired: '180K units',
    readyQuantity: '100K units',
    atRiskQuantity: '80K units',
    recoverableQuantity: '80K units',
    constraints: ['Certified labor shortage'],
    relatedWos: ['WO-350200'],
    aiRecoveryRecommendation: 'Assign shift coverage owner and confirm backup crew.',
    noActionImpact: 'Line 03 misses its planned start and demand protection drops.',
    demandProtectionActions: [
      {id: 'prep-demand-family-d', label: 'Assign Family D coverage owner', actionType: 'Assign owner', governed: true, owner: 'Production Manager', reasonCode: 'LAB-GAP', confirmationLabel: 'Confirm Assignment', comment: 'Assign owner for Family D shift coverage.'},
    ],
    suggestedQuestions: ['Who owns the action?', 'Can the risk still be recovered?', 'What is the due time?'],
  },
};

export const lineImpactRows: LineImpactRow[] = [
  {
    id: 'line-10',
    lineMachine: 'Line 10',
    wosAtRisk: '2 WOs',
    atRiskQuantity: '560K units',
    lineHoursAtRisk: '3.5h',
    primaryConstraint: 'Material shortage',
    earliestImpact: 'Today 14:00',
    aiRecommendation: 'Expedite RM-4421 or replace WO.',
    nextAction: 'Open Recovery Plan',
  },
  {
    id: 'line-07',
    lineMachine: 'Line 07',
    wosAtRisk: '1 WO',
    atRiskQuantity: '120K units',
    lineHoursAtRisk: '1.5h',
    primaryConstraint: 'QA release pending',
    earliestImpact: 'Today 18:00',
    aiRecommendation: 'Request QA release update.',
    nextAction: 'Notify QA',
  },
  {
    id: 'line-03',
    lineMachine: 'Line 03',
    wosAtRisk: '1 WO',
    atRiskQuantity: '80K units',
    lineHoursAtRisk: '1.5h',
    primaryConstraint: 'Certified labor shortage',
    earliestImpact: 'Tomorrow 13:00',
    aiRecommendation: 'Assign shift coverage.',
    nextAction: 'Assign Shift Coverage',
  },
];

export const aiInsightMap: Record<string, AiInsight> = {
  'WO-350021': {
    whyPriority: 'Ranked #1 because 500K units are at risk, the work order starts today, the blocker is hard, and no recovery is confirmed.',
    predictedImpact: 'Protects the largest demand commitment on the page and prevents 3.5h of Line 10 disruption.',
    recommendedAction: 'Assign material owner, expedite RM-4421, and prepare replacement WO if no ETA is confirmed by 12:00.',
    confidence: 'Medium',
    dataFreshness: 'Inventory 35 min ago. Supplier ETA missing.',
    isStale: true,
    suggestedOwner: 'Material Controller',
    deadline: 'Today 12:00',
    governed: true,
    noActionImpact: '500K units remain exposed and Family A slips into the next shipping window.',
    relatedObjects: ['WO-350311', 'Family A', 'Line 10'],
  },
  'WO-350087': {
    whyPriority: 'Single blocker with near-term start and high frozen-window sensitivity.',
    predictedImpact: 'Protects 120K units and avoids late-day resequencing.',
    recommendedAction: 'Notify QA and confirm delegate sign-off path.',
    confidence: 'Medium',
    dataFreshness: 'QMS 18 min ago.',
    isStale: false,
    suggestedOwner: 'Quality Eng.',
    deadline: 'Today 15:00',
    governed: true,
    noActionImpact: 'Frozen window exposure increases and Family B may require expedited freight.',
  },
  'WO-350145': {
    whyPriority: 'Ster-02 is single-point-of-failure and the reservation window closes tomorrow morning.',
    predictedImpact: 'Protects 3 batches and preserves Family C release.',
    recommendedAction: 'Reserve the next feasible sterilization slot.',
    confidence: 'High',
    dataFreshness: 'Ster schedule 14 min ago.',
    isStale: false,
    suggestedOwner: 'Sterilization',
    deadline: 'Tomorrow 09:00',
    governed: true,
    noActionImpact: 'Release slips 5 to 7 days for all three batches.',
  },
  'WO-350200': {
    whyPriority: 'No certified labor owner is assigned and the start cannot be executed safely without coverage.',
    predictedImpact: 'Protects 80K units and avoids a one-day start slip.',
    recommendedAction: 'Assign shift coverage owner now and confirm backup crew.',
    confidence: 'Medium',
    dataFreshness: 'HR 1h ago.',
    isStale: false,
    suggestedOwner: 'Production Manager',
    deadline: 'Tomorrow 13:00',
    governed: true,
    noActionImpact: 'Line 03 start is missed and demand recovery degrades.',
  },
  'WO-350311': {
    whyPriority: 'This WO depends on the same root cause as WO-350021 and should be managed as a contingency decision.',
    predictedImpact: 'Keeps Family A recovery options open if Line 10 remains constrained.',
    recommendedAction: 'Prepare contingency resequencing to Line 12.',
    confidence: 'High',
    dataFreshness: 'Capacity 20 min ago.',
    isStale: false,
    suggestedOwner: 'Planner',
    deadline: 'Tomorrow 10:00',
    governed: false,
    noActionImpact: 'Planner will make a late rescheduling decision with fewer options.',
  },
  'WO-350422': {
    whyPriority: 'This WO is ready and serves as a contingency to protect flow if Family A remains blocked.',
    predictedImpact: 'Provides ready capacity coverage with low risk.',
    recommendedAction: 'Keep as replacement candidate and monitor.',
    confidence: 'High',
    dataFreshness: 'All sources under 30 min.',
    isStale: false,
    suggestedOwner: 'Planner',
    deadline: '29-May 08:00',
    governed: false,
  },
  'cluster-material-shortage': {
    whyPriority: 'Largest root cause by demand impact and the main driver of the top-ranked WO.',
    predictedImpact: 'Clearing this cluster protects 620K units and relieves Line 10.',
    recommendedAction: 'Assign material recovery owner and escalate supplier team if ETA remains missing.',
    confidence: 'Medium',
    dataFreshness: 'Supplier portal stale, inventory fresh.',
    isStale: true,
    suggestedOwner: 'Material Controller',
    deadline: 'Today 12:00',
    governed: true,
    noActionImpact: 'Family A and dependent WOs remain exposed across two lines.',
    relatedObjects: ['WO-350021', 'WO-350311', 'Line 10'],
  },
  'cluster-quality-release': {
    whyPriority: 'Time-sensitive blocker near start window with high recoverability if acted on now.',
    predictedImpact: 'Protects 210K units by keeping quality releases on time.',
    recommendedAction: 'Notify QA release owners and confirm delegate sign-off.',
    confidence: 'Medium',
    dataFreshness: 'QMS and LIMS fresh.',
    isStale: false,
    suggestedOwner: 'Quality Eng.',
    deadline: 'Today 15:00',
    governed: true,
  },
  'cluster-sterilization': {
    whyPriority: 'Single qualified resource with hard reservation deadline.',
    predictedImpact: 'Protects 3 of 4 exposed batches if action is confirmed now.',
    recommendedAction: 'Reserve a priority Ster-02 slot.',
    confidence: 'High',
    dataFreshness: 'Ster schedule fresh.',
    isStale: false,
    suggestedOwner: 'Sterilization',
    deadline: 'Tomorrow 09:00',
    governed: true,
  },
  'cluster-labor-coverage': {
    whyPriority: 'No owner assigned and certified labor gap remains open.',
    predictedImpact: 'Protects 80K units and avoids unsafe staffing on Line 03.',
    recommendedAction: 'Assign shift coverage owner and escalate if no response.',
    confidence: 'Medium',
    dataFreshness: 'HR 1h ago.',
    isStale: false,
    suggestedOwner: 'Production Manager',
    deadline: 'Tomorrow 13:00',
    governed: true,
  },
  'demand-family-a': {
    whyPriority: 'Family A has the highest immediate demand exposure on the page.',
    predictedImpact: '500K units can still be protected today.',
    recommendedAction: 'Open the Family A recovery plan and confirm material path.',
    confidence: 'Medium',
    dataFreshness: 'Demand and inventory synced in the last 35 min.',
    isStale: false,
    suggestedOwner: 'Material Controller',
    deadline: 'Today 12:00',
    governed: false,
  },
  'demand-family-b': {
    whyPriority: 'Family B is fully recoverable if QA responds in time.',
    predictedImpact: '120K units remain protectable today.',
    recommendedAction: 'Notify QA and request release update.',
    confidence: 'Medium',
    dataFreshness: 'QMS fresh.',
    isStale: false,
    suggestedOwner: 'Quality Eng.',
    deadline: 'Today 15:00',
    governed: true,
  },
  'demand-family-c': {
    whyPriority: 'All exposed batches share a single hard resource.',
    predictedImpact: '3 batches can still be protected before dwell risk increases.',
    recommendedAction: 'Reserve slot now.',
    confidence: 'High',
    dataFreshness: 'Ster schedule fresh.',
    isStale: false,
    suggestedOwner: 'Sterilization',
    deadline: 'Tomorrow 09:00',
    governed: true,
  },
  'demand-family-d': {
    whyPriority: 'Demand is smaller, but still fully recoverable if labor is assigned.',
    predictedImpact: '80K units remain recoverable.',
    recommendedAction: 'Assign shift coverage owner.',
    confidence: 'Medium',
    dataFreshness: 'HR 1h ago.',
    isStale: false,
    suggestedOwner: 'Production Manager',
    deadline: 'Tomorrow 13:00',
    governed: true,
  },
};

export const conversationHistory: Record<string, ConversationEntry[]> = {
  'WO-350021': [
    {id: 'wo1-1', user: 'AI', timestamp: '09:05', text: 'WO-350021 remains #1 because material shortage is still unresolved and no replacement WO is selected.', type: 'ai'},
    {id: 'wo1-2', user: 'Maria Santos', timestamp: '08:41', text: 'Supplier B can confirm feasibility by 11:30.', type: 'comment'},
    {id: 'wo1-3', user: 'System', timestamp: '08:18', text: 'Inventory sync reduced available RM-4421 by another 50K units.', type: 'system'},
  ],
  'WO-350087': [
    {id: 'wo2-1', user: 'AI', timestamp: '08:52', text: 'Family B remains recoverable today if QA confirms release before 15:00.', type: 'ai'},
    {id: 'wo2-2', user: 'Ana Lima', timestamp: '08:38', text: 'Latest lab result posted and forwarded to QA Director.', type: 'comment'},
  ],
  'WO-350145': [
    {id: 'wo3-1', user: 'AI', timestamp: '08:50', text: 'Reserve a slot now to avoid dwell risk. Confidence is high because Ster-02 remains the only qualified resource.', type: 'ai'},
  ],
  'WO-350200': [
    {id: 'wo4-1', user: 'AI', timestamp: '08:06', text: 'Line 03 cannot start safely without certified coverage. Assign an owner before tomorrow 13:00.', type: 'ai'},
  ],
  'WO-350311': [
    {id: 'wo5-1', user: 'Planner', timestamp: '08:46', text: 'Will prepare contingency on Line 12 if Family A material recovery misses noon cutoff.', type: 'comment'},
  ],
  'cluster-material-shortage': [
    {id: 'rm1', user: 'AI', timestamp: '09:05', text: 'This cluster protects the most demand. Start with RM-4421 recovery before resequencing.', type: 'ai'},
    {id: 'rm2', user: 'Maria Santos', timestamp: '08:41', text: 'Supplier team is waiting for planner confirmation to open emergency expedite.', type: 'action'},
  ],
  'cluster-quality-release': [
    {id: 'rq1', user: 'AI', timestamp: '08:52', text: 'Quality release remains the narrowest time window after material shortage.', type: 'ai'},
  ],
  'cluster-sterilization': [
    {id: 'rs1', user: 'Carlos Rocha', timestamp: '08:47', text: 'Ster-02 can absorb one priority slot if we lock it before 09:00 tomorrow.', type: 'comment'},
  ],
  'cluster-labor-coverage': [
    {id: 'rl1', user: 'AI', timestamp: '08:06', text: 'Coverage is unassigned. Escalate if no owner responds within the next shift planning cycle.', type: 'ai'},
  ],
  'demand-family-a': [
    {id: 'dfa1', user: 'AI', timestamp: '09:02', text: 'Family A is still recoverable today, but only if RM-4421 action is confirmed by noon.', type: 'ai'},
  ],
  'demand-family-b': [
    {id: 'dfb1', user: 'AI', timestamp: '08:54', text: 'Family B is fully recoverable if QA responds before the frozen window closes.', type: 'ai'},
  ],
};

export const preparedActionPayloads: Record<string, ActionPayload> = {
  'prep-wo-350021': {
    title: 'Assign blocker',
    relatedLabel: 'WO-350021',
    owner: 'Material Controller',
    reasonCode: 'MAT-SHORT',
    recommendationId: 'AI-78421',
    rationale: 'WO is blocked by material shortage. 500K units are at risk. Action is required before 12:00 to protect demand.',
    comment: 'Please confirm expedite feasibility for RM-4421. If no ETA is available by 12:00, evaluate replacement WO.',
    confirmationLabel: 'Confirm Assignment',
  },
  'prep-wo-350087': {
    title: 'Notify QA release owner',
    relatedLabel: 'WO-350087',
    owner: 'Quality Eng.',
    reasonCode: 'QA-REL',
    recommendationId: 'AI-78422',
    rationale: 'WO starts within 24h and release is the only blocker. Prompt QA response protects 120K units.',
    comment: 'Please confirm release status and identify a delegate sign-off path before 15:00.',
    confirmationLabel: 'Confirm Notification',
  },
  'prep-wo-350145': {
    title: 'Reserve sterilization slot',
    relatedLabel: 'WO-350145',
    owner: 'Sterilization',
    reasonCode: 'STER-SLOT',
    recommendationId: 'AI-78423',
    rationale: 'Ster-02 is the only qualified resource. Reserving a slot protects three priority batches.',
    comment: 'Reserve the next feasible Ster-02 slot before dwell risk increases tomorrow morning.',
    confirmationLabel: 'Confirm Reservation Request',
  },
  'prep-wo-350200': {
    title: 'Assign shift coverage owner',
    relatedLabel: 'WO-350200',
    owner: 'Production Manager',
    reasonCode: 'LAB-GAP',
    recommendationId: 'AI-78424',
    rationale: 'Certified labor gap is open and 80K units are exposed. An owner is required before tomorrow 13:00.',
    comment: 'Assign the accountable owner for certified shift coverage or confirm that the WO should be delayed.',
    confirmationLabel: 'Confirm Assignment',
  },
  'prep-cluster-material': {
    title: 'Assign material recovery owner',
    relatedLabel: 'Material Shortage Cluster',
    owner: 'Material Controller',
    reasonCode: 'MAT-SHORT',
    recommendationId: 'AI-79001',
    rationale: 'This cluster protects the most demand and drives the top-ranked WO.',
    comment: 'Assign material recovery ownership and trigger same-day supplier ETA update.',
    confirmationLabel: 'Confirm Assignment',
  },
  'prep-cluster-quality': {
    title: 'Notify quality release owners',
    relatedLabel: 'Quality Release Pending Cluster',
    owner: 'Quality Eng.',
    reasonCode: 'QA-REL',
    recommendationId: 'AI-79002',
    rationale: 'The cluster is time-sensitive and still fully recoverable today.',
    comment: 'Notify quality owners and confirm delegate sign-off before the next freeze point.',
    confirmationLabel: 'Confirm Notification',
  },
  'prep-cluster-ster': {
    title: 'Reserve priority sterilization slot',
    relatedLabel: 'Sterilization Risk Cluster',
    owner: 'Sterilization',
    reasonCode: 'STER-SLOT',
    recommendationId: 'AI-79003',
    rationale: 'Ster-02 is single-point-of-failure and demand remains recoverable with a slot reservation.',
    comment: 'Reserve the next feasible slot for priority batches before dwell risk increases.',
    confirmationLabel: 'Confirm Reservation Request',
  },
  'prep-cluster-labor': {
    title: 'Assign shift coverage owner',
    relatedLabel: 'Labor Coverage Cluster',
    owner: 'Production Manager',
    reasonCode: 'LAB-GAP',
    recommendationId: 'AI-79004',
    rationale: 'No owner is assigned and the labor gap blocks safe execution.',
    comment: 'Assign an accountable owner for certified coverage before tomorrow 13:00.',
    confirmationLabel: 'Confirm Assignment',
  },
  'prep-demand-family-b': {
    title: 'Notify QA for Family B demand risk',
    relatedLabel: 'Family B demand risk',
    owner: 'Quality Eng.',
    reasonCode: 'QA-REL',
    recommendationId: 'AI-80002',
    rationale: 'Family B is fully recoverable if QA responds in time.',
    comment: 'Please confirm release status for Family B demand exposure.',
    confirmationLabel: 'Confirm Notification',
  },
  'prep-demand-family-c': {
    title: 'Reserve Family C slot',
    relatedLabel: 'Family C demand risk',
    owner: 'Sterilization',
    reasonCode: 'STER-SLOT',
    recommendationId: 'AI-80003',
    rationale: 'Three Family C batches remain recoverable before the dwell deadline.',
    comment: 'Reserve priority sterilization slot for Family C now.',
    confirmationLabel: 'Confirm Reservation Request',
  },
  'prep-demand-family-d': {
    title: 'Assign Family D coverage owner',
    relatedLabel: 'Family D demand risk',
    owner: 'Production Manager',
    reasonCode: 'LAB-GAP',
    recommendationId: 'AI-80004',
    rationale: 'Family D is fully recoverable if labor ownership is assigned immediately.',
    comment: 'Assign accountable owner for Family D shift coverage.',
    confirmationLabel: 'Confirm Assignment',
  },
};
