import type {
  ProductionLine,
  WorkOrder,
  WorkOrderAuditEvent,
  WorkOrderException,
  WorkOrderExceptionStatus,
  WorkOrderMaterialItem,
  WorkOrderOperation,
  WorkOrderOperationStatus,
  WorkOrderReadinessCategory,
  WorkOrderReadinessCheck,
  WorkOrderReadinessCheckStatus,
  WorkOrdersBundle,
} from './types';
import {hydrateWorkOrders} from './utils';

const REFERENCE_NOW = '2026-05-13T17:00:00.000Z';

const readinessCategories: WorkOrderReadinessCategory[] = [
  'Material',
  'Machine',
  'Labor',
  'Quality',
  'Documentation',
  'Tooling',
  'WarehouseStaging',
  'Schedule',
  'BatchLot',
];

const lineLookup: ProductionLine[] = [
  {id: 'line-10', name: 'Line 10', area: 'Filling', active: true},
  {id: 'line-20', name: 'Line 20', area: 'Assembly', active: true},
  {id: 'line-30', name: 'Line 30', area: 'Packing', active: true},
];

function createBaseWorkOrders(): WorkOrder[] {
  return [
    {
      id: 'wo-100245',
      woNumber: 'WO-100245',
      batchNumber: 'B100245',
      productCode: 'FG-1001',
      productDescription: 'Standard Tube A',
      productFamily: 'Standard Tubes',
      quantityRequired: 32000,
      quantityProduced: 18500,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-15T13:00:00.000Z',
      plannedStartDate: '2026-05-13T08:00:00.000Z',
      plannedEndDate: '2026-05-15T06:00:00.000Z',
      actualStartDate: '2026-05-13T08:00:00.000Z',
      actualEndDate: null,
      assignedLineId: 'line-10',
      assignedLineName: 'Line 10',
      shift: 'Day',
      crew: 'Crew A',
      priority: 'High',
      status: 'Running',
      readinessStatus: 'Ready',
      materialStatus: 'Available',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Danilo Brooks',
      lastUpdatedAt: '2026-05-13T16:55:00.000Z',
      plannerComment: 'Keep line steady through current campaign.',
      progressPercent: 0,
    },
    {
      id: 'wo-100246',
      woNumber: 'WO-100246',
      batchNumber: 'B100246',
      productCode: 'FG-2001',
      productDescription: 'Additive Tube',
      productFamily: 'Additives',
      quantityRequired: 18000,
      quantityProduced: 0,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-14T14:00:00.000Z',
      plannedStartDate: '2026-05-14T07:00:00.000Z',
      plannedEndDate: '2026-05-15T18:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-20',
      assignedLineName: 'Line 20',
      shift: 'Day',
      crew: 'Crew B',
      priority: 'Critical',
      status: 'Blocked',
      readinessStatus: 'Blocked',
      materialStatus: 'Shortage',
      qualityStatus: 'Hold',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Chris Klopp',
      lastUpdatedAt: '2026-05-13T16:50:00.000Z',
      plannerComment: 'Blocked on additive resin and QA hold disposition.',
      progressPercent: 0,
    },
    {
      id: 'wo-100247',
      woNumber: 'WO-100247',
      batchNumber: 'B100247',
      productCode: 'FG-1002',
      productDescription: 'Standard Tube B',
      productFamily: 'Standard Tubes',
      quantityRequired: 39500,
      quantityProduced: 8200,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-18T19:00:00.000Z',
      plannedStartDate: '2026-05-15T02:00:00.000Z',
      plannedEndDate: '2026-05-18T11:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-10',
      assignedLineName: 'Line 10',
      shift: 'Night',
      crew: 'Crew A',
      priority: 'High',
      status: 'Released',
      readinessStatus: 'Warning',
      materialStatus: 'Partial',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Danilo Brooks',
      lastUpdatedAt: '2026-05-13T16:48:00.000Z',
      plannerComment: 'Waiting for final staging confirmation.',
      progressPercent: 0,
    },
    {
      id: 'wo-100248',
      woNumber: 'WO-100248',
      batchNumber: 'B100248',
      productCode: 'FG-3001',
      productDescription: 'Gel Product',
      productFamily: 'Gels',
      quantityRequired: 22000,
      quantityProduced: 22000,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-12T18:00:00.000Z',
      plannedStartDate: '2026-05-10T11:00:00.000Z',
      plannedEndDate: '2026-05-12T12:00:00.000Z',
      actualStartDate: '2026-05-10T10:30:00.000Z',
      actualEndDate: '2026-05-12T11:45:00.000Z',
      assignedLineId: 'line-20',
      assignedLineName: 'Line 20',
      shift: 'Day',
      crew: 'Crew B',
      priority: 'Medium',
      status: 'Completed',
      readinessStatus: 'Ready',
      materialStatus: 'Available',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Maria Santos',
      lastUpdatedAt: '2026-05-13T16:40:00.000Z',
      plannerComment: 'Completed cleanly and released to pack-out.',
      progressPercent: 0,
    },
    {
      id: 'wo-100249',
      woNumber: 'WO-100249',
      batchNumber: 'B100249',
      productCode: 'FG-4001',
      productDescription: 'Specialty Pack',
      productFamily: 'Specialty',
      quantityRequired: 5200,
      quantityProduced: 0,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-19T17:00:00.000Z',
      plannedStartDate: '2026-05-16T18:00:00.000Z',
      plannedEndDate: '2026-05-19T06:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-30',
      assignedLineName: 'Line 30',
      shift: 'Day',
      crew: 'Crew C',
      priority: 'Medium',
      status: 'Planned',
      readinessStatus: 'Warning',
      materialStatus: 'Available',
      qualityStatus: 'InspectionRequired',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'James Lee',
      lastUpdatedAt: '2026-05-13T16:35:00.000Z',
      plannerComment: 'Documentation check pending before release.',
      progressPercent: 0,
    },
    {
      id: 'wo-100250',
      woNumber: 'WO-100250',
      batchNumber: 'B100250',
      productCode: 'FG-5001',
      productDescription: 'Low Volume Product',
      productFamily: 'Low Volume',
      quantityRequired: 1700,
      quantityProduced: 0,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-20T16:00:00.000Z',
      plannedStartDate: '2026-05-17T13:00:00.000Z',
      plannedEndDate: '2026-05-20T03:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-30',
      assignedLineName: 'Line 30',
      shift: 'Night',
      crew: 'Crew C',
      priority: 'Low',
      status: 'Planned',
      readinessStatus: 'Ready',
      materialStatus: 'Available',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'James Lee',
      lastUpdatedAt: '2026-05-13T16:30:00.000Z',
      plannerComment: 'Low-risk order available to fill capacity.',
      progressPercent: 0,
    },
    {
      id: 'wo-100251',
      woNumber: 'WO-100251',
      batchNumber: 'B100251',
      productCode: 'FG-1001',
      productDescription: 'Standard Tube A',
      productFamily: 'Standard Tubes',
      quantityRequired: 28000,
      quantityProduced: 6000,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-14T05:00:00.000Z',
      plannedStartDate: '2026-05-12T18:00:00.000Z',
      plannedEndDate: '2026-05-14T03:00:00.000Z',
      actualStartDate: '2026-05-12T17:30:00.000Z',
      actualEndDate: null,
      assignedLineId: 'line-10',
      assignedLineName: 'Line 10',
      shift: 'Day',
      crew: 'Crew A',
      priority: 'Critical',
      status: 'Running',
      readinessStatus: 'Warning',
      materialStatus: 'Available',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Maria Santos',
      lastUpdatedAt: '2026-05-13T16:25:00.000Z',
      plannerComment: 'Running behind plan after short microstop cluster.',
      progressPercent: 0,
    },
    {
      id: 'wo-100252',
      woNumber: 'WO-100252',
      batchNumber: 'B100252',
      productCode: 'FG-2001',
      productDescription: 'Additive Tube',
      productFamily: 'Additives',
      quantityRequired: 12000,
      quantityProduced: 0,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-21T21:00:00.000Z',
      plannedStartDate: '2026-05-18T11:00:00.000Z',
      plannedEndDate: '2026-05-21T12:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-20',
      assignedLineName: 'Line 20',
      shift: 'Day',
      crew: 'Crew B',
      priority: 'High',
      status: 'Blocked',
      readinessStatus: 'Blocked',
      materialStatus: 'Blocked',
      qualityStatus: 'Hold',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Chris Klopp',
      lastUpdatedAt: '2026-05-13T16:20:00.000Z',
      plannerComment: 'Waiting for document revision and released lot disposition.',
      progressPercent: 0,
    },
    {
      id: 'wo-100253',
      woNumber: 'WO-100253',
      batchNumber: 'B100253',
      productCode: 'FG-3001',
      productDescription: 'Gel Product',
      productFamily: 'Gels',
      quantityRequired: 24000,
      quantityProduced: 4000,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-16T09:00:00.000Z',
      plannedStartDate: '2026-05-14T11:00:00.000Z',
      plannedEndDate: '2026-05-16T08:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-20',
      assignedLineName: 'Line 20',
      shift: 'Night',
      crew: 'Crew B',
      priority: 'Medium',
      status: 'Released',
      readinessStatus: 'Ready',
      materialStatus: 'Available',
      qualityStatus: 'InspectionRequired',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Maria Santos',
      lastUpdatedAt: '2026-05-13T16:15:00.000Z',
      plannerComment: 'QA inspection slot reserved before line handoff.',
      progressPercent: 0,
    },
    {
      id: 'wo-100254',
      woNumber: 'WO-100254',
      batchNumber: 'B100254',
      productCode: 'FG-4001',
      productDescription: 'Specialty Pack',
      productFamily: 'Specialty',
      quantityRequired: 7600,
      quantityProduced: 2600,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-13T12:00:00.000Z',
      plannedStartDate: '2026-05-12T22:00:00.000Z',
      plannedEndDate: '2026-05-13T11:00:00.000Z',
      actualStartDate: '2026-05-12T21:55:00.000Z',
      actualEndDate: null,
      assignedLineId: 'line-30',
      assignedLineName: 'Line 30',
      shift: 'Day',
      crew: 'Crew C',
      priority: 'High',
      status: 'Paused',
      readinessStatus: 'Warning',
      materialStatus: 'Partial',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Lena Ortiz',
      lastUpdatedAt: '2026-05-13T16:10:00.000Z',
      plannerComment: 'Paused during changeover recovery.',
      progressPercent: 0,
    },
    {
      id: 'wo-100255',
      woNumber: 'WO-100255',
      batchNumber: 'B100255',
      productCode: 'FG-5001',
      productDescription: 'Low Volume Product',
      productFamily: 'Low Volume',
      quantityRequired: 4800,
      quantityProduced: 1200,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-12T10:00:00.000Z',
      plannedStartDate: '2026-05-11T07:00:00.000Z',
      plannedEndDate: '2026-05-12T07:00:00.000Z',
      actualStartDate: '2026-05-11T06:30:00.000Z',
      actualEndDate: null,
      assignedLineId: 'line-30',
      assignedLineName: 'Line 30',
      shift: 'Night',
      crew: 'Crew C',
      priority: 'Medium',
      status: 'Interrupted',
      readinessStatus: 'Warning',
      materialStatus: 'Available',
      qualityStatus: 'Nonconformance',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Lena Ortiz',
      lastUpdatedAt: '2026-05-13T16:05:00.000Z',
      plannerComment: 'Interrupted after process capability drift.',
      progressPercent: 0,
    },
    {
      id: 'wo-100256',
      woNumber: 'WO-100256',
      batchNumber: 'B100256',
      productCode: 'FG-1002',
      productDescription: 'Standard Tube B',
      productFamily: 'Standard Tubes',
      quantityRequired: 21000,
      quantityProduced: 0,
      quantityRemaining: 0,
      uom: 'PCS',
      dueDate: '2026-05-17T15:00:00.000Z',
      plannedStartDate: '2026-05-15T08:00:00.000Z',
      plannedEndDate: '2026-05-17T06:00:00.000Z',
      actualStartDate: null,
      actualEndDate: null,
      assignedLineId: 'line-10',
      assignedLineName: 'Line 10',
      shift: 'Day',
      crew: 'Crew A',
      priority: 'Low',
      status: 'Ready',
      readinessStatus: 'Ready',
      materialStatus: 'Available',
      qualityStatus: 'Clear',
      scheduleStatus: 'OnTime',
      exceptionCount: 0,
      owner: 'Danilo Brooks',
      lastUpdatedAt: '2026-05-13T16:00:00.000Z',
      plannerComment: 'Ready to release after current line clears.',
      progressPercent: 0,
    },
  ];
}

function createReadinessChecks(): WorkOrderReadinessCheck[] {
  const overrides: Record<string, Partial<Record<WorkOrderReadinessCategory, WorkOrderReadinessCheckStatus>>> = {
    'wo-100245': {},
    'wo-100246': {Material: 'Blocked', Quality: 'Blocked', WarehouseStaging: 'Warning'},
    'wo-100247': {WarehouseStaging: 'Warning'},
    'wo-100248': {},
    'wo-100249': {Documentation: 'Warning', Quality: 'Warning'},
    'wo-100250': {},
    'wo-100251': {Schedule: 'Warning'},
    'wo-100252': {Documentation: 'Blocked', BatchLot: 'Blocked'},
    'wo-100253': {},
    'wo-100254': {Schedule: 'Warning', Tooling: 'Warning'},
    'wo-100255': {Quality: 'Warning', Machine: 'Warning'},
    'wo-100256': {},
  };

  return createBaseWorkOrders().flatMap((workOrder) =>
    readinessCategories.map((category, index) => {
      const status: WorkOrderReadinessCheckStatus = overrides[workOrder.id]?.[category] ?? 'Pass';
      return {
        id: `${workOrder.id}-check-${category}`,
        workOrderId: workOrder.id,
        category,
        status,
        description: `${category} readiness review`,
        details:
          status === 'Blocked'
            ? `${category} issue must be resolved before dispatch.`
            : status === 'Warning'
              ? `${category} needs planner attention before release.`
              : `${category} check is clear for execution.`,
        owner: index % 2 === 0 ? 'Planner Team' : 'Area Owner',
        lastCheckedAt: '2026-05-13T15:45:00.000Z',
      };
    }),
  );
}

function createExceptions(): WorkOrderException[] {
  return [
    {
      id: 'exc-100245-1',
      workOrderId: 'wo-100245',
      severity: 'Warning',
      type: 'ChangeoverDelay',
      reason: 'Previous WO overrun is delaying line clearance by 1h 20m.',
      suggestedAction: 'Confirm updated completion and resequence crew break coverage.',
      owner: 'Danilo Brooks',
      ageMinutes: 120,
      createdAt: '2026-05-13T15:00:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100245-2',
      workOrderId: 'wo-100245',
      severity: 'Info',
      type: 'WarehouseStagingIssue',
      reason: 'One pallet still in transit from staging zone B.',
      suggestedAction: 'Track the final pallet move before step 4 pack-out.',
      owner: 'Warehouse Lead',
      ageMinutes: 45,
      createdAt: '2026-05-13T16:15:00.000Z',
      status: 'Acknowledged' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100246-1',
      workOrderId: 'wo-100246',
      severity: 'Blocker',
      type: 'MaterialShortage',
      reason: 'Component COMP-1001 has partial availability only.',
      suggestedAction: 'Escalate supplier expedite and review substitute lot.',
      owner: 'Chris Klopp',
      ageMinutes: 240,
      createdAt: '2026-05-13T13:00:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100246-2',
      workOrderId: 'wo-100246',
      severity: 'Blocker',
      type: 'QualityHold',
      reason: 'Incoming additive lot is on quality hold.',
      suggestedAction: 'Request quality disposition or release alternate lot.',
      owner: 'QA Lead',
      ageMinutes: 210,
      createdAt: '2026-05-13T13:30:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100249-1',
      workOrderId: 'wo-100249',
      severity: 'Warning',
      type: 'MissingDocumentation',
      reason: 'Packaging instruction rev 8 has not been attached.',
      suggestedAction: 'Publish document revision before release.',
      owner: 'James Lee',
      ageMinutes: 180,
      createdAt: '2026-05-13T14:00:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100251-1',
      workOrderId: 'wo-100251',
      severity: 'Warning',
      type: 'LateOrder',
      reason: 'Actual run rate is below plan and due time is inside 24h.',
      suggestedAction: 'Add overtime support or rebalance quantity to Line 20.',
      owner: 'Maria Santos',
      ageMinutes: 95,
      createdAt: '2026-05-13T15:25:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100252-1',
      workOrderId: 'wo-100252',
      severity: 'Blocker',
      type: 'MaterialBlocked',
      reason: 'Batch release is frozen pending nonconformance review.',
      suggestedAction: 'Escalate disposition review with QA and warehouse.',
      owner: 'Chris Klopp',
      ageMinutes: 140,
      createdAt: '2026-05-13T14:40:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100252-2',
      workOrderId: 'wo-100252',
      severity: 'Warning',
      type: 'ScheduleConflict',
      reason: 'Line 20 sterile window is already reserved for a higher priority WO.',
      suggestedAction: 'Reassign to next open sterile campaign or move due date.',
      owner: 'Scheduler',
      ageMinutes: 75,
      createdAt: '2026-05-13T15:45:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100254-1',
      workOrderId: 'wo-100254',
      severity: 'Warning',
      type: 'ChangeoverDelay',
      reason: 'Specialty line setup exceeded target by 35 minutes.',
      suggestedAction: 'Review tooling handoff and adjust next slot.',
      owner: 'Lena Ortiz',
      ageMinutes: 60,
      createdAt: '2026-05-13T16:00:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100255-1',
      workOrderId: 'wo-100255',
      severity: 'Blocker',
      type: 'ExecutionInterruption',
      reason: 'Process interruption triggered after repeated weight variation.',
      suggestedAction: 'Hold batch and complete process capability review.',
      owner: 'Lena Ortiz',
      ageMinutes: 300,
      createdAt: '2026-05-13T12:00:00.000Z',
      status: 'Open' as WorkOrderExceptionStatus,
    },
    {
      id: 'exc-100248-1',
      workOrderId: 'wo-100248',
      severity: 'Info',
      type: 'QuantityDiscrepancy',
      reason: 'Minor count delta was reconciled during close-out.',
      suggestedAction: 'No action required.',
      owner: 'Maria Santos',
      ageMinutes: 720,
      createdAt: '2026-05-12T17:30:00.000Z',
      status: 'Resolved' as WorkOrderExceptionStatus,
    },
  ];
}

function createOperations(): WorkOrderOperation[] {
  const selectedOperations: WorkOrderOperation[] = [
    {
      id: 'op-100245-10',
      workOrderId: 'wo-100245',
      operationNumber: '10',
      operationName: 'Dispensing',
      status: 'Completed',
      machine: 'DSP-10-01',
      operator: 'John Davis',
      plannedQuantity: 32000,
      actualQuantity: 18500,
      plannedTimeHours: 2.2,
      actualTimeHours: 2.1,
      startTime: '2026-05-13T08:00:00.000Z',
      endTime: '2026-05-13T10:06:00.000Z',
      progressPercent: 100,
    },
    {
      id: 'op-100245-20',
      workOrderId: 'wo-100245',
      operationNumber: '20',
      operationName: 'Forming',
      status: 'InProgress',
      machine: 'MCH-10-02',
      operator: 'John Davis',
      plannedQuantity: 32000,
      actualQuantity: 18500,
      plannedTimeHours: 8,
      actualTimeHours: 4.75,
      startTime: '2026-05-13T10:10:00.000Z',
      endTime: null,
      progressPercent: 60,
    },
    {
      id: 'op-100245-30',
      workOrderId: 'wo-100245',
      operationNumber: '30',
      operationName: 'Inspection',
      status: 'NotStarted',
      machine: 'Q-10-INS',
      operator: 'QA Team',
      plannedQuantity: 32000,
      actualQuantity: 0,
      plannedTimeHours: 1.5,
      actualTimeHours: 0,
      startTime: null,
      endTime: null,
      progressPercent: 0,
    },
    {
      id: 'op-100245-40',
      workOrderId: 'wo-100245',
      operationNumber: '40',
      operationName: 'Cartoning',
      status: 'NotStarted',
      machine: 'PK-10-04',
      operator: 'Packaging Team',
      plannedQuantity: 32000,
      actualQuantity: 0,
      plannedTimeHours: 2,
      actualTimeHours: 0,
      startTime: null,
      endTime: null,
      progressPercent: 0,
    },
    {
      id: 'op-100245-50',
      workOrderId: 'wo-100245',
      operationNumber: '50',
      operationName: 'Palletize',
      status: 'NotStarted',
      machine: 'PAL-10-05',
      operator: 'Warehouse Team',
      plannedQuantity: 32000,
      actualQuantity: 0,
      plannedTimeHours: 1,
      actualTimeHours: 0,
      startTime: null,
      endTime: null,
      progressPercent: 0,
    },
  ];

  const genericOrders = createBaseWorkOrders()
    .filter((workOrder) => workOrder.id !== 'wo-100245')
    .flatMap((workOrder) => [
      {
        id: `${workOrder.id}-op10`,
        workOrderId: workOrder.id,
        operationNumber: '10',
        operationName: 'Prep',
        status: (workOrder.status === 'Completed' ? 'Completed' : workOrder.status === 'Running' ? 'InProgress' : 'NotStarted') as WorkOrderOperationStatus,
        machine: `${workOrder.assignedLineName.replace(' ', '')}-PREP`,
        operator: workOrder.owner,
        plannedQuantity: workOrder.quantityRequired,
        actualQuantity: Math.min(workOrder.quantityProduced, Math.round(workOrder.quantityRequired * 0.4)),
        plannedTimeHours: 2,
        actualTimeHours: workOrder.quantityProduced > 0 ? 1.1 : 0,
        startTime: workOrder.actualStartDate,
        endTime: workOrder.status === 'Completed' ? workOrder.actualEndDate : null,
        progressPercent: workOrder.quantityProduced > 0 ? 100 : 0,
      },
      {
        id: `${workOrder.id}-op20`,
        workOrderId: workOrder.id,
        operationNumber: '20',
        operationName: 'Main Run',
        status: (
          workOrder.status === 'Completed'
            ? 'Completed'
            : workOrder.status === 'Running'
              ? 'InProgress'
              : workOrder.status === 'Paused'
                ? 'Paused'
                : workOrder.status === 'Blocked'
                  ? 'Blocked'
                  : 'NotStarted'
        ) as WorkOrderOperationStatus,
        machine: `${workOrder.assignedLineName.replace(' ', '')}-MAIN`,
        operator: workOrder.owner,
        plannedQuantity: workOrder.quantityRequired,
        actualQuantity: workOrder.quantityProduced,
        plannedTimeHours: 6,
        actualTimeHours: workOrder.quantityProduced > 0 ? 2.5 : 0,
        startTime: workOrder.actualStartDate,
        endTime: null,
        progressPercent: workOrder.quantityRequired > 0 ? Math.min(100, Math.round((workOrder.quantityProduced / workOrder.quantityRequired) * 100)) : 0,
      },
      {
        id: `${workOrder.id}-op30`,
        workOrderId: workOrder.id,
        operationNumber: '30',
        operationName: 'Pack-Out',
        status: (workOrder.status === 'Completed' ? 'Completed' : 'NotStarted') as WorkOrderOperationStatus,
        machine: `${workOrder.assignedLineName.replace(' ', '')}-PACK`,
        operator: 'Packaging Team',
        plannedQuantity: workOrder.quantityRequired,
        actualQuantity: workOrder.status === 'Completed' ? workOrder.quantityRequired : 0,
        plannedTimeHours: 1.5,
        actualTimeHours: workOrder.status === 'Completed' ? 1.3 : 0,
        startTime: workOrder.status === 'Completed' ? workOrder.actualStartDate : null,
        endTime: workOrder.status === 'Completed' ? workOrder.actualEndDate : null,
        progressPercent: workOrder.status === 'Completed' ? 100 : 0,
      },
    ]);

  return [...selectedOperations, ...genericOrders];
}

function createAuditEvents(): WorkOrderAuditEvent[] {
  return [
    {
      id: 'audit-1',
      workOrderId: 'wo-100245',
      timestamp: '2026-05-13T16:40:00.000Z',
      user: 'Danilo Brooks',
      eventType: 'PriorityConfirmed',
      previousValue: 'High',
      newValue: 'High',
      comment: 'Customer shipment remains protected.',
    },
    {
      id: 'audit-2',
      workOrderId: 'wo-100245',
      timestamp: '2026-05-13T15:20:00.000Z',
      user: 'John Davis',
      eventType: 'OperationStarted',
      previousValue: 'Operation 10',
      newValue: 'Operation 20',
      comment: 'Line moved into forming after clearance.',
    },
    {
      id: 'audit-3',
      workOrderId: 'wo-100246',
      timestamp: '2026-05-13T14:05:00.000Z',
      user: 'Chris Klopp',
      eventType: 'BlockerRaised',
      previousValue: 'Warning',
      newValue: 'Blocked',
      comment: 'Shortage and QA hold escalated together.',
    },
  ];
}

function createMaterials(): WorkOrderMaterialItem[] {
  return [
    {id: 'mat-100245-1', workOrderId: 'wo-100245', component: 'COMP-1001 Resin', requiredQuantity: 32000, availableQuantity: 32000, status: 'Available', issue: 'No issue'},
    {id: 'mat-100245-2', workOrderId: 'wo-100245', component: 'COMP-2045 Tube Sleeve', requiredQuantity: 32000, availableQuantity: 32000, status: 'Available', issue: 'No issue'},
    {id: 'mat-100245-3', workOrderId: 'wo-100245', component: 'COMP-3301 Carton', requiredQuantity: 1600, availableQuantity: 1200, status: 'Partial', issue: 'Final pallet in transfer from staging zone B'},
    {id: 'mat-100246-1', workOrderId: 'wo-100246', component: 'COMP-1001 Additive Resin', requiredQuantity: 18000, availableQuantity: 7200, status: 'Shortage', issue: 'Supplier backorder'},
    {id: 'mat-100246-2', workOrderId: 'wo-100246', component: 'COMP-4100 Sterile Cap', requiredQuantity: 18000, availableQuantity: 18000, status: 'Available', issue: 'No issue'},
    {id: 'mat-100249-1', workOrderId: 'wo-100249', component: 'COMP-5200 Specialty Carton', requiredQuantity: 5200, availableQuantity: 5200, status: 'Available', issue: 'Awaiting pack instructions'},
    {id: 'mat-100252-1', workOrderId: 'wo-100252', component: 'COMP-6200 Additive Lot', requiredQuantity: 12000, availableQuantity: 0, status: 'Blocked', issue: 'Blocked by nonconformance review'},
  ];
}

export function createWorkOrdersDemoBundle(): WorkOrdersBundle {
  const baseWorkOrders = createBaseWorkOrders();
  const readinessChecks = createReadinessChecks();
  const exceptions = createExceptions();
  const workOrders = hydrateWorkOrders(baseWorkOrders, readinessChecks, exceptions, REFERENCE_NOW);

  return {
    siteName: 'Sandy',
    siteLabel: 'San Diego Site',
    productionLines: lineLookup,
    workOrders,
    readinessChecks,
    exceptions,
    operations: createOperations(),
    auditEvents: createAuditEvents(),
    materials: createMaterials(),
    selectedWorkOrderId: 'wo-100245',
    referenceNow: REFERENCE_NOW,
  };
}
