import type {
  DailyProductionAuditEvent,
  DailyProductionStatusDemoBundle,
  DowntimeEvent,
  ProductionLineStatus,
  ProductionNote,
  DailyProductionReport,
} from './types';
import {createDailyProductionAuditEvent, enrichProductionLines} from './utils';

const reportId = 'daily-production-status-report-may-13-2026';
const baseUpdatedAt = '2026-05-13T15:15:00.000Z';

const report: DailyProductionReport = {
  id: reportId,
  reportDate: '2026-05-13',
  site: 'Sandy (San Diego Site)',
  shift: 'Day Shift (07:00 - 15:00)',
  planner: 'Danilo Brooks',
  supervisor: 'Maddison Brooks',
  reportStatus: 'Draft',
  lastUpdatedAt: baseUpdatedAt,
  lastSavedAt: null,
  submittedAt: null,
  notes: 'Daily front-end demo report for Production Planning and Operations review.',
};

const productionLineStatuses: ProductionLineStatus[] = enrichProductionLines([
  {
    id: 'line-status-10',
    reportId,
    lineId: 'line-10',
    lineName: 'Line 10',
    lineDescription: 'Tube Fill & Seal 1',
    status: 'Running',
    productCode: 'FG-1001',
    productDescription: 'Standard Tube A',
    campaign: 'FG-1001 Standard Tube A',
    planUnits: 220000,
    actualUnits: 210500,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 91.2,
    qualityYieldPercent: 98.1,
    ordersOnTimePercent: 92,
    downtimeMinutes: 28,
    reasonForGap: 'Short stoppage - labeler jam',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-20',
    reportId,
    lineId: 'line-20',
    lineName: 'Line 20',
    lineDescription: 'Tube Fill & Seal 2',
    status: 'Running',
    productCode: 'FG-2001',
    productDescription: 'Additive Tube',
    campaign: 'FG-2001 Additive Tube',
    planUnits: 180000,
    actualUnits: 162300,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 88.4,
    qualityYieldPercent: 97.3,
    ordersOnTimePercent: 85,
    downtimeMinutes: 46,
    reasonForGap: 'Material gap - cap component',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-30',
    reportId,
    lineId: 'line-30',
    lineName: 'Line 30',
    lineDescription: 'Tube Fill & Seal 3',
    status: 'Stopped',
    productCode: 'FG-1002',
    productDescription: 'Standard Tube B',
    campaign: 'FG-1002 Standard Tube B',
    planUnits: 160000,
    actualUnits: 120400,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 62.1,
    qualityYieldPercent: 96.5,
    ordersOnTimePercent: 70,
    downtimeMinutes: 95,
    reasonForGap: 'Machine down - jam in sealer',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-40',
    reportId,
    lineId: 'line-40',
    lineName: 'Line 40',
    lineDescription: 'Assembly Line 1',
    status: 'Running',
    productCode: 'FG-3001',
    productDescription: 'Gel Product',
    campaign: 'FG-3001 Gel Product',
    planUnits: 150000,
    actualUnits: 148200,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 93.6,
    qualityYieldPercent: 99.2,
    ordersOnTimePercent: 95,
    downtimeMinutes: 18,
    reasonForGap: 'Normal operations',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-50',
    reportId,
    lineId: 'line-50',
    lineName: 'Line 50',
    lineDescription: 'Assembly Line 2',
    status: 'Running',
    productCode: 'FG-4001',
    productDescription: 'Specialty Pack',
    campaign: 'FG-4001 Specialty Pack',
    planUnits: 120000,
    actualUnits: 115600,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 90.7,
    qualityYieldPercent: 97.6,
    ordersOnTimePercent: 90,
    downtimeMinutes: 22,
    reasonForGap: 'Changeover adjustment',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-60',
    reportId,
    lineId: 'line-60',
    lineName: 'Line 60',
    lineDescription: 'Packaging Line 1',
    status: 'Running',
    productCode: 'FG-5001',
    productDescription: 'Low Volume Product',
    campaign: 'FG-5001 Low Volume Product',
    planUnits: 80000,
    actualUnits: 78900,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 94.1,
    qualityYieldPercent: 98.7,
    ordersOnTimePercent: 96,
    downtimeMinutes: 15,
    reasonForGap: 'Normal operations',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-70',
    reportId,
    lineId: 'line-70',
    lineName: 'Line 70',
    lineDescription: 'Packaging Line 2',
    status: 'Idle',
    productCode: 'N/A',
    productDescription: 'N/A',
    campaign: 'No campaign',
    planUnits: 0,
    actualUnits: 0,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: null,
    qualityYieldPercent: null,
    ordersOnTimePercent: null,
    downtimeMinutes: 0,
    reasonForGap: 'No production planned',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
  {
    id: 'line-status-80',
    reportId,
    lineId: 'line-80',
    lineName: 'Line 80',
    lineDescription: 'Manual / Rework',
    status: 'Running',
    productCode: 'REWORK',
    productDescription: 'Rework / Repack',
    campaign: 'Rework / Repack',
    planUnits: 18500,
    actualUnits: 19400,
    achievementPercent: null,
    varianceUnits: 0,
    oeePercent: 85.2,
    qualityYieldPercent: 95.1,
    ordersOnTimePercent: 80,
    downtimeMinutes: 35,
    reasonForGap: 'Rework from Line 30',
    supervisor: 'Maddison Brooks',
    lastUpdatedAt: baseUpdatedAt,
  },
]);

const downtimeEvents: DowntimeEvent[] = [
  {
    id: 'dt-30',
    reportId,
    lineId: 'line-30',
    lineName: 'Line 30',
    reason: 'Machine down - jam in sealer',
    startTime: '2026-05-13T08:15:00.000Z',
    endTime: '2026-05-13T09:50:00.000Z',
    durationMinutes: 95,
    impactUnits: 39600,
    category: 'Machine',
    severity: 'Critical',
    comment: 'Maintenance troubleshooting in progress.',
  },
  {
    id: 'dt-20',
    reportId,
    lineId: 'line-20',
    lineName: 'Line 20',
    reason: 'Material gap - cap component',
    startTime: '2026-05-13T09:20:00.000Z',
    endTime: '2026-05-13T10:06:00.000Z',
    durationMinutes: 46,
    impactUnits: 17700,
    category: 'Material',
    severity: 'Warning',
    comment: 'Shortage escalated to material team.',
  },
  {
    id: 'dt-80',
    reportId,
    lineId: 'line-80',
    lineName: 'Line 80',
    reason: 'Rework processing',
    startTime: '2026-05-13T11:10:00.000Z',
    endTime: '2026-05-13T11:45:00.000Z',
    durationMinutes: 35,
    impactUnits: null,
    category: 'Rework',
    severity: 'Info',
    comment: 'Rework lane repacked material from Line 30.',
  },
  {
    id: 'dt-10',
    reportId,
    lineId: 'line-10',
    lineName: 'Line 10',
    reason: 'Labeler jam',
    startTime: '2026-05-13T13:05:00.000Z',
    endTime: '2026-05-13T13:33:00.000Z',
    durationMinutes: 28,
    impactUnits: 9500,
    category: 'Machine',
    severity: 'Warning',
    comment: 'Recovered after short stop.',
  },
  {
    id: 'dt-50',
    reportId,
    lineId: 'line-50',
    lineName: 'Line 50',
    reason: 'Changeover adjustment',
    startTime: '2026-05-13T14:00:00.000Z',
    endTime: '2026-05-13T14:22:00.000Z',
    durationMinutes: 22,
    impactUnits: 4400,
    category: 'Changeover',
    severity: 'Info',
    comment: 'Normal transition between campaigns.',
  },
];

const notes: ProductionNote[] = [
  {
    id: 'note-1',
    reportId,
    category: 'Downtime',
    message: 'Line 30 is facing machine downtime. Maintenance team is working on it.',
    severity: 'Critical',
    createdBy: 'Danilo Brooks',
    createdAt: baseUpdatedAt,
  },
  {
    id: 'note-2',
    reportId,
    category: 'Material',
    message: 'Material cap component shortage affected Line 20.',
    severity: 'Warning',
    createdBy: 'Danilo Brooks',
    createdAt: baseUpdatedAt,
  },
  {
    id: 'note-3',
    reportId,
    category: 'Production',
    message: 'Rework volume is higher due to issues on Line 30.',
    severity: 'Warning',
    createdBy: 'Maddison Brooks',
    createdAt: baseUpdatedAt,
  },
  {
    id: 'note-4',
    reportId,
    category: 'Planning',
    message: 'Overall plan achievement is above target.',
    severity: 'Info',
    createdBy: 'BLU.AI',
    createdAt: baseUpdatedAt,
  },
  {
    id: 'note-5',
    reportId,
    category: 'Quality',
    message: 'Quality yield is within acceptable range.',
    severity: 'Info',
    createdBy: 'BLU.AI',
    createdAt: baseUpdatedAt,
  },
  {
    id: 'note-6',
    reportId,
    category: 'Safety',
    message: 'No safety incidents today.',
    severity: 'Info',
    createdBy: 'BLU.AI',
    createdAt: baseUpdatedAt,
  },
];

const auditEvents: DailyProductionAuditEvent[] = [
  createDailyProductionAuditEvent({
    reportId,
    user: 'Danilo Brooks',
    eventType: 'ReportInitialized',
    previousValue: 'N/A',
    newValue: 'Draft demo report loaded',
    comment: 'Initial front-end mock bundle created for review.',
    timestamp: '2026-05-13T15:05:00.000Z',
  }),
];

export function createDailyProductionStatusDemoBundle(): DailyProductionStatusDemoBundle {
  return {
    report: structuredClone(report),
    productionLineStatuses: structuredClone(productionLineStatuses),
    downtimeEvents: structuredClone(downtimeEvents),
    notes: structuredClone(notes),
    auditEvents: structuredClone(auditEvents),
    lastRefreshAt: baseUpdatedAt,
    autoRefreshEnabled: true,
    safetyIncidents: 0,
  };
}
