import type {LongTermPlanningAiProposal} from './aiProposalTypes';

export function generateLongTermAiProposalMock(): LongTermPlanningAiProposal {
  return {
    id: 'AILTP-2026-05-001',
    site: 'Sandy / San Diego Site',
    planningHorizonStart: '2026-06',
    planningHorizonEnd: '2027-05',
    sourceForecastVersion: 'Forecast-v2026.05',
    generatedAt: new Date().toISOString(),
    generatedBy: 'AI Forecast & Capacity Assistant',
    confidencePercent: 84,
    status: 'Draft',
    summary: {
      forecastRowsChecked: 384,
      productsWithForecastIssues: 6,
      capacityOverloadedMonths: 5,
      recommendedCommitmentPercent: 92,
      uncoveredDemandUnits: 148000,
      highRiskProducts: 4,
      materialRiskItems: 7,
      plannerActionsRequired: 9,
    },
    forecastQualityIssues: [
      {
        id: 'fqi-001',
        productCode: 'FG-1001',
        productDescription: 'Tube Assembly Standard',
        month: '2026-06',
        issueType: 'DemandSpike',
        currentForecast: 145000,
        priorForecast: 119000,
        variancePercent: 21.8,
        severity: 'Warning',
        aiRecommendation: 'Review with Supply Chain before commitment.',
        status: 'Open',
      },
      {
        id: 'fqi-002',
        productCode: 'FG-2001',
        productDescription: 'Packaging Unit B',
        month: '2026-07',
        issueType: 'DemandSpike',
        currentForecast: 92000,
        priorForecast: 73000,
        variancePercent: 26.0,
        severity: 'Warning',
        aiRecommendation: 'Prioritize due to firm customer demand.',
        status: 'Open',
      },
      {
        id: 'fqi-003',
        productCode: 'FG-4001',
        productDescription: 'Specialty Finishing Alpha',
        month: '2026-08',
        issueType: 'MissingProductLineCapability',
        currentForecast: 64000,
        priorForecast: null,
        variancePercent: null,
        severity: 'Blocker',
        aiRecommendation: 'Request master data update before committing full demand.',
        status: 'Open',
      },
      {
        id: 'fqi-004',
        productCode: 'FG-5001',
        productDescription: 'Specialty Finishing Beta',
        month: '2026-09',
        issueType: 'DemandBelowMinimumLotSize',
        currentForecast: 18000,
        priorForecast: 18000,
        variancePercent: 0,
        severity: 'Warning',
        aiRecommendation: 'Round to minimum lot size of 25,000 or defer.',
        status: 'Open',
      },
      {
        id: 'fqi-005',
        productCode: 'FG-3001',
        productDescription: 'Packaging Unit C',
        month: '2026-10',
        issueType: 'DuplicateForecastRow',
        currentForecast: 110000,
        priorForecast: 110000,
        variancePercent: 0,
        severity: 'Blocker',
        aiRecommendation: 'Remove duplicate before release.',
        status: 'Open',
      },
    ],
    demandCapacityRows: [
      {
        id: 'dcr-001',
        productCode: 'FG-1001',
        productDescription: 'Tube Assembly Standard',
        month: '2026-06',
        forecastDemand: 145000,
        requiredHours: 85.3,
        eligibleLine: 'Line 10',
        availableHours: 92,
        utilizationPercent: 92.7,
        capacityStatus: 'Warning',
        constraint: null,
        aiRecommendation: 'Commit full demand but monitor Line 10 utilization.',
      },
      {
        id: 'dcr-002',
        productCode: 'FG-2001',
        productDescription: 'Packaging Unit B',
        month: '2026-07',
        forecastDemand: 92000,
        requiredHours: 76.7,
        eligibleLine: 'Line 20',
        availableHours: 70,
        utilizationPercent: 109.5,
        capacityStatus: 'Overloaded',
        constraint: 'Line 20 overloaded',
        aiRecommendation: 'Move 15,000 units to Line 30 or add overtime.',
      },
      {
        id: 'dcr-003',
        productCode: 'FG-4001',
        productDescription: 'Specialty Finishing Alpha',
        month: '2026-08',
        forecastDemand: 64000,
        requiredHours: null,
        eligibleLine: 'Line 20',
        availableHours: 88,
        utilizationPercent: null,
        capacityStatus: 'MissingData',
        constraint: 'Missing production rate',
        aiRecommendation: 'Do not approve until production rate is maintained.',
      },
      {
        id: 'dcr-004',
        productCode: 'FG-5001',
        productDescription: 'Specialty Finishing Beta',
        month: '2026-09',
        forecastDemand: 18000,
        requiredHours: 24,
        eligibleLine: 'Line 30',
        availableHours: 60,
        utilizationPercent: 40,
        capacityStatus: 'Warning',
        constraint: 'Below minimum lot size',
        aiRecommendation: 'Round to 25,000 or defer.',
      },
    ],
    commitmentRecommendations: [
      {
        id: 'cr-001',
        productCode: 'FG-1001',
        productDescription: 'Tube Assembly Standard',
        month: '2026-06',
        forecastDemand: 145000,
        recommendedCommitment: 145000,
        commitmentPercent: 100,
        uncoveredDemand: 0,
        primaryConstraint: null,
        confidence: 'High',
        plannerDecision: 'Pending',
        aiReasoning: 'Demand is feasible within Line 10 available hours at 92.7% utilization.',
        selected: false,
      },
      {
        id: 'cr-002',
        productCode: 'FG-2001',
        productDescription: 'Packaging Unit B',
        month: '2026-07',
        forecastDemand: 92000,
        recommendedCommitment: 80000,
        commitmentPercent: 87,
        uncoveredDemand: 12000,
        primaryConstraint: 'Capacity on Line 20',
        confidence: 'Medium',
        plannerDecision: 'Pending',
        aiReasoning: 'Line 20 is overloaded. Recommend committing 80,000 and moving remainder to Line 30 or overtime.',
        selected: false,
      },
      {
        id: 'cr-003',
        productCode: 'FG-3001',
        productDescription: 'Packaging Unit C',
        month: '2026-08',
        forecastDemand: 110000,
        recommendedCommitment: 100000,
        commitmentPercent: 91,
        uncoveredDemand: 10000,
        primaryConstraint: 'Material risk',
        confidence: 'Medium',
        plannerDecision: 'Pending',
        aiReasoning: 'Material shortage risk identified for key component. Recommend committing 100,000 pending supply confirmation.',
        selected: false,
      },
      {
        id: 'cr-004',
        productCode: 'FG-4001',
        productDescription: 'Specialty Finishing Alpha',
        month: '2026-08',
        forecastDemand: 64000,
        recommendedCommitment: 0,
        commitmentPercent: 0,
        uncoveredDemand: 64000,
        primaryConstraint: 'Missing production rate',
        confidence: 'Low',
        plannerDecision: 'Pending',
        aiReasoning: 'Cannot commit until production rate master data is resolved for Line 20.',
        selected: false,
      },
      {
        id: 'cr-005',
        productCode: 'FG-5001',
        productDescription: 'Specialty Finishing Beta',
        month: '2026-09',
        forecastDemand: 18000,
        recommendedCommitment: 25000,
        commitmentPercent: 139,
        uncoveredDemand: -7000,
        primaryConstraint: 'Minimum lot size',
        confidence: 'Medium',
        plannerDecision: 'Pending',
        aiReasoning: 'Demand is below minimum lot size of 25,000. AI recommends rounding up to avoid inefficient production run.',
        selected: false,
      },
    ],
    scenarios: [
      {
        id: 'sc-001',
        name: 'Baseline Forecast',
        description: 'Commit 100% of forecast demand regardless of capacity.',
        demandCoveragePercent: 100,
        requiredOvertimeHours: 220,
        overloadedMonths: 5,
        uncoveredDemand: 0,
        inventoryRisk: 'High',
        materialRisk: 'High',
        aiRecommendation: 'Not recommended without capacity actions.',
        selected: false,
      },
      {
        id: 'sc-002',
        name: 'Capacity-Constrained',
        description: 'Commit only what available capacity can support without overtime.',
        demandCoveragePercent: 92,
        requiredOvertimeHours: 0,
        overloadedMonths: 0,
        uncoveredDemand: 148000,
        inventoryRisk: 'Medium',
        materialRisk: 'Medium',
        aiRecommendation: 'Recommended baseline for planner review.',
        selected: true,
      },
      {
        id: 'sc-003',
        name: 'Full Demand with Overtime',
        description: 'Approve full demand and authorize overtime to cover overloaded months.',
        demandCoveragePercent: 100,
        requiredOvertimeHours: 220,
        overloadedMonths: 0,
        uncoveredDemand: 0,
        inventoryRisk: 'Medium',
        materialRisk: 'High',
        aiRecommendation: 'Use only if overtime is approved.',
        selected: false,
      },
      {
        id: 'sc-004',
        name: 'Prioritize Firm Orders',
        description: 'Prioritize firm customer demand over forecast-only demand.',
        demandCoveragePercent: 95,
        requiredOvertimeHours: 80,
        overloadedMonths: 1,
        uncoveredDemand: 90000,
        inventoryRisk: 'Medium',
        materialRisk: 'Medium',
        aiRecommendation: 'Good service-level option.',
        selected: false,
      },
      {
        id: 'sc-005',
        name: 'Conservative Plan',
        description: 'Commit only to highly confident demand with no capacity risk.',
        demandCoveragePercent: 88,
        requiredOvertimeHours: 0,
        overloadedMonths: 0,
        uncoveredDemand: 210000,
        inventoryRisk: 'Low',
        materialRisk: 'Low',
        aiRecommendation: 'Safest operational plan but lower service coverage.',
        selected: false,
      },
    ],
    reasoning: [
      {
        id: 'rsn-001',
        title: 'Forecast Quality',
        category: 'ForecastQuality',
        severity: 'Warning',
        explanation:
          'AI detected demand spikes on FG-1001 (+22%) and FG-2001 (+26%), a duplicate forecast row on FG-3001, and a missing production rate blocker on FG-4001. These should be reviewed before release.',
        affectedProducts: ['FG-1001', 'FG-2001', 'FG-3001', 'FG-4001'],
        affectedMonths: ['2026-06', '2026-07', '2026-08', '2026-10'],
      },
      {
        id: 'rsn-002',
        title: 'Capacity',
        category: 'Capacity',
        severity: 'Warning',
        explanation:
          'Line 20 is overloaded in July because FG-2001 demand requires 76.7 hours against 70 available hours. This results in 109.5% utilization.',
        affectedProducts: ['FG-2001'],
        affectedMonths: ['2026-07'],
      },
      {
        id: 'rsn-003',
        title: 'Commitment',
        category: 'Commitment',
        severity: 'Warning',
        explanation:
          'AI recommends committing 80,000 of 92,000 units for FG-2001 unless overtime or alternate line capacity is approved.',
        affectedProducts: ['FG-2001'],
        affectedMonths: ['2026-07'],
      },
      {
        id: 'rsn-004',
        title: 'Product Rules',
        category: 'ProductRules',
        severity: 'Warning',
        explanation:
          'FG-5001 demand of 18,000 is below minimum lot size of 25,000. AI recommends either rounding to 25,000 or deferring.',
        affectedProducts: ['FG-5001'],
        affectedMonths: ['2026-09'],
      },
      {
        id: 'rsn-005',
        title: 'Scenario',
        category: 'Scenario',
        severity: 'Info',
        explanation:
          'Capacity-Constrained scenario is recommended because it removes overloads without requiring overtime, covering 92% of demand.',
        affectedProducts: [],
        affectedMonths: [],
      },
      {
        id: 'rsn-006',
        title: 'Risks',
        category: 'Risk',
        severity: 'Blocker',
        explanation:
          'FG-4001 cannot be committed until missing production rate data is resolved. This is a blocking issue for August planning.',
        affectedProducts: ['FG-4001'],
        affectedMonths: ['2026-08'],
      },
    ],
    risks: [
      {
        id: 'rsk-001',
        riskType: 'CapacityOverload',
        severity: 'Warning',
        productCode: 'FG-2001',
        productDescription: 'Packaging Unit B',
        month: '2026-07',
        impact: 'Line 20 overloaded by 9.5% — 12,000 units uncovered.',
        owner: 'Capacity Planner',
        recommendedAction: 'Move 15,000 units to Line 30 or approve overtime.',
        status: 'Open',
      },
      {
        id: 'rsk-002',
        riskType: 'MissingProductionRate',
        severity: 'Blocker',
        productCode: 'FG-4001',
        productDescription: 'Specialty Finishing Alpha',
        month: '2026-08',
        impact: 'Cannot calculate required hours or commit any demand.',
        owner: 'Manufacturing Engineering',
        recommendedAction: 'Update production rate on Line 20 master data.',
        status: 'Open',
      },
      {
        id: 'rsk-003',
        riskType: 'MaterialShortageRisk',
        severity: 'Warning',
        productCode: 'FG-3001',
        productDescription: 'Packaging Unit C',
        month: '2026-08',
        impact: 'Key component supply at risk — up to 10,000 units may be uncovered.',
        owner: 'Supply Chain',
        recommendedAction: 'Confirm supply availability before committing 110,000 units.',
        status: 'Open',
      },
      {
        id: 'rsk-004',
        riskType: 'DemandSpike',
        severity: 'Warning',
        productCode: 'FG-1001',
        productDescription: 'Tube Assembly Standard',
        month: '2026-06',
        impact: 'Demand spike of +22% vs prior forecast — may indicate data error.',
        owner: 'Demand Planner',
        recommendedAction: 'Validate with Supply Chain before final commitment.',
        status: 'Open',
      },
      {
        id: 'rsk-005',
        riskType: 'DuplicateForecastRow',
        severity: 'Blocker',
        productCode: 'FG-3001',
        productDescription: 'Packaging Unit C',
        month: '2026-10',
        impact: 'Duplicate forecast row will double-count demand in MPS release.',
        owner: 'Demand Planner',
        recommendedAction: 'Remove duplicate row before release.',
        status: 'Open',
      },
      {
        id: 'rsk-006',
        riskType: 'MinimumLotSizeIssue',
        severity: 'Warning',
        productCode: 'FG-5001',
        productDescription: 'Specialty Finishing Beta',
        month: '2026-09',
        impact: 'Demand of 18,000 is below minimum lot size of 25,000.',
        owner: 'Production Planner',
        recommendedAction: 'Round to 25,000 or defer to next month.',
        status: 'Open',
      },
      {
        id: 'rsk-007',
        riskType: 'SupplierTestCapacityLoss',
        severity: 'Info',
        productCode: 'FG-1001',
        productDescription: 'Tube Assembly Standard',
        month: '2026-08',
        impact: 'Supplier test capacity reduced by 15% during August quality audit.',
        owner: 'SQA',
        recommendedAction: 'Confirm supplier test schedule and buffer stock.',
        status: 'Open',
      },
      {
        id: 'rsk-008',
        riskType: 'MaintenanceCapacityLoss',
        severity: 'Info',
        productCode: 'FG-2001',
        productDescription: 'Packaging Unit B',
        month: '2026-09',
        impact: 'Line 20 scheduled for 8-hour maintenance window in September.',
        owner: 'Maintenance',
        recommendedAction: 'Confirm maintenance dates and adjust line hours.',
        status: 'Open',
      },
      {
        id: 'rsk-009',
        riskType: 'LaborConstraint',
        severity: 'Info',
        productCode: 'FG-3001',
        productDescription: 'Packaging Unit C',
        month: '2026-10',
        impact: 'Headcount reduction planned — may affect Line 30 throughput.',
        owner: 'Operations',
        recommendedAction: 'Review staffing plan before confirming October commitments.',
        status: 'Open',
      },
    ],
    auditEvents: [],
  };
}
