export type BdPlantCountry = 'US' | 'MX';
export type BdPlantKind = 'manufacturing' | 'distribution' | 'campus' | 'pharma';

export type BdPlantSite = {
  id: string;
  name: string;
  shortName: string;
  country: BdPlantCountry;
  kind: BdPlantKind;
  address: string;
  city: string;
  focus: string;
  lat: number;
  lng: number;
};

/** BD manufacturing / DC network used by the 4PL live map (approx. site centroids). */
export const BD_PLANT_SITES: BdPlantSite[] = [
  {
    id: 'us-canaan',
    name: 'Becton Dickinson & Co — Canaan',
    shortName: 'Canaan CT',
    country: 'US',
    kind: 'manufacturing',
    address: '7 Grace Way, Canaan, CT 06018, USA',
    city: 'Canaan, CT',
    focus: 'Syringes & needles (legacy flagship)',
    lat: 41.9612,
    lng: -73.3293,
  },
  {
    id: 'us-columbus-west',
    name: 'Columbus West (Nebraska)',
    shortName: 'Columbus West',
    country: 'US',
    kind: 'manufacturing',
    address: '1852 10th Ave, Columbus, NE 68601, USA',
    city: 'Columbus, NE',
    focus: 'High-scale syringes & delivery systems',
    lat: 41.4298,
    lng: -97.3684,
  },
  {
    id: 'us-columbus-pharma',
    name: 'BD Medical — Pharmaceutical Systems',
    shortName: 'Columbus Pharma',
    country: 'US',
    kind: 'pharma',
    address: '920 E 19th St, Columbus, NE 68601, USA',
    city: 'Columbus, NE',
    focus: 'Advanced pharmaceutical systems',
    lat: 41.4331,
    lng: -97.3502,
  },
  {
    id: 'us-sandy',
    name: 'Becton Dickinson — Sandy',
    shortName: 'Sandy UT',
    country: 'US',
    kind: 'manufacturing',
    address: '9450 S State St, Sandy, UT 84070, USA',
    city: 'Sandy, UT',
    focus: 'IV catheters & surgical devices',
    lat: 40.5724,
    lng: -111.8601,
  },
  {
    id: 'us-elpaso',
    name: 'Becton Dickinson — El Paso',
    shortName: 'El Paso TX',
    country: 'US',
    kind: 'manufacturing',
    address: '1550 Northwestern Dr, El Paso, TX 79912, USA',
    city: 'El Paso, TX',
    focus: 'Infusion / CareFusion logistics hub',
    lat: 31.8615,
    lng: -106.5459,
  },
  {
    id: 'us-franklin',
    name: 'BD Franklin Lakes Campus',
    shortName: 'Franklin Lakes',
    country: 'US',
    kind: 'campus',
    address: '1 Becton Drive, Franklin Lakes, NJ 07417, USA',
    city: 'Franklin Lakes, NJ',
    focus: 'Global HQ & research campus',
    lat: 41.0167,
    lng: -74.2058,
  },
  {
    id: 'mx-cuautitlan',
    name: 'Cuautitlan Izcalli — Manufacturing',
    shortName: 'Cuautitlan',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Autopista Querétaro - Mexico Km 37.4, Industrial Cuamatla, 54730 Cuautitlan Izcalli, Mex., Mexico',
    city: 'Cuautitlan Izcalli',
    focus: 'Disposable syringes & needles',
    lat: 19.6436,
    lng: -99.2118,
  },
  {
    id: 'mx-tepotzotlan',
    name: 'Tepotzotlan — Primary DC',
    shortName: 'Tepotzotlan DC',
    country: 'MX',
    kind: 'distribution',
    address: 'Carretera Tepotzotlan La Aurora Km 1 S/N, Col. Axotlán, C.P. 54716 Cuautitlan Izcalli, Edo. Mex., Mexico',
    city: 'Tepotzotlan',
    focus: 'Primary distribution hub',
    lat: 19.7142,
    lng: -99.2219,
  },
  {
    id: 'mx-tijuana-1',
    name: 'Tijuana — Plant 1',
    shortName: 'Tijuana P1',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Calle 12 Norte No. 120, Ciudad Industrial Nueva Tijuana, C.P. 22444 Tijuana, B.C., Mexico',
    city: 'Tijuana, BC',
    focus: 'Infusion & medication management',
    lat: 32.5149,
    lng: -116.9701,
  },
  {
    id: 'mx-tijuana-2',
    name: 'Tijuana — Plant 2 (Alaris / CareFusion)',
    shortName: 'Tijuana Alaris',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Av. Produccion No. 20, Parque Industrial Internacional Tijuana, C.P. 22424 Tijuana, B.C., Mexico',
    city: 'Tijuana, BC',
    focus: 'Alaris infusion pumps',
    lat: 32.5052,
    lng: -116.9504,
  },
  {
    id: 'mx-nogales-norte',
    name: 'Nogales Norte',
    shortName: 'Nogales Norte',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Av. De los Anhelos No. 35, Parque Industrial Nuevo Nogales, C.P. 84094 Nogales, Son., Mexico',
    city: 'Nogales, Son.',
    focus: 'Medical components',
    lat: 31.3085,
    lng: -110.9421,
  },
  {
    id: 'mx-nogales-sur',
    name: 'Nogales Sur',
    shortName: 'Nogales Sur',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Carretera Internacional Km 6.5, Parque Industrial San Carlos, C.P. 84090 Nogales, Son., Mexico',
    city: 'Nogales, Son.',
    focus: 'Sterile assembly',
    lat: 31.2804,
    lng: -110.9452,
  },
  {
    id: 'mx-hermosillo',
    name: 'Hermosillo',
    shortName: 'Hermosillo',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Calle De la Plata S/N, Parque Industrial Hermosillo, C.P. 83299 Hermosillo, Son., Mexico',
    city: 'Hermosillo, Son.',
    focus: 'Collection & diagnostics',
    lat: 29.0892,
    lng: -110.9613,
  },
  {
    id: 'mx-juarez',
    name: 'Ciudad Juarez',
    shortName: 'Ciudad Juarez',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Av. Intermex No. 1651, Parque Industrial Intermex, C.P. 32690 Ciudad Juarez, Chih., Mexico',
    city: 'Ciudad Juarez',
    focus: 'Advanced infusion devices',
    lat: 31.6904,
    lng: -106.4245,
  },
  {
    id: 'mx-reynosa',
    name: 'Reynosa',
    shortName: 'Reynosa',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Av. Industrial Falcon S/N, Parque Industrial del Norte, C.P. 88730 Reynosa, Tamps., Mexico',
    city: 'Reynosa, Tamps.',
    focus: 'Diabetes & control products',
    lat: 26.0508,
    lng: -98.2978,
  },
  {
    id: 'mx-slp',
    name: 'San Luis Potosi',
    shortName: 'San Luis Potosi',
    country: 'MX',
    kind: 'manufacturing',
    address: 'Av. CFE No. 630, Zona Industrial, C.P. 78395 San Luis Potosi, S.L.P., Mexico',
    city: 'San Luis Potosi',
    focus: 'Diagnostics & culture systems',
    lat: 22.1498,
    lng: -100.9792,
  },
];

export function getPlantById(id: string): BdPlantSite | undefined {
  return BD_PLANT_SITES.find((p) => p.id === id);
}
