import type {ProductionMachine} from './types';

export const schedulingMachinesMock: ProductionMachine[] = [
  {id: 'machine-10a', lineId: 'line-10', name: 'M-10A Filler', description: 'Tube Fill & Seal 1', machineType: 'Filler', status: 'Running', utilizationPercent: 91, currentWorkOrderId: 'WO-100245-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 17000, notes: 'Primary filler for tube products.'},
  {id: 'machine-10b', lineId: 'line-10', name: 'M-10B Sealer', description: 'Tube Fill & Seal 1', machineType: 'Sealer', status: 'Running', utilizationPercent: 86, currentWorkOrderId: 'WO-100245-OP20', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 16500, notes: 'Inline sealing resource.'},
  {id: 'machine-10c', lineId: 'line-10', name: 'M-10C Labeler', description: 'Tube Fill & Seal 1', machineType: 'Labeler', status: 'Blocked', utilizationPercent: 74, currentWorkOrderId: 'WO-100245-OP30', riskLevel: 'High', riskReason: 'Label roll shortage', capacityRatePerHour: 15000, notes: 'Label reel staging is unstable.'},
  {id: 'machine-20a', lineId: 'line-20', name: 'M-20A Filler', description: 'Tube Fill & Seal 2', machineType: 'Filler', status: 'Running', utilizationPercent: 89, currentWorkOrderId: 'WO-200104-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 16000, notes: 'Main additive filling machine.'},
  {id: 'machine-20b', lineId: 'line-20', name: 'M-20B Capper', description: 'Tube Fill & Seal 2', machineType: 'Other', status: 'Maintenance', utilizationPercent: 48, currentWorkOrderId: null, riskLevel: 'Medium', riskReason: 'Preventive maintenance', capacityRatePerHour: 14500, notes: 'Maintenance lockout scheduled on day two.'},
  {id: 'machine-30a', lineId: 'line-30', name: 'M-30A Feeder', description: 'Assembly Line 1', machineType: 'Conveyor', status: 'Running', utilizationPercent: 85, currentWorkOrderId: 'WO-300090-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 6200, notes: 'Feeds specialty pack components.'},
  {id: 'machine-30b', lineId: 'line-30', name: 'M-30B Assembly Robot', description: 'Assembly Line 1', machineType: 'Robot', status: 'Down', utilizationPercent: 30, currentWorkOrderId: null, riskLevel: 'Critical', riskReason: 'Servo fault', capacityRatePerHour: 5800, notes: 'Requires maintenance inspection before restart.'},
  {id: 'machine-30c', lineId: 'line-30', name: 'M-30C Vision Inspector', description: 'Assembly Line 1', machineType: 'Inspector', status: 'Running', utilizationPercent: 78, currentWorkOrderId: 'WO-300090-OP30', riskLevel: 'Medium', riskReason: 'High reject sensitivity', capacityRatePerHour: 6100, notes: 'Vision setup adjusted for specialty packs.'},
  {id: 'machine-30d', lineId: 'line-30', name: 'M-30D Packer', description: 'Assembly Line 1', machineType: 'Packer', status: 'Running', utilizationPercent: 88, currentWorkOrderId: 'WO-300090-OP40', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 6400, notes: 'End-of-line packing station.'},
  {id: 'machine-40a', lineId: 'line-40', name: 'M-40A Sterilizer', description: 'Sterilization Line', machineType: 'Sterilizer', status: 'Running', utilizationPercent: 95, currentWorkOrderId: 'WO-400021-OP10', riskLevel: 'High', riskReason: 'Queue buildup', capacityRatePerHour: 12000, notes: 'Queue is building toward the end of the day.'},
  {id: 'machine-50a', lineId: 'line-50', name: 'M-50A Cartoner', description: 'Packaging Line 1', machineType: 'Packer', status: 'Running', utilizationPercent: 84, currentWorkOrderId: 'WO-500044-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 7200, notes: 'Primary cartoner.'},
  {id: 'machine-50b', lineId: 'line-50', name: 'M-50B Label Printer', description: 'Packaging Line 1', machineType: 'Printer', status: 'Available', utilizationPercent: 69, currentWorkOrderId: 'WO-500044-OP20', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 7000, notes: 'Print queue shared with case packer.'},
  {id: 'machine-50c', lineId: 'line-50', name: 'M-50C Case Packer', description: 'Packaging Line 1', machineType: 'Packer', status: 'Running', utilizationPercent: 82, currentWorkOrderId: 'WO-500063-OP30', riskLevel: 'Medium', riskReason: 'Changeover load', capacityRatePerHour: 6800, notes: 'Handles family changeover between low volume and specialty.'},
  {id: 'machine-50d', lineId: 'line-50', name: 'M-50D Checkweigher', description: 'Packaging Line 1', machineType: 'Tester', status: 'Blocked', utilizationPercent: 22, currentWorkOrderId: null, riskLevel: 'High', riskReason: 'Calibration expired', capacityRatePerHour: 7300, notes: 'Requires QA release after recalibration.'},
  {id: 'machine-50e', lineId: 'line-50', name: 'M-50E Palletizer', description: 'Packaging Line 1', machineType: 'Robot', status: 'Idle', utilizationPercent: 54, currentWorkOrderId: 'WO-500078-OP50', riskLevel: 'Medium', riskReason: 'Labor handoff timing', capacityRatePerHour: 7600, notes: 'Manual handoff timing affects pallet release.'},
  {id: 'machine-60a', lineId: 'line-60', name: 'M-60A Manual Bench', description: 'Manual / Rework', machineType: 'Other', status: 'Idle', utilizationPercent: 41, currentWorkOrderId: 'WO-600001-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 1800, notes: 'Supports manual recovery work.'},
  {id: 'machine-60b', lineId: 'line-60', name: 'M-60B Rework Station', description: 'Manual / Rework', machineType: 'Other', status: 'Setup', utilizationPercent: 49, currentWorkOrderId: 'WO-600021-OP20', riskLevel: 'Medium', riskReason: 'Operator rotation', capacityRatePerHour: 1600, notes: 'Shared labor across two shifts.'},
  {id: 'machine-70a', lineId: 'line-70', name: 'M-70A Visual Inspection', description: 'Inspection Line', machineType: 'Inspector', status: 'Running', utilizationPercent: 83, currentWorkOrderId: 'WO-700011-OP10', riskLevel: 'Low', riskReason: '', capacityRatePerHour: 8900, notes: 'Front-end visual inspection gate.'},
  {id: 'machine-70b', lineId: 'line-70', name: 'M-70B Metrology Station', description: 'Inspection Line', machineType: 'Tester', status: 'Available', utilizationPercent: 71, currentWorkOrderId: 'WO-700022-OP20', riskLevel: 'Medium', riskReason: 'Gauge study pending', capacityRatePerHour: 8400, notes: 'Metrology checks may slow at higher sampling.'},
  {id: 'machine-70c', lineId: 'line-70', name: 'M-70C Final QA Gate', description: 'Inspection Line', machineType: 'Inspector', status: 'Running', utilizationPercent: 79, currentWorkOrderId: 'WO-700033-OP30', riskLevel: 'Medium', riskReason: 'Final release queue', capacityRatePerHour: 8600, notes: 'Final release queue rises late in horizon.'},
];
