import type {MachineWorkOrder, TimelineEvent} from './types';

function machineWorkOrder(config: {
  id: string;
  woNumber: string;
  workOrderId: string;
  machineId: string;
  machineName: string;
  machineType: MachineWorkOrder['machineType'];
  lineId: string;
  productCode: string;
  productDescription: string;
  productFamily: string;
  batchNumber: string;
  quantity: number;
  plannedStartDateTime: string;
  plannedEndDateTime: string;
  durationHours: number;
  status: MachineWorkOrder['status'];
  readinessStatus: MachineWorkOrder['readinessStatus'];
  priority: MachineWorkOrder['priority'];
  operationName: string;
  operationSequence: number;
  setupRequired?: boolean;
  setupMinutes?: number;
  changeoverGroup: string;
  materialRisk?: MachineWorkOrder['materialRisk'];
  qualityRisk?: MachineWorkOrder['qualityRisk'];
  laborRisk?: MachineWorkOrder['laborRisk'];
  exceptionCount?: number;
  progressPercent?: number;
  notes?: string;
  constraintReason?: string;
  plannerComment?: string;
}): MachineWorkOrder {
  return {
    id: config.id,
    woNumber: config.woNumber,
    batchNumber: config.batchNumber,
    productCode: config.productCode,
    productDescription: config.productDescription,
    productFamily: config.productFamily,
    quantity: config.quantity,
    uom: 'PCS',
    lineId: config.lineId,
    plannedStartDateTime: config.plannedStartDateTime,
    plannedEndDateTime: config.plannedEndDateTime,
    durationHours: config.durationHours,
    status: config.status,
    readinessStatus: config.readinessStatus,
    priority: config.priority,
    exceptionCount: config.exceptionCount ?? 0,
    machineId: config.machineId,
    machineName: config.machineName,
    machineType: config.machineType,
    operationName: config.operationName,
    operationSequence: config.operationSequence,
    setupRequired: config.setupRequired ?? false,
    setupMinutes: config.setupMinutes ?? 0,
    changeoverGroup: config.changeoverGroup,
    materialRisk: config.materialRisk ?? 'None',
    qualityRisk: config.qualityRisk ?? 'None',
    laborRisk: config.laborRisk ?? 'None',
    progressPercent: config.progressPercent ?? 0,
    aiSequenceRecommendation: '',
    notes: config.notes,
    constraintReason: config.constraintReason,
    plannerComment: config.plannerComment,
  };
}

function machineEvent(config: {
  id: string;
  lineId: string;
  lineName: string;
  machineId: string;
  machineName: string;
  category: TimelineEvent['category'];
  eventType: string;
  status: TimelineEvent['status'];
  severity: TimelineEvent['severity'];
  startDateTime: string;
  endDateTime: string;
  description: string;
  source: string;
  reasonCode: string;
  workOrderId?: string;
  productCode?: string;
}): TimelineEvent {
  return {
    id: config.id,
    lineId: config.lineId,
    lineName: config.lineName,
    machineId: config.machineId,
    machineName: config.machineName,
    category: config.category,
    eventType: config.eventType,
    status: config.status,
    severity: config.severity,
    startDateTime: config.startDateTime,
    endDateTime: config.endDateTime,
    description: config.description,
    source: config.source,
    reasonCode: config.reasonCode,
    recommendedActions: [
      `Review ${config.machineName} status before next shift handoff.`,
      'Confirm planner recovery sequence with production supervisor.',
      'Escalate if the issue remains active past the next execution window.',
    ],
    workOrderId: config.workOrderId,
    relatedWorkOrderId: config.workOrderId,
    productCode: config.productCode,
    productDescription: config.productCode ? `${config.productCode} machine operation` : undefined,
  };
}

export const schedulingMachineWorkOrdersMock: MachineWorkOrder[] = [
  machineWorkOrder({id: 'mwo-001', woNumber: 'WO-100245-OP10', workOrderId: 'WO-100245', machineId: 'machine-10a', machineName: 'M-10A Filler', machineType: 'Filler', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-245-A', quantity: 32000, plannedStartDateTime: '2026-05-15T07:00', plannedEndDateTime: '2026-05-15T10:00', durationHours: 3, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Fill Tubes', operationSequence: 10, changeoverGroup: 'STD-TUBE', progressPercent: 68}),
  machineWorkOrder({id: 'mwo-002', woNumber: 'WO-100266-OP10', workOrderId: 'WO-100266', machineId: 'machine-10a', machineName: 'M-10A Filler', machineType: 'Filler', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-266-A', quantity: 28000, plannedStartDateTime: '2026-05-15T10:00', plannedEndDateTime: '2026-05-15T13:30', durationHours: 3.5, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Fill Tubes', operationSequence: 10, changeoverGroup: 'STD-TUBE'}),
  machineWorkOrder({id: 'mwo-003', woNumber: 'WO-100280-OP10', workOrderId: 'WO-100280', machineId: 'machine-10a', machineName: 'M-10A Filler', machineType: 'Filler', lineId: 'line-10', productCode: 'FG-1002', productDescription: 'Standard Tube B', productFamily: 'Standard Tube', batchNumber: 'B-280-B', quantity: 24000, plannedStartDateTime: '2026-05-15T13:30', plannedEndDateTime: '2026-05-15T17:30', durationHours: 4, status: 'Planned', readinessStatus: 'Warning', priority: 'High', operationName: 'Fill Tubes', operationSequence: 10, changeoverGroup: 'STD-TUBE', materialRisk: 'Medium', exceptionCount: 1, notes: 'Material staging pending.'}),
  machineWorkOrder({id: 'mwo-004', woNumber: 'WO-100245-OP20', workOrderId: 'WO-100245', machineId: 'machine-10b', machineName: 'M-10B Sealer', machineType: 'Sealer', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-245-A', quantity: 32000, plannedStartDateTime: '2026-05-15T07:30', plannedEndDateTime: '2026-05-15T10:30', durationHours: 3, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Seal Tubes', operationSequence: 20, changeoverGroup: 'STD-TUBE', progressPercent: 62}),
  machineWorkOrder({id: 'mwo-005', woNumber: 'WO-100266-OP20', workOrderId: 'WO-100266', machineId: 'machine-10b', machineName: 'M-10B Sealer', machineType: 'Sealer', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-266-A', quantity: 28000, plannedStartDateTime: '2026-05-15T10:30', plannedEndDateTime: '2026-05-15T14:00', durationHours: 3.5, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Seal Tubes', operationSequence: 20, changeoverGroup: 'STD-TUBE'}),
  machineWorkOrder({id: 'mwo-006', woNumber: 'WO-100280-OP20', workOrderId: 'WO-100280', machineId: 'machine-10b', machineName: 'M-10B Sealer', machineType: 'Sealer', lineId: 'line-10', productCode: 'FG-1002', productDescription: 'Standard Tube B', productFamily: 'Standard Tube', batchNumber: 'B-280-B', quantity: 24000, plannedStartDateTime: '2026-05-15T14:00', plannedEndDateTime: '2026-05-15T18:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'High', operationName: 'Seal Tubes', operationSequence: 20, changeoverGroup: 'STD-TUBE', setupRequired: true, setupMinutes: 30}),
  machineWorkOrder({id: 'mwo-007', woNumber: 'WO-100245-OP30', workOrderId: 'WO-100245', machineId: 'machine-10c', machineName: 'M-10C Labeler', machineType: 'Labeler', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-245-A', quantity: 32000, plannedStartDateTime: '2026-05-15T08:00', plannedEndDateTime: '2026-05-15T11:00', durationHours: 3, status: 'Blocked', readinessStatus: 'Blocked', priority: 'High', operationName: 'Apply Label', operationSequence: 30, changeoverGroup: 'STD-TUBE', materialRisk: 'High', exceptionCount: 2, notes: 'Label roll shortage.'}),
  machineWorkOrder({id: 'mwo-008', woNumber: 'WO-100266-OP30', workOrderId: 'WO-100266', machineId: 'machine-10c', machineName: 'M-10C Labeler', machineType: 'Labeler', lineId: 'line-10', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-266-A', quantity: 28000, plannedStartDateTime: '2026-05-15T11:00', plannedEndDateTime: '2026-05-15T14:30', durationHours: 3.5, status: 'Planned', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Apply Label', operationSequence: 30, changeoverGroup: 'STD-TUBE'}),
  machineWorkOrder({id: 'mwo-009', woNumber: 'WO-100280-OP30', workOrderId: 'WO-100280', machineId: 'machine-10c', machineName: 'M-10C Labeler', machineType: 'Labeler', lineId: 'line-10', productCode: 'FG-1002', productDescription: 'Standard Tube B', productFamily: 'Standard Tube', batchNumber: 'B-280-B', quantity: 24000, plannedStartDateTime: '2026-05-15T14:30', plannedEndDateTime: '2026-05-15T18:30', durationHours: 4, status: 'Planned', readinessStatus: 'Warning', priority: 'High', operationName: 'Apply Label', operationSequence: 30, changeoverGroup: 'STD-TUBE', materialRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-010', woNumber: 'WO-200104-OP10', workOrderId: 'WO-200104', machineId: 'machine-20a', machineName: 'M-20A Filler', machineType: 'Filler', lineId: 'line-20', productCode: 'FG-2001', productDescription: 'Additive Tube', productFamily: 'Additive Tube', batchNumber: 'B-104-A', quantity: 12000, plannedStartDateTime: '2026-05-15T07:00', plannedEndDateTime: '2026-05-15T10:00', durationHours: 3, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Fill Additives', operationSequence: 10, changeoverGroup: 'ADDITIVE', progressPercent: 55}),
  machineWorkOrder({id: 'mwo-011', woNumber: 'WO-200118-OP10', workOrderId: 'WO-200118', machineId: 'machine-20a', machineName: 'M-20A Filler', machineType: 'Filler', lineId: 'line-20', productCode: 'FG-2001', productDescription: 'Additive Tube', productFamily: 'Additive Tube', batchNumber: 'B-118-A', quantity: 18000, plannedStartDateTime: '2026-05-15T10:00', plannedEndDateTime: '2026-05-15T13:00', durationHours: 3, status: 'Released', readinessStatus: 'Warning', priority: 'Critical', operationName: 'Fill Additives', operationSequence: 10, changeoverGroup: 'ADDITIVE', materialRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-012', woNumber: 'WO-200133-OP10', workOrderId: 'WO-200133', machineId: 'machine-20a', machineName: 'M-20A Filler', machineType: 'Filler', lineId: 'line-20', productCode: 'FG-3001', productDescription: 'Gel Product', productFamily: 'Gel Product', batchNumber: 'B-133-G', quantity: 22000, plannedStartDateTime: '2026-05-16T07:00', plannedEndDateTime: '2026-05-16T11:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Fill Gel', operationSequence: 10, changeoverGroup: 'GEL', setupRequired: true, setupMinutes: 45}),
  machineWorkOrder({id: 'mwo-013', woNumber: 'WO-200104-OP20', workOrderId: 'WO-200104', machineId: 'machine-20b', machineName: 'M-20B Capper', machineType: 'Other', lineId: 'line-20', productCode: 'FG-2001', productDescription: 'Additive Tube', productFamily: 'Additive Tube', batchNumber: 'B-104-A', quantity: 12000, plannedStartDateTime: '2026-05-15T07:30', plannedEndDateTime: '2026-05-15T10:30', durationHours: 3, status: 'Completed', readinessStatus: 'Ready', priority: 'High', operationName: 'Cap Tubes', operationSequence: 20, changeoverGroup: 'ADDITIVE', progressPercent: 100}),
  machineWorkOrder({id: 'mwo-014', woNumber: 'WO-200118-OP20', workOrderId: 'WO-200118', machineId: 'machine-20b', machineName: 'M-20B Capper', machineType: 'Other', lineId: 'line-20', productCode: 'FG-2001', productDescription: 'Additive Tube', productFamily: 'Additive Tube', batchNumber: 'B-118-A', quantity: 18000, plannedStartDateTime: '2026-05-16T08:00', plannedEndDateTime: '2026-05-16T11:00', durationHours: 3, status: 'OnHold', readinessStatus: 'Warning', priority: 'Critical', operationName: 'Cap Tubes', operationSequence: 20, changeoverGroup: 'ADDITIVE', laborRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-015', woNumber: 'WO-200142-OP20', workOrderId: 'WO-200142', machineId: 'machine-20b', machineName: 'M-20B Capper', machineType: 'Other', lineId: 'line-20', productCode: 'FG-3001', productDescription: 'Gel Product', productFamily: 'Gel Product', batchNumber: 'B-142-G', quantity: 16000, plannedStartDateTime: '2026-05-17T08:00', plannedEndDateTime: '2026-05-17T12:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'High', operationName: 'Cap Gel Tubes', operationSequence: 20, changeoverGroup: 'GEL'}),
  machineWorkOrder({id: 'mwo-016', woNumber: 'WO-300090-OP10', workOrderId: 'WO-300090', machineId: 'machine-30a', machineName: 'M-30A Feeder', machineType: 'Conveyor', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-090-S', quantity: 5200, plannedStartDateTime: '2026-05-15T07:00', plannedEndDateTime: '2026-05-15T11:00', durationHours: 4, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Feed Components', operationSequence: 10, changeoverGroup: 'SPECIALTY', progressPercent: 61}),
  machineWorkOrder({id: 'mwo-017', woNumber: 'WO-300097-OP10', workOrderId: 'WO-300097', machineId: 'machine-30a', machineName: 'M-30A Feeder', machineType: 'Conveyor', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-097-S', quantity: 6000, plannedStartDateTime: '2026-05-15T11:30', plannedEndDateTime: '2026-05-15T15:00', durationHours: 3.5, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Feed Components', operationSequence: 10, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-018', woNumber: 'WO-300111-OP10', workOrderId: 'WO-300111', machineId: 'machine-30a', machineName: 'M-30A Feeder', machineType: 'Conveyor', lineId: 'line-30', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-111-L', quantity: 1700, plannedStartDateTime: '2026-05-16T07:30', plannedEndDateTime: '2026-05-16T11:30', durationHours: 4, status: 'Planned', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Feed Components', operationSequence: 10, changeoverGroup: 'LOW-VOLUME', laborRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-019', woNumber: 'WO-300090-OP20', workOrderId: 'WO-300090', machineId: 'machine-30b', machineName: 'M-30B Assembly Robot', machineType: 'Robot', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-090-S', quantity: 5200, plannedStartDateTime: '2026-05-15T10:00', plannedEndDateTime: '2026-05-15T13:00', durationHours: 3, status: 'Blocked', readinessStatus: 'Blocked', priority: 'High', operationName: 'Assemble Pack', operationSequence: 20, changeoverGroup: 'SPECIALTY', laborRisk: 'Low', exceptionCount: 2, notes: 'Servo fault blocks execution.'}),
  machineWorkOrder({id: 'mwo-020', woNumber: 'WO-300097-OP20', workOrderId: 'WO-300097', machineId: 'machine-30b', machineName: 'M-30B Assembly Robot', machineType: 'Robot', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-097-S', quantity: 6000, plannedStartDateTime: '2026-05-16T09:00', plannedEndDateTime: '2026-05-16T12:00', durationHours: 3, status: 'OnHold', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Assemble Pack', operationSequence: 20, changeoverGroup: 'SPECIALTY', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-021', woNumber: 'WO-300125-OP20', workOrderId: 'WO-300125', machineId: 'machine-30b', machineName: 'M-30B Assembly Robot', machineType: 'Robot', lineId: 'line-30', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-125-L', quantity: 2000, plannedStartDateTime: '2026-05-17T08:00', plannedEndDateTime: '2026-05-17T12:00', durationHours: 4, status: 'Planned', readinessStatus: 'Blocked', priority: 'Critical', operationName: 'Assemble Low Volume', operationSequence: 20, changeoverGroup: 'LOW-VOLUME', materialRisk: 'High', laborRisk: 'Medium', exceptionCount: 2}),
  machineWorkOrder({id: 'mwo-022', woNumber: 'WO-300090-OP30', workOrderId: 'WO-300090', machineId: 'machine-30c', machineName: 'M-30C Vision Inspector', machineType: 'Inspector', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-090-S', quantity: 5200, plannedStartDateTime: '2026-05-15T12:00', plannedEndDateTime: '2026-05-15T15:30', durationHours: 3.5, status: 'Released', readinessStatus: 'Ready', priority: 'High', operationName: 'Inspect', operationSequence: 30, changeoverGroup: 'SPECIALTY', progressPercent: 8}),
  machineWorkOrder({id: 'mwo-023', woNumber: 'WO-300097-OP30', workOrderId: 'WO-300097', machineId: 'machine-30c', machineName: 'M-30C Vision Inspector', machineType: 'Inspector', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-097-S', quantity: 6000, plannedStartDateTime: '2026-05-16T11:00', plannedEndDateTime: '2026-05-16T14:30', durationHours: 3.5, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Inspect', operationSequence: 30, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-024', woNumber: 'WO-300111-OP30', workOrderId: 'WO-300111', machineId: 'machine-30c', machineName: 'M-30C Vision Inspector', machineType: 'Inspector', lineId: 'line-30', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-111-L', quantity: 1700, plannedStartDateTime: '2026-05-17T10:00', plannedEndDateTime: '2026-05-17T13:30', durationHours: 3.5, status: 'Planned', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Inspect', operationSequence: 30, changeoverGroup: 'LOW-VOLUME', qualityRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-025', woNumber: 'WO-300090-OP40', workOrderId: 'WO-300090', machineId: 'machine-30d', machineName: 'M-30D Packer', machineType: 'Packer', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-090-S', quantity: 5200, plannedStartDateTime: '2026-05-15T13:00', plannedEndDateTime: '2026-05-15T17:00', durationHours: 4, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Pack', operationSequence: 40, changeoverGroup: 'SPECIALTY', progressPercent: 39}),
  machineWorkOrder({id: 'mwo-026', woNumber: 'WO-300097-OP40', workOrderId: 'WO-300097', machineId: 'machine-30d', machineName: 'M-30D Packer', machineType: 'Packer', lineId: 'line-30', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-097-S', quantity: 6000, plannedStartDateTime: '2026-05-16T14:00', plannedEndDateTime: '2026-05-16T18:00', durationHours: 4, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Pack', operationSequence: 40, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-027', woNumber: 'WO-300125-OP40', workOrderId: 'WO-300125', machineId: 'machine-30d', machineName: 'M-30D Packer', machineType: 'Packer', lineId: 'line-30', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-125-L', quantity: 2000, plannedStartDateTime: '2026-05-17T13:00', plannedEndDateTime: '2026-05-17T17:00', durationHours: 4, status: 'Planned', readinessStatus: 'Blocked', priority: 'Critical', operationName: 'Pack', operationSequence: 40, changeoverGroup: 'LOW-VOLUME', materialRisk: 'High', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-028', woNumber: 'WO-400021-OP10', workOrderId: 'WO-400021', machineId: 'machine-40a', machineName: 'M-40A Sterilizer', machineType: 'Sterilizer', lineId: 'line-40', productCode: 'FG-3001', productDescription: 'Gel Product', productFamily: 'Gel Product', batchNumber: 'B-021-S', quantity: 20000, plannedStartDateTime: '2026-05-15T08:00', plannedEndDateTime: '2026-05-15T14:00', durationHours: 6, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Sterilize', operationSequence: 10, changeoverGroup: 'STERILE', progressPercent: 72}),
  machineWorkOrder({id: 'mwo-029', woNumber: 'WO-400034-OP10', workOrderId: 'WO-400034', machineId: 'machine-40a', machineName: 'M-40A Sterilizer', machineType: 'Sterilizer', lineId: 'line-40', productCode: 'FG-3001', productDescription: 'Gel Product', productFamily: 'Gel Product', batchNumber: 'B-034-S', quantity: 18000, plannedStartDateTime: '2026-05-16T07:00', plannedEndDateTime: '2026-05-16T13:00', durationHours: 6, status: 'Released', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Sterilize', operationSequence: 10, changeoverGroup: 'STERILE'}),
  machineWorkOrder({id: 'mwo-030', woNumber: 'WO-400047-OP10', workOrderId: 'WO-400047', machineId: 'machine-40a', machineName: 'M-40A Sterilizer', machineType: 'Sterilizer', lineId: 'line-40', productCode: 'FG-1001', productDescription: 'Standard Tube A', productFamily: 'Standard Tube', batchNumber: 'B-047-S', quantity: 30000, plannedStartDateTime: '2026-05-17T07:00', plannedEndDateTime: '2026-05-17T13:00', durationHours: 6, status: 'Planned', readinessStatus: 'Warning', priority: 'High', operationName: 'Sterilize', operationSequence: 10, changeoverGroup: 'STERILE', materialRisk: 'Low', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-031', woNumber: 'WO-500044-OP10', workOrderId: 'WO-500044', machineId: 'machine-50a', machineName: 'M-50A Cartoner', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-044-P', quantity: 1700, plannedStartDateTime: '2026-05-15T07:00', plannedEndDateTime: '2026-05-15T10:00', durationHours: 3, status: 'Running', readinessStatus: 'Warning', priority: 'High', operationName: 'Carton', operationSequence: 10, changeoverGroup: 'LOW-VOLUME', laborRisk: 'Medium', exceptionCount: 1, progressPercent: 57}),
  machineWorkOrder({id: 'mwo-032', woNumber: 'WO-500051-OP10', workOrderId: 'WO-500051', machineId: 'machine-50a', machineName: 'M-50A Cartoner', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-051-P', quantity: 1900, plannedStartDateTime: '2026-05-15T10:00', plannedEndDateTime: '2026-05-15T13:00', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Carton', operationSequence: 10, changeoverGroup: 'LOW-VOLUME'}),
  machineWorkOrder({id: 'mwo-033', woNumber: 'WO-500063-OP10', workOrderId: 'WO-500063', machineId: 'machine-50a', machineName: 'M-50A Cartoner', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-063-P', quantity: 5500, plannedStartDateTime: '2026-05-16T07:00', plannedEndDateTime: '2026-05-16T11:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'High', operationName: 'Carton', operationSequence: 10, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-034', woNumber: 'WO-500044-OP20', workOrderId: 'WO-500044', machineId: 'machine-50b', machineName: 'M-50B Label Printer', machineType: 'Printer', lineId: 'line-50', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-044-P', quantity: 1700, plannedStartDateTime: '2026-05-15T07:30', plannedEndDateTime: '2026-05-15T09:30', durationHours: 2, status: 'Completed', readinessStatus: 'Ready', priority: 'High', operationName: 'Print Labels', operationSequence: 20, changeoverGroup: 'LOW-VOLUME', progressPercent: 100}),
  machineWorkOrder({id: 'mwo-035', woNumber: 'WO-500051-OP20', workOrderId: 'WO-500051', machineId: 'machine-50b', machineName: 'M-50B Label Printer', machineType: 'Printer', lineId: 'line-50', productCode: 'FG-5001', productDescription: 'Low Volume Product', productFamily: 'Low Volume Product', batchNumber: 'B-051-P', quantity: 1900, plannedStartDateTime: '2026-05-16T08:00', plannedEndDateTime: '2026-05-16T10:00', durationHours: 2, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Print Labels', operationSequence: 20, changeoverGroup: 'LOW-VOLUME'}),
  machineWorkOrder({id: 'mwo-036', woNumber: 'WO-500078-OP20', workOrderId: 'WO-500078', machineId: 'machine-50b', machineName: 'M-50B Label Printer', machineType: 'Printer', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-078-P', quantity: 6200, plannedStartDateTime: '2026-05-17T08:00', plannedEndDateTime: '2026-05-17T12:00', durationHours: 4, status: 'Planned', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Print Labels', operationSequence: 20, changeoverGroup: 'SPECIALTY', materialRisk: 'Low', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-037', woNumber: 'WO-500063-OP30', workOrderId: 'WO-500063', machineId: 'machine-50c', machineName: 'M-50C Case Packer', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-063-P', quantity: 5500, plannedStartDateTime: '2026-05-16T11:00', plannedEndDateTime: '2026-05-16T15:00', durationHours: 4, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Case Pack', operationSequence: 30, changeoverGroup: 'SPECIALTY', progressPercent: 42}),
  machineWorkOrder({id: 'mwo-038', woNumber: 'WO-500063-OP30B', workOrderId: 'WO-500063', machineId: 'machine-50c', machineName: 'M-50C Case Packer', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-063-P2', quantity: 3000, plannedStartDateTime: '2026-05-16T14:30', plannedEndDateTime: '2026-05-16T17:30', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Case Pack Split', operationSequence: 35, changeoverGroup: 'SPECIALTY', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-039', woNumber: 'WO-500078-OP30', workOrderId: 'WO-500078', machineId: 'machine-50c', machineName: 'M-50C Case Packer', machineType: 'Packer', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-078-P', quantity: 6200, plannedStartDateTime: '2026-05-17T10:00', plannedEndDateTime: '2026-05-17T14:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Case Pack', operationSequence: 30, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-040', woNumber: 'WO-500063-OP40', workOrderId: 'WO-500063', machineId: 'machine-50d', machineName: 'M-50D Checkweigher', machineType: 'Tester', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-063-P', quantity: 5500, plannedStartDateTime: '2026-05-16T15:00', plannedEndDateTime: '2026-05-16T18:00', durationHours: 3, status: 'Blocked', readinessStatus: 'Blocked', priority: 'High', operationName: 'Check Weight', operationSequence: 40, changeoverGroup: 'SPECIALTY', qualityRisk: 'High', exceptionCount: 2, notes: 'Calibration expired.'}),
  machineWorkOrder({id: 'mwo-041', woNumber: 'WO-500078-OP40', workOrderId: 'WO-500078', machineId: 'machine-50d', machineName: 'M-50D Checkweigher', machineType: 'Tester', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-078-P', quantity: 6200, plannedStartDateTime: '2026-05-17T12:00', plannedEndDateTime: '2026-05-17T15:00', durationHours: 3, status: 'OnHold', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Check Weight', operationSequence: 40, changeoverGroup: 'SPECIALTY', qualityRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-042', woNumber: 'WO-500099-OP40', workOrderId: 'WO-500099', machineId: 'machine-50d', machineName: 'M-50D Checkweigher', machineType: 'Tester', lineId: 'line-50', productCode: 'FG-4100', productDescription: 'Promo Pack', productFamily: 'Promo Pack', batchNumber: 'B-099-P', quantity: 4300, plannedStartDateTime: '2026-05-17T16:00', plannedEndDateTime: '2026-05-17T19:00', durationHours: 3, status: 'Planned', readinessStatus: 'Ready', priority: 'Low', operationName: 'Check Weight', operationSequence: 40, changeoverGroup: 'PROMO'}),
  machineWorkOrder({id: 'mwo-043', woNumber: 'WO-500063-OP50', workOrderId: 'WO-500063', machineId: 'machine-50e', machineName: 'M-50E Palletizer', machineType: 'Robot', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-063-P', quantity: 5500, plannedStartDateTime: '2026-05-16T17:00', plannedEndDateTime: '2026-05-16T20:00', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'High', operationName: 'Palletize', operationSequence: 50, changeoverGroup: 'SPECIALTY'}),
  machineWorkOrder({id: 'mwo-044', woNumber: 'WO-500078-OP50', workOrderId: 'WO-500078', machineId: 'machine-50e', machineName: 'M-50E Palletizer', machineType: 'Robot', lineId: 'line-50', productCode: 'FG-4001', productDescription: 'Specialty Pack', productFamily: 'Specialty Pack', batchNumber: 'B-078-P', quantity: 6200, plannedStartDateTime: '2026-05-17T15:00', plannedEndDateTime: '2026-05-17T18:30', durationHours: 3.5, status: 'Planned', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Palletize', operationSequence: 50, changeoverGroup: 'SPECIALTY', laborRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-045', woNumber: 'WO-500099-OP50', workOrderId: 'WO-500099', machineId: 'machine-50e', machineName: 'M-50E Palletizer', machineType: 'Robot', lineId: 'line-50', productCode: 'FG-4100', productDescription: 'Promo Pack', productFamily: 'Promo Pack', batchNumber: 'B-099-P', quantity: 4300, plannedStartDateTime: '2026-05-17T18:30', plannedEndDateTime: '2026-05-17T21:00', durationHours: 2.5, status: 'Planned', readinessStatus: 'Ready', priority: 'Low', operationName: 'Palletize', operationSequence: 50, changeoverGroup: 'PROMO'}),
  machineWorkOrder({id: 'mwo-046', woNumber: 'WO-600001-OP10', workOrderId: 'WO-600001', machineId: 'machine-60a', machineName: 'M-60A Manual Bench', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6100', productDescription: 'Rework Kit A', productFamily: 'Rework', batchNumber: 'B-001-R', quantity: 900, plannedStartDateTime: '2026-05-15T09:00', plannedEndDateTime: '2026-05-15T12:00', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Manual Rework', operationSequence: 10, changeoverGroup: 'REWORK'}),
  machineWorkOrder({id: 'mwo-047', woNumber: 'WO-600011-OP10', workOrderId: 'WO-600011', machineId: 'machine-60a', machineName: 'M-60A Manual Bench', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6101', productDescription: 'Rework Kit B', productFamily: 'Rework', batchNumber: 'B-011-R', quantity: 1100, plannedStartDateTime: '2026-05-16T09:00', plannedEndDateTime: '2026-05-16T13:00', durationHours: 4, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Manual Rework', operationSequence: 10, changeoverGroup: 'REWORK', progressPercent: 44}),
  machineWorkOrder({id: 'mwo-048', woNumber: 'WO-600021-OP10', workOrderId: 'WO-600021', machineId: 'machine-60a', machineName: 'M-60A Manual Bench', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6200', productDescription: 'Containment Sort', productFamily: 'Containment', batchNumber: 'B-021-R', quantity: 700, plannedStartDateTime: '2026-05-17T10:00', plannedEndDateTime: '2026-05-17T13:00', durationHours: 3, status: 'Planned', readinessStatus: 'Warning', priority: 'Medium', operationName: 'Manual Sort', operationSequence: 10, changeoverGroup: 'CONTAINMENT', laborRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-049', woNumber: 'WO-600001-OP20', workOrderId: 'WO-600001', machineId: 'machine-60b', machineName: 'M-60B Rework Station', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6100', productDescription: 'Rework Kit A', productFamily: 'Rework', batchNumber: 'B-001-R', quantity: 900, plannedStartDateTime: '2026-05-15T12:00', plannedEndDateTime: '2026-05-15T15:00', durationHours: 3, status: 'Completed', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Rework Validation', operationSequence: 20, changeoverGroup: 'REWORK', progressPercent: 100}),
  machineWorkOrder({id: 'mwo-050', woNumber: 'WO-600021-OP20', workOrderId: 'WO-600021', machineId: 'machine-60b', machineName: 'M-60B Rework Station', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6200', productDescription: 'Containment Sort', productFamily: 'Containment', batchNumber: 'B-021-R', quantity: 700, plannedStartDateTime: '2026-05-16T14:00', plannedEndDateTime: '2026-05-16T17:00', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Rework Validation', operationSequence: 20, changeoverGroup: 'CONTAINMENT'}),
  machineWorkOrder({id: 'mwo-051', woNumber: 'WO-600031-OP20', workOrderId: 'WO-600031', machineId: 'machine-60b', machineName: 'M-60B Rework Station', machineType: 'Other', lineId: 'line-60', productCode: 'FG-6201', productDescription: 'Deviation Recovery', productFamily: 'Containment', batchNumber: 'B-031-R', quantity: 650, plannedStartDateTime: '2026-05-17T14:00', plannedEndDateTime: '2026-05-17T18:00', durationHours: 4, status: 'Planned', readinessStatus: 'Ready', priority: 'High', operationName: 'Rework Validation', operationSequence: 20, changeoverGroup: 'CONTAINMENT'}),
  machineWorkOrder({id: 'mwo-052', woNumber: 'WO-700011-OP10', workOrderId: 'WO-700011', machineId: 'machine-70a', machineName: 'M-70A Visual Inspection', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7001', productDescription: 'Visual Inspection', productFamily: 'Inspection', batchNumber: 'B-011-I', quantity: 7800, plannedStartDateTime: '2026-05-15T07:00', plannedEndDateTime: '2026-05-15T10:00', durationHours: 3, status: 'Running', readinessStatus: 'Ready', priority: 'High', operationName: 'Visual Inspect', operationSequence: 10, changeoverGroup: 'INSPECTION', progressPercent: 52}),
  machineWorkOrder({id: 'mwo-053', woNumber: 'WO-700022-OP10', workOrderId: 'WO-700022', machineId: 'machine-70a', machineName: 'M-70A Visual Inspection', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7002', productDescription: 'Metrology Queue', productFamily: 'Inspection', batchNumber: 'B-022-I', quantity: 8400, plannedStartDateTime: '2026-05-16T07:00', plannedEndDateTime: '2026-05-16T10:30', durationHours: 3.5, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Visual Inspect', operationSequence: 10, changeoverGroup: 'INSPECTION'}),
  machineWorkOrder({id: 'mwo-054', woNumber: 'WO-700033-OP10', workOrderId: 'WO-700033', machineId: 'machine-70a', machineName: 'M-70A Visual Inspection', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7003', productDescription: 'Final QA', productFamily: 'Inspection', batchNumber: 'B-033-I', quantity: 9000, plannedStartDateTime: '2026-05-17T07:00', plannedEndDateTime: '2026-05-17T11:00', durationHours: 4, status: 'Planned', readinessStatus: 'Warning', priority: 'High', operationName: 'Visual Inspect', operationSequence: 10, changeoverGroup: 'INSPECTION', qualityRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-055', woNumber: 'WO-700011-OP20', workOrderId: 'WO-700011', machineId: 'machine-70b', machineName: 'M-70B Metrology Station', machineType: 'Tester', lineId: 'line-70', productCode: 'FG-7001', productDescription: 'Visual Inspection', productFamily: 'Inspection', batchNumber: 'B-011-I', quantity: 7800, plannedStartDateTime: '2026-05-15T10:00', plannedEndDateTime: '2026-05-15T12:30', durationHours: 2.5, status: 'Completed', readinessStatus: 'Ready', priority: 'High', operationName: 'Measure Critical Dims', operationSequence: 20, changeoverGroup: 'INSPECTION', progressPercent: 100}),
  machineWorkOrder({id: 'mwo-056', woNumber: 'WO-700022-OP20', workOrderId: 'WO-700022', machineId: 'machine-70b', machineName: 'M-70B Metrology Station', machineType: 'Tester', lineId: 'line-70', productCode: 'FG-7002', productDescription: 'Metrology Queue', productFamily: 'Inspection', batchNumber: 'B-022-I', quantity: 8400, plannedStartDateTime: '2026-05-16T10:30', plannedEndDateTime: '2026-05-16T13:30', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Measure Critical Dims', operationSequence: 20, changeoverGroup: 'INSPECTION'}),
  machineWorkOrder({id: 'mwo-057', woNumber: 'WO-700033-OP20', workOrderId: 'WO-700033', machineId: 'machine-70b', machineName: 'M-70B Metrology Station', machineType: 'Tester', lineId: 'line-70', productCode: 'FG-7003', productDescription: 'Final QA', productFamily: 'Inspection', batchNumber: 'B-033-I', quantity: 9000, plannedStartDateTime: '2026-05-17T11:00', plannedEndDateTime: '2026-05-17T14:00', durationHours: 3, status: 'Planned', readinessStatus: 'Warning', priority: 'High', operationName: 'Measure Critical Dims', operationSequence: 20, changeoverGroup: 'INSPECTION', qualityRisk: 'Medium', exceptionCount: 1}),
  machineWorkOrder({id: 'mwo-058', woNumber: 'WO-700011-OP30', workOrderId: 'WO-700011', machineId: 'machine-70c', machineName: 'M-70C Final QA Gate', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7001', productDescription: 'Visual Inspection', productFamily: 'Inspection', batchNumber: 'B-011-I', quantity: 7800, plannedStartDateTime: '2026-05-15T12:30', plannedEndDateTime: '2026-05-15T15:30', durationHours: 3, status: 'Released', readinessStatus: 'Ready', priority: 'High', operationName: 'Final QA Release', operationSequence: 30, changeoverGroup: 'INSPECTION'}),
  machineWorkOrder({id: 'mwo-059', woNumber: 'WO-700022-OP30', workOrderId: 'WO-700022', machineId: 'machine-70c', machineName: 'M-70C Final QA Gate', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7002', productDescription: 'Metrology Queue', productFamily: 'Inspection', batchNumber: 'B-022-I', quantity: 8400, plannedStartDateTime: '2026-05-16T13:30', plannedEndDateTime: '2026-05-16T16:30', durationHours: 3, status: 'Ready', readinessStatus: 'Ready', priority: 'Medium', operationName: 'Final QA Release', operationSequence: 30, changeoverGroup: 'INSPECTION'}),
  machineWorkOrder({id: 'mwo-060', woNumber: 'WO-700033-OP30', workOrderId: 'WO-700033', machineId: 'machine-70c', machineName: 'M-70C Final QA Gate', machineType: 'Inspector', lineId: 'line-70', productCode: 'FG-7003', productDescription: 'Final QA', productFamily: 'Inspection', batchNumber: 'B-033-I', quantity: 9000, plannedStartDateTime: '2026-05-17T14:00', plannedEndDateTime: '2026-05-17T17:30', durationHours: 3.5, status: 'Planned', readinessStatus: 'Ready', priority: 'High', operationName: 'Final QA Release', operationSequence: 30, changeoverGroup: 'INSPECTION'}),
];

export const schedulingMachineEventsMock: TimelineEvent[] = [
  machineEvent({id: 'mev-001', lineId: 'line-10', lineName: 'Line 10 - Tube Fill & Seal 1', machineId: 'machine-10b', machineName: 'M-10B Sealer', category: 'Changeover / Setup', eventType: 'Setup Started', status: 'Running', severity: 'Info', startDateTime: '2026-05-15T13:45', endDateTime: '2026-05-15T14:15', description: 'Short setup before switching to Standard Tube B.', source: 'Planner Mock', reasonCode: 'SET-10B-01', workOrderId: 'WO-100280', productCode: 'FG-1002'}),
  machineEvent({id: 'mev-002', lineId: 'line-20', lineName: 'Line 20 - Tube Fill & Seal 2', machineId: 'machine-20b', machineName: 'M-20B Capper', category: 'Maintenance', eventType: 'Preventive Maintenance', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-16T06:00', endDateTime: '2026-05-16T10:00', description: 'Preventive maintenance on capping heads.', source: 'Maintenance Mock', reasonCode: 'PM-20B-01'}),
  machineEvent({id: 'mev-003', lineId: 'line-30', lineName: 'Line 30 - Assembly Line 1', machineId: 'machine-30b', machineName: 'M-30B Assembly Robot', category: 'Downtime', eventType: 'Machine Down', status: 'Blocker', severity: 'Blocker', startDateTime: '2026-05-15T09:30', endDateTime: '2026-05-15T13:30', description: 'Servo fault stopped the assembly robot.', source: 'MES / Planner Mock', reasonCode: 'DWN-30B-01'}),
  machineEvent({id: 'mev-004', lineId: 'line-30', lineName: 'Line 30 - Assembly Line 1', machineId: 'machine-30a', machineName: 'M-30A Feeder', category: 'Changeover / Setup', eventType: 'Setup Started', status: 'Warning', severity: 'Info', startDateTime: '2026-05-15T11:00', endDateTime: '2026-05-15T11:30', description: 'Feeder recipe swap between family runs.', source: 'Planner Mock', reasonCode: 'SET-30A-01'}),
  machineEvent({id: 'mev-005', lineId: 'line-30', lineName: 'Line 30 - Assembly Line 1', machineId: 'machine-30c', machineName: 'M-30C Vision Inspector', category: 'Quality', eventType: 'Quality Hold', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-17T09:00', endDateTime: '2026-05-17T10:00', description: 'Sampling review before low volume release.', source: 'QA Mock', reasonCode: 'QH-30C-01', workOrderId: 'WO-300111', productCode: 'FG-5001'}),
  machineEvent({id: 'mev-006', lineId: 'line-40', lineName: 'Line 40 - Assembly Line 1', machineId: 'machine-40a', machineName: 'M-40A Sterilizer', category: 'Maintenance', eventType: 'Calibration Due', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-16T13:00', endDateTime: '2026-05-16T14:00', description: 'Sterilizer calibration check between campaigns.', source: 'Maintenance Mock', reasonCode: 'CAL-40A-01'}),
  machineEvent({id: 'mev-007', lineId: 'line-50', lineName: 'Line 50 - Packaging Line 1', machineId: 'machine-50d', machineName: 'M-50D Checkweigher', category: 'Quality', eventType: 'Calibration Expired', status: 'Blocker', severity: 'Blocker', startDateTime: '2026-05-16T14:30', endDateTime: '2026-05-16T18:30', description: 'Checkweigher blocked pending recalibration.', source: 'QA Mock', reasonCode: 'CAL-50D-01'}),
  machineEvent({id: 'mev-008', lineId: 'line-50', lineName: 'Line 50 - Packaging Line 1', machineId: 'machine-50c', machineName: 'M-50C Case Packer', category: 'Downtime', eventType: 'Unplanned Downtime', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-16T15:30', endDateTime: '2026-05-16T16:30', description: 'Jam cleared during case packer overlap.', source: 'MES / Planner Mock', reasonCode: 'DWN-50C-01'}),
  machineEvent({id: 'mev-009', lineId: 'line-50', lineName: 'Line 50 - Packaging Line 1', machineId: 'machine-50e', machineName: 'M-50E Palletizer', category: 'Labor', eventType: 'Operator Reassigned', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-17T17:30', endDateTime: '2026-05-17T18:30', description: 'Palletizer handoff slowed by shared labor.', source: 'Planner Mock', reasonCode: 'LAB-50E-01'}),
  machineEvent({id: 'mev-010', lineId: 'line-60', lineName: 'Line 60 - Manual / Rework', machineId: 'machine-60b', machineName: 'M-60B Rework Station', category: 'Changeover / Setup', eventType: 'Setup Started', status: 'Running', severity: 'Info', startDateTime: '2026-05-16T13:30', endDateTime: '2026-05-16T14:00', description: 'Containment setup before validation step.', source: 'Planner Mock', reasonCode: 'SET-60B-01'}),
  machineEvent({id: 'mev-011', lineId: 'line-70', lineName: 'Line 70 - Sterile Finish', machineId: 'machine-70b', machineName: 'M-70B Metrology Station', category: 'Downtime', eventType: 'IT/System Downtime', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-16T09:30', endDateTime: '2026-05-16T10:30', description: 'Measurement software restart delayed the queue.', source: 'MES / Planner Mock', reasonCode: 'DWN-70B-01'}),
  machineEvent({id: 'mev-012', lineId: 'line-70', lineName: 'Line 70 - Sterile Finish', machineId: 'machine-70c', machineName: 'M-70C Final QA Gate', category: 'Material', eventType: 'Material Blocked', status: 'Warning', severity: 'Warning', startDateTime: '2026-05-17T13:00', endDateTime: '2026-05-17T14:00', description: 'Release packet missing one batch attachment.', source: 'eDHR', reasonCode: 'MAT-70C-01', workOrderId: 'WO-700033', productCode: 'FG-7003'}),
];
